use Onpe;
insert LocalVotacion(idDistrito, RazonSocial, Direccion) values

-- ---- AFRICA --- ARGELIA
	( 1855, 'EMBAJADA DEL PERÚ EN ARGELIA', 'N° 14, CALLE 3, PARC PARADO, HYDRA, ARGEL' ),			-- ARGEL

-- ---- AFRICA --- EGIPTO, REPUBLICA ARABE
	( 1856, 'EMBAJADA DEL PERÚ EN EGIPTO', '41 AL-NAHDA STREET, 2° PISO, MAADI, EL CAIRO' ),		-- EL CAIRO

-- ---- AFRICA --- GHANA
	( 1857, 'EMBAJADA DEL PERÚ', '16 PLOT, 1ST CIRCULAR ROAD CANTONMENTS' ),						-- ACCRA

-- ---- AFRICA --- MARRUECOS
	( 1858, 'EMBAJADA DEL PERÚ EN MARRUECOS', '16 RUE D`IFRANE, PLACE DU PÉROU, HASSAN' ),			-- RABAT

-- ---- AFRICA --- SUDAFRICA
	( 1859, 'RESIDENCIA CONNACIONAL GABRIELA PALACIOS-FLUSK', '12 BADGER STREET, FOURWAYS, JOHANNESBURGO' ),	-- JOHANNESBURGO
	( 1860, 'EMBAJADA DEL PERÚ EN SUDÁFRICA', '200 ST. PATRICK RD, MUCKLENEUK, PRETORIA' ),			-- PRETORIA

-- ---- AMERICA --- ANTILLAS HOLANDESAS
	( 1861, 'THE BALLROOM ORANJESTAD', 'CALLE LA SALLESTRAAT 26 LOCAL 4 (AL COSTADO DEL RESTAURANT DON JACINTO Y FRENTE A IMELDA KLEUTERSCHOOL).' ),	-- ARUBA

-- ---- AMERICA --- ARGENTINA
	( 1862, 'ESCUELA NORMAL N° 1 "ROQUE SÁENZ PEÑA"', 'AV. CÓRDOBA 1951, CAPITAL FEDERAL' ),		-- BUENOS AIRES
	( 1862, 'ESCUELA PRIMARIA N° 1', 'AYACUCHO N° 1680, CAPITAL FEDERAL' ),
	( 1862, 'ESCUELA PRIMARIA N° 8', 'TALCAHUANO 680, CAPITAL FEDERAL' ),
	( 1862, 'ESCUELA TÉCNICA N° 25', 'AV. JUJUY 780, CAPITAL FEDERAL' ),
	( 1862, 'ESCUELA TÉCNICA N° 7 "DOLORES LAVALLE DE LAVALLE"', 'CALLE ZAVALETA 204, CAPITAL FEDERAL' ),
	( 1863, 'INADI CATAMARCA', 'JUAN NUÑEZ DEL PRADO 380' ),										-- CATAMARCA
	( 1864, 'ESCUELA JUAN BAUTISTA ALBERDI', 'AV. GENERAL PAZ 488' ),								-- CORDOBA
	( 1865, 'INSTITUTO DE CIENCIAS-OHM', 'SANTA FÉ 1527, CORRIENTES - LAS HERAS 201, CORRIENTES' ),	-- CORRIENTES
	( 1866, '"ESCUELA EGB NO 1 - FRANCISCO A. BERRA"', 'CALLE 8 ESQUINA CALLE 57 LA PLATA' ),		-- LA PLATA
	( 1867, 'SUBSECRETARIA DE JUVENTUD Y SOLIDARIDAD', 'SANTIAGO DEL ESTERO 369' ),					-- LA RIOJA
	( 1868, 'ESCUELA DOMINGO SARMIENTO', 'JULIO ROCA 343, 5TA SECCIÓN, MENDOZA, CIUDAD' ),			-- MENDOZA
	( 1869, 'ESCUELA �REPÚBLICA DEL PERڔ', 'AV. LEANDRO N. ALEM 3069' ),							-- ROSARIO
	( 1870, 'CALLE URQUIZA', 'CALLE URQUIZA 1078 SALTA - CAPITAL' ),								-- SALTA

-- ---- AMERICA --- ARGENTINA
	( 1871, 'AUDITORIO DE "ROTARY CLUB DE COCHABAMBA"', 'AV. AMÉRICA N° 945' ),						-- COCHABAMBA
	( 1872, 'CONSULADO DEL PERÚ EN EL ALTO', 'AV. CÍVICA N° 33 CASI ESQ. AV. SATÉLITE VILLA TEJADA TRIANGULAR' ),	-- EL ALTO
	( 1873, 'COLEGIO INTERNACIONAL DEL SUR', 'AV. HECTOR ORMACHEA ESQUINA CALLE 13, OBRAJES, ZONA SUR, LA PAZ.' ),	-- LA PAZ
	( 1874, 'UNIDAD EDUCATIVA DE FE Y ALEGRIA "NUESTRA SEÑORA DEL CARMEN"', 'CALLE MEDARDO CHAVEZ S/N ENTRE LA CALLE ANTENOR VASQUEZ Y LA AVENIDA SUCRE, BARRIO CENTRAL, RIBERALTA,BOLIVIA' ),	-- RIBERALTA
	( 1875, 'COLEGIO PARTICULAR "NUEVA AMERICA"', 'AVENIDA JAPON N° 3460, SANTA CRUZ DE LA SIERRA, BOLIVIA' ),		-- SANTA CRUZ DE LA SIERRA

-- ---- AMERICA --- BRASIL
	( 1876, 'ESCOLA MUNICIPAL IMACO', 'RUA GON°ALVES DIAS 1180, FUNCIONARIOS - BELO HORIZONTE - MG. CEP 30140-091' ),	-- BELO HORIZONTE
	( 1877, 'EMBAJADA DEL PERÚ EN BRASIL', 'S.E.S AV. DAS NACOES LOTE 43 QUADRA 811 - BRASILIA DF' ),	-- BRASILIA
	( 1878, 'SANTUARIO NOSSA SENHORA DE LOURDES', 'PRAÇA ITALIA, 183, JARDIM BOTÁNICO - CURITIBA/PR' ),	-- CURITIBA
	( 1879, 'CLOD (CENTRO LASER E DIAGNOSE OCULAR)', 'RUA ILDEFONSO ALBANO 1373 - ALDEOTA, FORTALEZA - CE. CEP 60115-000' ),	-- FORTALEZA
	( 1880, 'COLEGIO FRACTAL', ' AV. T. NOVE, 4586 - JARDIM PLANATO - GOIANIA' ),					-- GOIANIA
	( 1881, 'CONSULADO GENERAL DEL PERÚ EN MANAOS', 'AV. CONSTELAÇÃO N°16-A CONJUNTO MORADA DO SOL, BAIRRO ALEIXO - MANAUS / AM. CEP.69.060-081' ),		-- MANAOS
	( 1882, 'CITY HOTEL', 'RUA JOSE MONTAURY N° 20-2° ANDAR, CENTRO, PORTO ALEGRE/RS' ),			-- PORTO ALEGRE
	( 1883, 'CONSULADO GENERAL DEL PERÚ EN RIO BRANCO', 'RUA PERNAMBUCO, N° 1040 - BARRIO BOSQUE - RIO BRANCO - ACRE' ),		-- RIO BRANCO
	( 1884, 'COLEGIO SANTA ROSA DE LIMA', 'RUA VOLUNTARIOS DA PATRIA N° 110 - BOTAFOGO, RIO DE JANEIRO - RJ. CEP 22270-000' ),	-- RIO DE JANEIRO
	( 1885, 'EDIFICIO MAR A VISTA (ANTIGUA SEDE DEL CONSULADO DEL PERÚ)', 'RUA OSWALDO RIBEIRO 198 - SALA 501 - EDIF. MAR A VISTA - ONDINA, SALVADOR � BA. CEP 40170-250' ),	-- SALVADOR
	( 1886, 'ESCOLA ESTADUAL RODRIGUES ALVES', 'AV. PAULISTA, 227, CERQUEIRA CESAR, SAN PABLO/SP' ),	-- SAN PAULO

-- ---- AMERICA --- CANADA
	( 1887, 'PERÚVIAN CANADIAN CULTURAL ASSOCIATION', '10370B 60 AVE. NW, EDMONTON, ALBERTA T6H 1G9' ),	-- EDMONTON
	( 1888, 'RESIDENCIA ESTUDIANTIL EVO', '420, CALLE SHERBROOKE OESTE, MONTREAL, QUEBEC, H3A 1B2' ),	-- MONTREAL
	( 1889, 'VARETTE BUILDING (EDIFICIO DONDE SE UBICA OFICINA SECCIÓN CONSULAR)', '130 ALBERT STREET, SUITE 202, OTTAWA, ONTARIO K1P 5G4, CANAD�' ),	-- OTTAWA
	( 1890, 'METRO HALL (ROTUNDA AND ROOMS 303, 304 Y 310)', '55 JOHN STREET, TORONTO, ONTARIO, M5V 3C6' ),		-- TORONTO
	( 1891, 'CENTRO COMUNAL PARROQUIA OUR LADY OF SORROWS', '555 SOUTH SLOCAN STREET, VANCOUVER COLUMBIA BRITÁNICA, V5K 3X5' ),		-- VANCOUVER
	( 1892, 'CASA DE LA CONSUL HONORARIA DEL PERÚ EN WINNIPEG', '76 CORAL REEF COVE, WINNIPEG, MANITOBA, R3X 1X3' ),	-- WINNIPEG

-- ---- AMERICA --- CHILE
	( 1893, 'INFOCA', 'CALLE SUCRE 631 ANTOFAGASTA' ),												-- ANTOFAGASTA
	( 1894, 'COLISEO AUGUSTO ZUBIRI RUBIO (EX EPICENTRO 1)', 'CALLE PABLO PICASSO 2150, POBLACIÓN SAN MARCOS' ),	-- ARICA
	( 1895, 'PARROQUIA DE LA MERCED', 'CASTELLÓN 624, CONCEPCIÓN' ),								-- CONCEPCION
	( 1896, 'CASA DE ACOGIDA NUESTRA SEÑORA DE GUADALUPE', 'AV. LOS LOROS 847 POBLACION PEDRO LEON GALLO' ),	-- COPIAPO
	( 1897, 'LICEO BERNARDO O`HIGGINS', 'PASEO BAQUEDANO 1200 IQUIQUE' ),							-- IQUIQUE
	( 1898, 'ESCUELA BÁSICA PROVIDENCIA', 'MANUEL MONTT 485, PROVIDENCIA' ),						-- SANTIAGO	
	( 1898, 'ESCUELA REPÚBLICA DE ALEMANIA', 'LIBERTAD 1242, SANTIAGO' ),
	( 1898, 'INSTITUTO NACIONAL JOSÉ MIGUEL CARRERA', 'ARTURO PRAT 33, SANTIAGO' ),
	( 1898, 'LICEO 1 JAVIERA CARRERA', 'COMPAÑIA DE JESÚS 1484, SANTIAGO' ),
	( 1898, 'LICEO 7 LUISA SAAVEDRA', 'MONSEÑOR SOTERO SANZ 60, PROVIDENCIA' ),
	( 1898, 'LICEO ARTURO ALESSANDRI', 'GRAL. BUSTAMANTE 443, PROVIDENCIA' ),
	( 1898, 'LICEO JOSÉ VICTORINO LASTARRIA', 'MIGUEL CLARO 32, PROVIDENCIA' ),
	( 1899, 'ESCUELA BÁSICA DE GRECIA', 'AVENIDA PEDRO MONTT N° 2357' ),							-- VALPARAISO

-- ---- AMERICA --- COLOMBIA
	( 1900, 'EDIFICIO EXECUTIVE TRADE CENTER', 'CARRERA 51 N° 79-34 OFICINA 501' ),					-- BARRANQUILLA
	( 1901, 'UNIVERSIDAD SERGIO ARBOLEDA', 'CALLE 74 N° 14-14' ),									-- BOGOTA
	( 1902, 'BARRIO CIUDAD JARDIN', 'CARRERA 101 N°11B-12' ),										-- CALI
	( 1903, 'CASA MUSEO RAFAEL NUÑEZ', 'CARRERA 2 N°41-89' ),										-- CARTAGENA
	( 1904, 'CONSULADO GENERAL DEL PERÚ EN LETICIA', 'CALLE 11 #5-32' ),							-- LETICIA
	( 1905, 'EDIFICIO STAFF', 'CARRERA 43B N° 16-41' ),												-- MEDELLIN

-- ---- AMERICA --- COSTA RICA
	( 1906, 'ESCUELA UNIFICADA REPÚBLICA DEL PERÚ - VITALIA MADRIGAL', 'CALLE 7, SAN JOSÉ. COSTADO DE PARQUE MORAZ�N' ),	-- SAN JOSE

-- ---- AMERICA --- CUBA
	( 1907, 'EMBAJADA DEL PERÚ EN CUBA', 'CALLE 8 N° 307, E/3RA. Y 5TA., PLAYA,' ),					-- LA HABANA

-- ---- AMERICA --- ECUADOR
	( 1908, 'CASA DEL MIGRANTE DE CUENCA', 'CALLE LUIS CORDERO 5-43, ENTRE HONORATO VÁZQUEZ Y JUAN JARAMILLO' ),	-- CUENCA
	( 1909, 'CONSULADO GENERAL DEL PERÚ EN GUAYAQUIL', 'AVENIDA FRANCISCO DE ORELLANA EDIFICIO "CENTRUM" PISO 13 OFICINA 04, URBANIZACI�N KENNEDY NORTE, PARROQUIA DE TARQUI - GUAYAQUIL.' ),	-- GUAYAQUIL
	( 1910, 'CONSULADO GENERAL DEL PERÚ EN LOJA', 'CALLE ZOILO RODRIGUEZ 03-05 Y CLODOVEO CARRIÓN' ),	-- LOJA
	( 1911, 'CONSULADO GENERAL DEL PERÚ EN MACHALA', 'MZNA. 14 VILLA 11 URBANIZACIÓN UNIORO, CANTON MACHALA.' ),	-- MACHALA
	( 1912, 'UNIDAD EDUCATIVA MUNICIPAL SEBASTIÁN DE BENALCÁZAR', 'AVENIDA 6 DE DICIEMBRE E IRLANDA N° E-1077, FRENTE AL CONSULADO GENERAL DEL PERÚ EN QUITO' ),	-- QUITO

-- ---- AMERICA --- EL SALVADOR	
	( 1913, 'EMBAJADA DEL PERÚ EN EL SALVADOR', 'AVENIDA MASFERRER NORTE 17P, CUMBRES DE LA ESCALON, COLONIA ESCALON, SAN SALVADOR, EL SALVADOR' ),		-- SAN SALVADOR

-- ---- AMERICA --- ESTADOS UNIDOS DE AMERICA
	( 1914, 'THE LATIN AMERICAN ASSOCIATION', '2750 BUFORD HIGHWAY, ATLANTA, GA 30324' ),			-- ATLANTA
	( 1915, 'MADISON PARK HIGH SCHOOL', '75 MALCOLN X BLVD., ROXBURY, MA 02120' ),					-- BOSTON
	( 1916, 'RAMADA PLAZA HOTEL', '212 WEST WOODLAWN RD, CHARLOTTE, NC 28217' ),					-- CHARLOTTE
	( 1917, 'THE CONGRESS PLAZA HOTEL & CONVETION CENTER', '520 SOUTH MICHIGAN AVENUE, CHICAGO, ILLINOIS 60605' ),	-- CHICAGO
	( 1918, 'GREENHILL SCHOOL', '4141 SPRING VALLEY RD. ADDISON, TEXAS, 75001' ),					-- DALLAS
	( 1919, 'PARROQUIA SAN CAYETANO', '4335 W. BYERS PL. DENVER, COLORADO 80219' ),					-- DENVER
	( 1920, 'RED BULL ARENA', '600 CAP MAY STREET, HARRISON, NJ 07029' ),							-- HARRISON, N.J.
	( 1921, 'GREATER SCHOOL ACADEMY OF THE ARTS - HIGH SCHOOL', '172 HUYSHOPE AVE., HARTFORD, CT 06106' ),	-- HARTFORD
	( 1922, 'JUDSON ROBINSON JR. COMMUNITY CENTER', '2020 HERMANN DRIVE, TX 77004' ),				-- HOUSTON
	( 1923, 'ROBERT F. KENNEDY COMMUNITY SCHOOLS', '701 S. CATALINA ST., LOS ANGELES, CA 90005' ),	-- LOS ANGELES
	( 1924, 'MIAMI - DADE COUNTY FAIR EXPOSITION', '10901 SW 24TH ST. MIAMI FL 33165' ),			-- MIAMI
	( 1925, 'HUB NOLA LLC', '4035 WASHINGTON AVE., NEW ORLEANS, LA 70125' ),						-- NUEVA ORLEANS
	( 1926, 'QUEENS COLLEGE', '65-30 KISSENA BLVD FLUSHING NY 11367' ),								-- NUEVA YORK
	( 1927, 'CARIDADES CATOLICAS', '1232 N CLASSEN BLVD OKLAHOMA CITY, OK73106' ),					-- OKLAHOMA CITY
	( 1928, 'CENTRAL HIGH SCHOOL', '4525 N CENTRAL AVE., PHOENIX, AZ 85012' ),						-- PHOENIX
	( 1929, 'HOTEL SHERATON - CANYONS BALLROOM', '150 WEST 500 SOUTH - SALT LAKE CITY UT 84101' ),	-- SALT LAKE CITY
	( 1930, 'ALAMO COLLEGES', '201 W. SHERIDAN STREET, BUILDING E, TX 78204' ),						-- SAN ANTONIO
	( 1931, 'DISCOVERY CHARTE SCHOOL', '1100 CAMINO BISCAY, CHULA VISTA, CA 91910' ),				-- SAN DIEGO
	( 1932, 'CITY COLLEGE OF SAN FRANCISCO - MISSION CAMPUS', '106 BARTLETT ST, SAN FRANCISCO, CA 94110 (ESQUINA CON 22ND ST.)' ),	-- SAN FRANCISCO
	( 1933, 'CONSULADO HONORARIO DEL PERÚ EN SAINT LOUIS', '10123 CORPORATE SQUARE, SAINT LOUIS, MISSOURI 63132' ),	-- SAN LOUIS
	( 1934, 'AUDITORIO DEL COLEGIO ST. JOHN', '123 N. 79TH ST. (1ST AVE NW), SEATTLE, WA 98103' ),	-- SEATLE
	( 1935, 'TAMPA CONVENTION CENTER', '"333 SOUTH FRANKLIN ST. TAMPA, FL 33602SALAS 23, 24 Y 25"' ),	-- TAMPA
	( 1936, 'GEORGE MASON HIGH SCHOOL', '7124 LEESBURG PIKE, FALLS CHURCH, VA 22043' ),				-- VIRGINIA
	( 1936, 'MARY ELLEN HERDENSON MIDDLE SCHOOL', '7134 LEESBURG PIKE, FALLS CHURCH, VA 22043' ),
	
-- ---- AMERICA --- GUATEMALA
	( 1937, 'EMBAJADA DEL PERÚ EN GUATEMALA', '13 CALLE 14-24 ZONA 13' ),							-- GUATEMALA

-- ---- AMERICA --- GUAYANA FRANCESA
	( 1938, 'CONSULADO DEL PERÚ EN CAYENNE', '99, RUE DU LIEUTENANT BECKER BP 541, 97333 CAYENNE � GUYANE FRAN°AISE' ),	-- CAYENA/GUAYANA FRANCESA

-- ---- AMERICA --- HAITI
	( 1939, 'CONSULADO DEL PERÚ EN PUERTO PRÍNCIPE', '40 RUE LAMARRE, PUERTO PRÍNCIPE, HAITÍ' ),	-- PUERTO PRINCIPE

-- ---- AMERICA --- HONDURAS
	( 1940, 'EMBAJADA DEL PERÚ EN HONDURAS', 'COLONIA LOMAS DEL GUIJARRO, CALLE PRINCIPAL, EDIFICIO TORRE ALFA 4°PISO' ),		-- TEGUCIGALPA

-- ---- AMERICA --- MEXICO
	( 1941, 'ASOCIACION PROVIDENCIA DE COLONOS AC', 'BOGOTA NRO. 3000, COLONIA PROVIDENCIA NORTE, C.P.44630, GUADALAJARA.' ),	-- GUADALAJARA
	( 1942, 'LICEO FRANCO MEXICANO', 'HOMERO 1521, COLONIA POLANCO, DELEGACION MIGUEL HIDALGO, C.P. 11560, MEXICO D.F.' ),		-- MEXICO D.F.
	( 1943, 'CONSULADO DEL PERÚ EN MONTERREY', 'LOMA ALTA NRO. 2335, COLONIA LOMA LARGA, MONTERREY.' ),		-- MONTERREY
	
-- ---- AMERICA --- NICARAGUA
	( 1944, 'EMBAJADA DEL PERÚ EN NICARAGUA', 'BOLONIA. DEL PORTÓN PRINCIPAL DEL ANTIGUO HOSPÍTAL MILITAR UNA CUADRA AL LAGO, DOS CUADRAS ABAJO. CASA N° 325.' ),	-- MANAGUA

-- ---- AMERICA --- PANAMA
	( 1945, 'SALON KUNA DEL HOTEL FOUR POINTS BY SHERATON', 'MILLENNIUM PLAZA, AV. A. WAKED, CORREDOR ZONA LIBRE, COLÓN' ),			-- COLON
	( 1946, 'SALA DE REUNIONES DEL CUARTEL DE BOMBEROS JUAN M. ARANGO', 'AV. CENTRAL Y CALLE CENTRAL (FRENTE A LA GOBERNACIÓN)' ),	-- DAVID
	( 1947, 'CENTRO DE CONFERENCIAS TORRES DE LAS AMERICAS', 'PUNTA PACIFICA Y PUNTA DARIEN' ),		-- PANAMA
	( 1948, 'CONSULADO GENERAL DEL PERÚ EN SANTIAGO', 'CALLE MANUEL CELESTINO GONZÁLES EDIFICIO TERRAZA, 1ER PISO, OFICINA 3' ),	-- SANTIAGO

-- ---- AMERICA --- PARAGUAY
	( 1949, 'UNIVERSIDAD DEL PACIFICO', 'CALLE O`HIGGINS S/N ESQUINA CON AUSTRIA, ASUNCIÓN' ),		-- ASUNCION

-- ---- AMERICA --- PUERTO RICO
	( 1950, 'SEDE DE LA GUARDIA NACIONAL DE PUERTO RICO', 'CALLE GENERAL ESTEVES # 100 (PARADA 3 1/2) SAN JUAN, PUERTO RICO 00902' ),	-- SAN JUAN

-- ---- AMERICA --- REPUBLICA DOMINICANA
	( 1951, 'COLEGIO LA SALLE', 'AV. JUAN PABLO DUARTE NO. 88, SANTIAGO DE LOS CABALLEROS' ),		-- SANTIAGO DE LOS CABALLEROS
	( 1952, 'EMBAJADA DEL PERÚ EN LA REPÚBLICA DOMINICANA', 'CALLE LAS NINFAS NO. 18, ESQUINA CON CALLE LOS HELIOS, SECTOR BELLA VISTA, SANTO DOMINGO' ),	-- SANTO DOMINGO
	
-- ---- AMERICA --- TRINIDAD Y TOBAGO
	( 1953, 'EMBAJADA DEL PERÚ EN TRINIDAD Y TOBAGO', '12 ALEXANDRA ST., SAINT CLAIR, PORT OF SPAIN, W.I..' ),	-- PUERTO ESPA�A

-- ---- AMERICA --- URUGUAY
	( 1954, 'PARROQUIA DE LA ASUNCIÓN, MADRE DE LOS MIGRANTES', 'AV. LUIS ALBERTO DE HERRERA 2231' ),	-- MONTEVIDEO

-- ---- AMERICA --- VENEZUELA
	( 1955, 'CASA PARROQUIAL, AL LADO DE LA CATEDRAL DE BARCELONA, ESTADO ANZOATEGUI', 'CALLE EL JUNCAL S/N, BARCELONA ESTADO ANZOATEGUI' ),	-- BARCELONA
	( 1956, 'ATENEO DE BARQUISIMETO', 'CALLE 23, ENTRE CARRERAS 17 Y 18 (FRENTE A LA PLAZA LARA), BARQUISIMETO, ESTADO LARA' ),		-- BARQUISIMETO
	( 1957, 'COLEGIO "MARIA AUXILIADORA"', '4TA AVENIDA CON 7MA TRANSVERSAL, URB. ALTAMIRA, CHACAO, ESTADO MIRANDA' ),		-- CARACAS
	( 1958, 'PARROQUIA SAN ALFONSO MARIA DE LIGORIO', 'AVENIDA 27 CON CALLE 70, N. 69-70 SECTOR SANTA MARÍA (FRENTE AL COLEGIO PARTICULAR SANTA �NGELA), MARACAIBO, ESTADO ZULIA' ),	-- MARACAIBO
	( 1959, 'CLUB MAMPATARE', 'CALLE SAN MARTIN S/N (TRANSVERSAL AL SENIAT, DETRÁS DE LA IGLESIA CRISTO DEL BUEN VECINO), PAMPATAR, ESTADO NUEVA ESPARTA' ),		-- PAMPATAR
	( 1960, 'UNIDAD EDUCATIVA "JARDIN LEVANTE"', 'URB. RORAIMA, CALLE BOLIVAR, S/N, DIAGONAL AL HOSPITAL UYAPAR, ALTA VISTA SUR, PUERTO ORDAZ, ESTADO BOLIVAR' ),	-- PUERTO ORDAZ
	( 1961, 'ESCUELA BÁSICA NACIONAL "LA CONCORDIA"', 'PROLONGACIÓN 5TA AVENIDA "FRANCISCO GARCÍA DE HEVIA", ENTRE CALLES 5 Y 6, PARROQUIA LA CONCORDIA (FRENTE A HELADER�A MAX CREAM), SAN CRISTOBAL, ESTADO TACHIRA' ),	-- SAN CRISTOBAL
	( 1962, 'COLEGIO "JUAN XXIII"', 'CALLE SAN ENRIQUE N. 85-70 EL TRIGAL CENTRO (FRENTE A LA CASA DEL GOBERNADOR), VALENCIA, ESTADO CARABOBO' ),	-- VALENCIA

-- ---- ASIA --- ARABIA SAUDITA
	( 1963, 'EMBAJADA DEL PERÚ EN EL REINO DE ARABIA SAUDITA', 'CALLE IBN YOUNES AL �SADAFI, VILLA 7393, DISTRITO DE NORTHERN MAATHAR. CERCA A LA INTERSECCI�N DE LAS AVENIDAS PRINCE TURKI Y PRINCE MUHAMMAD IBN ABDULAZIZ (TAHLIAH).' ),	-- RIAD

-- ---- ASIA --- CHINA, REPUBLICA POPULAR	
	( 1964, 'EMBAJADA DEL PERÚ EN LA REPÚBLICA POPULAR CHINA', '1-91, SANLITUN DIPLOMATIC COMPOUND, 1 WORKERS STADIUM NORTH ROAD, DISTRICT CHAOYANG, BEIJING' ),	-- BEIJING (PEKIN)
	( 1965, 'INTERNATIONAL FINANCE CENTER (IFC)', 'IFC TOWER, 5 ZHUJIANG XI LU, 32 FLOOR,TIANHE-GUANGZHOU' ),	-- GUANGZHOU
	( 1966, 'CONSULADO GENERAL DEL PERÚ EN HONG KONG Y MACAO', '"UNIT 1401, 14/F, CHINA MERCHANTS TOWER168-200 CONNAUGHT ROAD CENTRALSHEUNG WAN, HONG KONG"' ),		-- HONG KONG
	( 1967, 'CONSULADO GENERAL DE PERÚ EN SHANGHAI', '1515 NANJING WEST ROAD. EDIFICIO 1 JINGAN KERRY CENTRE, SUITE 2705, DISTRITO JINGAN, SHANGHAI' ),				-- SHANGHAI

-- ---- ASIA --- COREA DEL SUR, REPUBLICA DE
	( 1968, 'EMBAJADA DEL PERÚ EN COREA DEL SUR', 'N° 1305 � CORYO DAEYUNGAK TOWER TOEGYERO 97, JUNG �GU, SE�L' ),	-- SEUL

-- ---- ASIA --- EMIRATOS ARABES UNIDOS
	( 1969, 'AL HABTOOR BUSINESS TOWER - CONSULADO GENERAL DEL PERÚ EN DUBAI', 'AL HABTOOR BUSINESS TOWER - PISO 25, DUBAI MARINA' ),	-- DUBAI

-- ---- ASIA --- FILIPINAS
	( 1970, 'CONSULADO GENERAL HONORARIO DEL PERÚ EN MANILA', 'SUITES 404-405,CLMC BLDG. 259-269 EDSA GREENHILLS, MANDALUYONG CITY, MANILA 1554' ),		-- MANILA

-- ---- ASIA --- INDIA
	( 1971, 'EMBAJADA DEL PERÚ EN LA INDIA', 'D-2/5, VASANT VIHAR, NEW DELHI, INDIA' ),				-- NUEVA DELHI

-- ---- ASIA --- INDONESIA
	( 1972, 'EMBAJADA DEL PERÚ EN INDONESIA', 'MENARA RAJAWALI, PISO 12. JL. DR IDE AGUNG GDE AGUNG LOT #5.1. KAWASAN MEGA KUNINGAN, JAKARTA12950' ),	-- JAKARTA

-- ---- ASIA --- ISRAEL
	( 1973, 'EMBAJADA DEL PERÚ EN ISRAEL', 'MEDINAT HAYEHUDIM, 60 - HERZLIYA PITUACH - ENTRABA B PISO 2' ),		-- HERZLIYA PITUACH

-- ---- ASIA --- JAPON
	( 1974, 'FUKUOKA KEN KOKUSAI KORYU CENTER KOKUSAI HIROBA, 3°PISO KORYU SHITSU (EXCHANGE ROOM)', 'ACROS FUKUOKA, 1-1-1 TENJIN, CHUO KU, FUKUOKA SHI, C.P.810-0001' ),	-- FUKUOKA
	( 1975, 'PRIOR PALACE ISESAKI', 'GUNMA KEN ISESAKI SHI SHOWA CHO 3827 C.P.372-0014' ),			-- GUNMA
	( 1976, 'HIROSHIMA SHI RYUGAKUSEI KAIKAN', '1-1 NISHI-KOJIN-MACHI, MINAMI-KU HIROSHIMA CITY, C.P.732-0806' ),	-- HIROSHIMA
	( 1977, 'ROUTE TSUKUBA', 'IBARAKI KEN TSUKUBA SHI HANAMURO 1145-3 C.P.305-0025' ),				-- IBARAKI
	( 1978, 'KANNAI ARAI HALL (PISO 11)', 'KANAGAWA KEN YOKOHAMA SHI NAKA KU ONOE CHO 1-8 KANNAI ARAI BUILDING 11F C.P.231-0015' ),	-- KANAGAWA
	( 1979, 'KOBE SHI KINROU KAIKAN, 2° PISO TAMOKUTEKI HALL', '5-1-2 KUMOI DORI, CHUO KU, KOBE SHI, C.P.651-0096' ),	-- KOBE
	( 1980, 'KUSATSU SHI MACHIDUKURI CENTER, CUARTO 301 Y 302', '"9-6 NISHI OOJI CHO, KUSATSU SHI, SHIGA KENC�DIGO POSTAL .525-0037"' ),	-- KUSATSU
	( 1981, 'I.M.Y BUILDING, 3° Y 4° PISO', '"3-7-14 AOI, HIGASHI KU, NAGOYA SHI , AICHI KENC�DIGO POSTAL 461-0004"' ),	-- NAGOYA
	( 1982, 'NAHA SHI BUNKA TEMBUS KAN, 3° PISO GALERÍA', '"3-2-10, MAKISHI, NAHA SHI C.P. 900-0013"' ),	-- OKINAWA
	( 1983, 'HELLO KASHI KAIGISHITSU OMIYA HIGASHIGUCHI (PISO 5)', 'SAITAMA KEN SAITAMA SHI OMIYA KU NAKA CHO 1-54-3 VISIONARY III 5F C.P. 330-0845' ),	-- SAITAMA
	( 1984, 'TKP HAMAMATSU ACT TOWER (PISO 25)', 'SHIZUOKA KEN HAMAMATSU SHI NAKA KU ITAYA MACHI 111-2 HAMAMATSU ACT TOWER 25F C.P. 430-7725' ),		-- SHIZUOKA
	( 1985, 'SUZUKA SHIMIN KAIKAN, 2° PISO TENJI SHITSU', '1-18-18 KANBE, SUZUKA SHI, C.P.513-0801' ),		-- SUZUKA
	( 1986, 'TOCHIGI KENNAN CHIIKI JIBA SANGYO SHINKO CENTER', 'TOCHIGI KEN ASHIKAGA SHI TANAKA CHO 32-11 C.P.326-0822' ),		-- TOCHIGI
	( 1987, 'AP SHINAGAWA (PISO 7)', 'TOKYO TO MINATO KU TAKANAWA 3-25-23 KEIKYU DAI NI BUILDING 7F C.P.108-0074' ),			-- TOKIO

-- ---- ASIA --- JORDANIA
	( 1988, 'CONSULADO HONORARIO DEL PERÚ EN AMMAN', 'CALLE DE LA REINA RANIA, CALLE DE LA UNIVERSIDAD DE JORDANIA, EN FRENTE DEL PERI�DICO AL STOUR EDIFICIO (JORDAN BOOK CENTER) N° 152, AMMAN' ),	-- AMMAN

-- ---- ASIA --- KUWAIT
	( 1989, 'EMBAJADA DEL PERÚ EN KUWAIT', 'FLOOR 6, AL ARABIYA TOWER, AHMAD AL JABER STREET, SHARQ, KUWAIT' ),		-- AL - KUWAIT

-- ---- ASIA --- LIBANO
	( 1990, 'CONSULADO HONORARIO DEL PERÚ EN BEIRUT', 'VICA HOUSE - 4TH FLOOR - SAMI EL SOLH AVENUE, BEIRUT' ),		-- BEIRUT

-- ---- ASIA --- MALASIA
	( 1991, 'EMBAJADA DEL PERÚ EN MALASIA', 'WISMA SELANGOR DREDGING, SOUTH TOWER, 6TH FLOOR, JALAN AMPANG 142 A, 50450 KUALA LUMPUR' ),	-- KUALA LUMPUR

-- ---- ASIA --- QATAR
	( 1992, 'EMBAJADA DEL PERÚ EN QATAR', 'STREET 835, BUILDING 42, ZONE 64, LEJBAILAT, P.O. BOX 24062, DOHA' ),	-- DOHA

-- ---- ASIA --- SINGAPUR
	( 1993, 'EMBAJADA DEL PERÚ EN SINGAPUR', '"390 ORCHARD ROAD #12-03 PALAIS RENAISSANCE SINGAPORE 238871"' ),		-- SINGAPUR

-- ---- ASIA --- TAILANDIA
	( 1994, 'EMBAJADA DEL PERÚ EN TAILANDIA', '16/F GLAS HAUS BLDG. NO.1, SUKHUMVIT 25, WATTANA, BANGKOK 10110' ),	-- BANGKOK

-- ---- ASIA --- TURQUIA
	( 1995, 'SEDE DE LA EMBAJADA DEL PERÚ', 'RESIT GALIP CAD. NO:70/1 GOP' ),						-- ANKARA
	( 1996, 'OFICINA DE LA ALIANZA DEL PACÍFICO', 'IN°N° CAD. ONGAN APT. NO: 43/5 KAT:2 34437 GÓMÁSSUYU/TAKSIM' ),	-- ESTAMBUL

-- ---- ASIA --- VIETNAN
	( 1997, 'EMBAJADA DEL PERÚ', '1402, CORNERSTONE BUILDING, 16 PHAN CHU TRINH, HOAN KIEM, HANOI' ),	-- HANOI

-- ---- EUROPA --- ALEMANIA
	( 1998, 'EMBAJADA DEL PERÚ EN LA REPÚBLICA FEDERAL DE ALEMANIA', 'MOHRENSTRASSE 42, 5TO PISO, 10117 BERLÍN' ),	-- BERLIN
	( 1999, 'CONSULADO HONORARIO DEL PERÚ EN BREMEN', 'MARTINISTR. 58, 28195 BREMEN' ),				-- BREMEN
	( 2000, 'CONSULADO GENERAL DEL PERÚ EN FRANKFURT', 'KAISERSTRASSE 74, 63065 OFFENBACH AM MAIN' ),	-- FRANKFURT
	( 2001, 'CONSULADO GENERAL DEL PERÚ EN HAMBURGO', 'BLUMENSTR. 28, 22301 HAMBURG' ),				-- HAMBURGO
	( 2002, 'CONSULADO GENERAL DEL PERÚ EN MÜNICH', 'HERZOG HEINRICH 23, MÜNICH 80336' ),			-- MUNICH

-- ---- EUROPA --- ANDORRA, PRINCIPADO DE	
	( 2003, 'CENTRE CULTURAL LA LLACUNA, SALA D`ACTES', '"C/. MOSSÖN CINTO VERDAGUER, 4 - 6 AD500 ANDORRA LA VELLA"' ),	-- ANDORRA

-- ---- EUROPA --- AUSTRIA
	( 2004, 'EMBAJADA DEL PERÚ EN AUSTRIA', 'MAHLERSTRASSE 7/22, 1010. VIENA. AUSTRIA' ),			-- VIENA

-- ---- EUROPA --- BELGICA
	( 2005, 'OFICINA DE CÓNSUL HONORARIO', 'SCHAELI�NSTRAAT 3, 2000 AMBERES.' ),					-- AMBERES
	( 2006, 'COLEGIO SAINT MICHEL', 'BLD. SAINT MICHEL 24, 1040 BRUSELAS' ),						-- BRUSELAS
	( 2007, 'HOTEL CASTEL', 'KON. MARIA HENDRIKAPLEIN 9, 9000 GANTE' ),								-- GANTE
	( 2008, 'PENTAHOTEL', 'BLD. DE LA SAUVENI�RE 100, 4000 LIEJA' ),								-- LIEJA

-- ---- EUROPA --- BIELORRUSIA
	( 2009, 'OFICINA CONSULADO HONORARIO', 'CALLE CHKALOVA 12, OFICINA 408, MINSK 220039' ),		-- MINSK

-- ---- EUROPA --- CROACIA
	( 2010, 'CONSULADO EN ZAGREB', 'JURISICEVA 24, 10000 ZAGREB' ),									-- ZAGREB

-- ---- EUROPA --- DINAMARCA
	( 2011, 'TIVOLI CONGRESS CENTER', 'ARNI MAGNUSSONS GADE 2-4 DK-1577 KOBENHAVN V' ),				-- COPENHAGUE	

-- ---- EUROPA --- ESPAÑA
	( 2012, 'PABELLÓN MUNICIPAL MOISËS RUIZ', 'C/. NIJAR N°2, ALMERÍA 04006' ),					-- ALMERIA
	( 2013, 'PALAU SANT JORDI, MONJUIC', 'PASSEIG OLIMPIC 5-7, 08038 BARCELONA' ),					-- BARCELONA
	( 2014, 'COLEGIO NUESTRA SRA. DE BEGOÍA (JESUITAS INDAUTXU)', 'CALLE MARÍA DÍAZ DE HARO 29, BILBAO' ),	-- BILBAO
	( 2015, 'ESPAI CIVIC MERCADAL', 'CALLE CRISTOFOR GROBER 8 BAJOS, 170001, GIRONA' ),				-- GERONA
	( 2016, 'CONSULADO DE LAS PALMAS DE GRAN CANARIA', 'CALLE GENERAL MAS DE GAMIDE 45 - 35006, PALMAS DE GRAN CANARIA' ),	-- LAS PALMAS DE GRAN CANARIA
	( 2017, 'CENTRO LATINOAMERICANO DE LLEIDA', 'CALLE GENERAL BRITO, 5, BAJOS 25007 LÉRIDA' ),		-- LERIDA
	( 2018, 'IFEMA - FERIA DE MADRID', 'PABELLÓN N° 7 - AVDA. DEL PARTEN°N, 5 28042 MADRID' ),		-- MADRID
	( 2019, 'CONSULADO DEL PERÚ EN MÁLAGA', 'CALLE MARBELLA 7° 1° PLANTA, 29640, FUENGIROLA, MALAGA' ),	-- MALAGA
	( 2020, 'CEIP AINA MOLL I MARQUÉS', 'PLAZA BERENGUER DE PALOU, 6 (PLAZA DE LOS PATINES)' ),		-- MALLORCA	
	( 2021, 'OFICINA DE ATENCIÓN AL INMIGRANTE', 'PLAZA DEL LAGO ENOL S/N VENTANIELLES - 33010 OVIEDO' ),	-- OVIEDO
	( 2022, 'CENTRO INTEGRADO MUNICIPAL VISTAHERMOSA', 'CALLE RAMON DE MESONEROS ROMANOS 10-20 - URB. VISTA HERMOSA, 37008 SALAMANCA' ),	-- SALAMANCA
	( 2023, 'CENTRO DE EMPLEO', 'PLAZA IRENEO GONZÁLEZ, 1 - 38003 SANTA CRUZ DE TENERIFE' ),		-- SANTA CRUZ DE TENERIFE
	( 2024, 'CENTRO SOCIAL POLIVALENTE HOGAR VIRGEN DE LOS REYES.', 'C/. FRAY ISIDORO DE SEVILLA N°1, SEVILLA 41009' ),	-- SEVILLA
	( 2025, 'AYUNTAMIENTO DE TARRAGONA', 'PLAZA DE LA FONT 1 TARRAGONA' ),							-- TARRAGONA
	( 2026, 'INSTITUTO DE EDUCACIÓN SECUNDARIA LUIS VIVES', 'CALLE MARQUES DE SOTELO N° 10, 46002, VALENCIA' ),	-- VALENCIA
	( 2027, 'CENTRO MUNICIPAL DE DISTRITOS DEL CASCO VELLO', 'RÍA OLIVA, 12 - VIGO' ),				-- VIGO
	( 2028, 'PARROQUIA EL PORTILLO', 'CALLE MONSEÑOR OSCAR ROMERO NO. 1, 3 BAJOS - 50004 ZARAGOZA' ),	-- ZARAGOZA
	
-- ---- EUROPA --- FINLANDIA
	( 2029, 'EMBAJADA DEL PERÚ EN FINLANDIA', 'L�NNROTINKATU 7 B 11 HELSINKI' ),					-- HELSINKY

-- ---- EUROPA --- FRANCIA
	( 2030, 'CONSULAT DU P�ROU � BORDEAUX', '20-22 RUE SAINT R�MI 33000 BORDEAUX' ),				-- BURDEOS
	( 2031, 'FOYER PAROISSIAL DE SAINT-PIERRE-LE-JEUNE CATHOLIQUE', '4, RUE GLOXIN � 67000 STRASBOURG FRANCE' ),	-- ESTRASBURGO
	( 2032, 'RESTAURANT L�INCA', '42 BIS RUE DE TROIS MOLLETTES 59000 LILLE FRANCE' ),				-- LILLE
	( 2033, 'SALLE MUNICIPALE', '24 RUE VERLET HANUS 69003 LYON FRANCE' ),							-- LYON
	( 2034, 'HOTEL MERCURE MARSEILLE CENTRE VIEUX PORT', '2, RUE NEUVE SAINT MARTIN, 13001 MARSELLA' ),	-- MARSELLA
	( 2035, 'COLLEGE RAOUL DUFY', '30 AVENUE RAOUL DUFY, 06200 NICE, FRANCE' ),						-- NIZA
	( 2036, 'LYC�E ESPAGNOL � LUIS BU�UEL �', '38 BOULEVARD VICTOR HUGO, 92200 NEUILLY-SUR-SEINE' ),	-- PARIS
	( 2037, 'MAISON DE QUARTIER CENTRE MERIEL', '5 RUE PAUL MERIEL 31000 TOULOUSE' ),				-- TOULOUSE

-- ---- EUROPA --- GRAN BRETA�A
	( 2038, 'MILLBANK ACADEMY', 'ERASMUS STREET, SW1P 4HR, LONDRES' ),								-- LONDRES

-- ---- EUROPA --- GRECIA
	( 2039, 'EMBAJADA DEL PERÚ EN LA REPÚBLICA HELÉNICA', 'KOUMBARI 2, KOLONAKI � ATENAS.' ),		-- ATENAS
	( 2040, 'CONSULADO HONORARIO EN SALÓNICA', 'CALLE MONASTIRIOU #192, TERCER PISO, CP546 28 SAL�NICA' ),	-- SALONICA

-- ---- EUROPA --- HOLANDA
	( 2041, 'CONSULADO GENERAL DEL PERÚ EN AMSTERDAM', 'EDIFICIO COENGEBOUW - KABELWEG 37, 1014 BA �MSTERDAM' ),	-- AMSTERDAM

-- ---- EUROPA --- HUNGRIA
	( 2042, 'CONSULADO GENERAL HONORARIO DEL PERÚ EN HUNGRÍA', 'V�CI �T 168 ( RENO UDVAR - EDIFICIO T ) 1138 BUDAPEST. HUNGR�A.' ),		-- BUDAPEST

-- ---- EUROPA --- IRLANDA
	( 2043, 'TERENURE COLLEGE', 'TEMPLEOGUE RD, DUBLIN 6W, CO. DUBLIN' ),							-- DUBLIN

-- ---- EUROPA --- ITALIA
	( 2044, 'PARROQUIA "LA SAGRADA FAMILIA"', 'VIA DON BOSCO, 1 - ANCONA' ),						-- ANCONA
	( 2045, 'CENTRO INTERCULTURALLE MASSIMO ZONARELLI', 'VIA GIOVANNI ANTONIO SACCO, 14, 40127 BOLOGNA' ),	-- BOLONIA
	( 2046, 'PARROCHIA S. PIO X AL SODO', 'VIA DELLE PANCHE 212, FIRENZE 50141' ),					-- FLORENCIA
	( 2047, 'LICEO STATALE ANDREA DORIA', 'VIA ARMANDO DIAZ 8 16121 GENOVA' ),						-- GENOVA
	( 2048, 'FORUM DE ASSAGO', 'VIA GIUSEPPE DI VITTORIO, 6, 20090 ASSAGO MI' ),					-- MILAN
	( 2049, 'CONSULADO HONORARIO DEL PERÚ EN N°POLES', 'VIA SANTA BRIGIDA 51, NAPOLES.' ),			-- NAPOLES
	( 2050, 'ESCUELA "SAN BERNARDINO DI BETTO"', 'VIALE ROMA 15, PERÚGIA' ),						-- PERÚGIA
	( 2051, 'CENTRO STUDI MANIERI', 'VIA FALERIA N° 21, 00183 - ROMA' ),							-- ROMA
	( 2052, 'PARROCCHIA DI SANTA MARIA MAGGIORE', 'VIA COLLEGIO NRO 6, TRIESTE' ),					-- TRIESTE
	( 2053, 'LINGOTTO FIERE (PABELLON 5)', 'VIA NIZZA N° 280 TURIN' ),								-- TURIN

-- ---- EUROPA --- LUXEMBURGO, GRAN DUCADO DE
	( 2054, 'CENTRO CULTURAL ALTRIMENTI', 'AVENUE MARIE-TH�R�SE 5, L-2132 LUXEMBURGO' ),			-- LUXEMBURGO

-- ---- EUROPA --- MACEDONIA
	( 2055, 'CONSULADO EN SKOPJE', 'BUL. KOCO RACIN 38/1-5, 1000 SKOPJE' ),							-- SKOPJE

-- ---- EUROPA --- NORUEGA
	( 2056, 'CITYBOX OSLO', 'PRINSENS GATE 6 NO-0152 OSLO NORGE' ),									-- OSLO

-- ---- EUROPA --- POLONIA
	( 2057, 'EMBAJADA DEL PERÚ EN POLONIA', 'UL. STAROSCINSKA 1 M 3, 02-516 VARSOVIA' ),			-- VARSOVIA

-- ---- EUROPA --- PORTUGAL
	( 2058, 'EMBAJADA DEL PERÚ EN PORTUGAL', 'RUA CASTILHO 50, 4� PISO. DERECHO. 1250-071 LISBOA' ),	-- LISBOA

-- ---- EUROPA --- REPUBLICA CHECA
	( 2059, 'EMBAJADA DEL PERÚ EN LA REPÚBLICA CHECA', 'MUCHOVA 9, PRAGA 6 - 160 00, PRAGA, REPÚBLICA CHECA.' ),	-- PRAGA

-- ---- EUROPA --- RUMANIA
	( 2060, 'EMBAJADA DEL PERÚ EN RUMANIA', 'STRADA MAIOR GHEORGHE SONTU NO. 10-12, ET 3 AP 10. SECTOR 1, 014031 BUCAREST' ),	-- BUCAREST
	( 2061, 'CONSULADO EN TIMISOARA', 'STRADA ORAVITA NO. 2/D, 300244 TIMISOARA' ),					-- TIMISOARA

-- ---- EUROPA --- RUSIA
	( 2062, 'INSTITUTO DE LATINOAMERICA - ACADEMIA DE CIENCIAS DE RUSIA', 'CALLE B. ORDYNKA 21, MOSC� 115035' ),	-- MOSCU
	( 2063, 'OFICINA CONSULADO HONORARIO', '10-12,9 SOVETSKAYA,(ENTRADA POR LA CALLE MAISIENKO), ST. PETERSBURGO 191144' ),	-- SAN PETERSBURGO

-- ---- EUROPA --- SUECIA
	( 2064, 'CLARION HOTEL STOCKHOLM', 'RINGV�GEN 98, 104 60 STOCKHOLM' ),							-- ESTOCOLMO
	( 2065, 'RADISSON BLU HOTEL MALM�', '�STERGATAN 10 SE-211 25 MALM�, SVERIGE' ),					-- MALMO

-- ---- EUROPA --- SUIZA
	( 2066, 'PH BERN', 'HELVETIAPLATZ 2. CH-3005 BERNA' ),											-- BERNA
	( 2067, 'SALLE COMMUNALE POINT FAVRE', 'AVENUE F.-A. GRISON 6 � 1225 CH�NE-BOURG' ),			-- GINEBRA
	( 2068, 'SALON DE ACTIVIDADES DE LA IGLESIA PROTESTANTE DE NEUMUNSTER', 'SEEFELDSTRASSE 91, 8008, ZURICH' ),	-- ZURICH

-- ---- EUROPA --- UCRANIA
	( 2069, 'EMPRESA"ENTENSO LTD"', 'CALLE DEVICHIYA 6, CODIGO POSTAL 61002' ),						-- KHARKOV
	( 2070, 'CONSULADO HONORARIO DEL PERÚ EN UCRANIA', 'NABEREZHNO-KHRESHATITSKAYA 25 OFICINA "A", CODOGO POSTAL 04070' ),	-- KIEV

-- ---- EUROPA --- YUGOSLAVIA
	( 2071, 'CONSULADO EN BELGRADO', 'SURDULICKA 5, 11040 BELGRADO' ),								-- BELGRADO

-- ---- OCEANIA --- AUSTRALIA
	( 2072, 'HOLLY SPIRIT CATHOLIC CHURCH/PARISH OFFICE', '16 VILLERS STREET NEW FARM QLD 4005' ),	-- BRISBANE
	( 2073, 'EMBAJADA DEL PERÚ EN AUSTRALIA', '40 BRISBANE AVENUE, GROUND FLOOR, BARTON, ACT 2600, CANBERRA - AUSTRALIA.' ),	-- CAMBERRA
	( 2074, 'ST BRIGID �S CATHOLIC CHURCH', '378 NICHOLSON ST, FITZROY NORTH VIC 3068' ),			-- MELBOURNE
	( 2075, 'BOB DANIEL COMMUNITY CENTRE', 'INGLEWOOD WA 6052 PERTH' ),								-- PERTH
	( 2076, 'ST. ANDREWS CATHEDRAL SCHOOL', 'SYDNEY SQUARE SYDNEY NSW 2000 (ESTACI�N TOWN HALL)' ),	-- SIDNEY

-- ---- OCEANIA --- NUEVA ZELANDA
	( 2077, 'AUCKLAND DEAF SOCIETY', 'POTTERS PARK, EVENTS CENTRE, 164 BALMORAL RD. AUCKLAND 1024' )-- AUCKLAND