use Onpe;
insert LocalVotacion(idDistrito, RazonSocial, Direccion) values

-- ---- AMAZONAS --- BAGUA
	(    1, 'IE 16201', 'AV. 28 DE JULIO SN' ),														-- ARAMANGO
	(    1, 'IE MIGUEL MONTEZA TAFUR', 'AV. 28 DE JULIO SN' ),
	(    2, 'IE 16192 5 DE JUNIO', 'AV. MARIANO MELGAR SN' ),										-- BAGUA
	(    2, 'IE 16193 BAGUA', 'JR. COMERCIO N° 364' ),
	(    2, 'IE AGROPECUARIO TORIBIO RODRIGUEZ DE MENDOZA', 'AV. AGROPECUARIO C-2' ),
	(    3, 'IE 16239', 'JR. RODRIGUEZ DE MENDOZA N° 651' ),										-- COPALLIN
	(    4, 'IE 16273', 'JR. ALFONSO UGARTE N° 270' ),												-- EL PARCO
	(    5, 'IE 16318', 'JR. RICARDO PALMA SN' ),													-- IMAZA
	(    5, 'IE 16351 JOSE KISTUG PUJUPAT', 'AV. AUTUKAI SN' ),
	(    5, 'IE 16352', 'COMUNIDAD NATIVA YAMAYAKAT' ),
	(    5, 'IE 16357', 'COMUNIDAD NATIVA KUNCHIN' ),
	(    5, 'IE 16714 SUWIKAI TSAKIM MIYAN', 'COMUNIDAD NATIVA PAANTAM (SAWIT)' ),
	(    5, 'IE 16725 WAVAMPIAK', 'CCPP WAYAMPIAK' ),
	(    5, 'IE 16729 WAWAS', 'JR. LIRIO SN' ),
	(    5, 'IE 17088', 'CCPP CUZUMATAC' ),
	(    5, 'IE ALBERTO ACOSTA HERRERA', 'AV. IMAZA N° 100' ),
	(    5, 'IE JOSE GABRIEL CONDORCANQUI', 'CARRETERA WAWICO URAKUSA' ),
	(    5, 'IE TUPAC AMARU', 'AV. PRINCIPAL N° 220' ),
	(    5, 'IST TSAMAJAIN', 'AV. PRINCIPAL N° 201' ),
	(    6, 'IE 16275 LA PECA', 'AV. SAN FELIPE N° 486' ),											-- LA PECA
	(    6, 'IE 16277', 'JR. PORFIRIO IZQUIERDO SN' ),
	(    6, 'IE 16279 EL ARRAYAN', 'JR. LA FLORIDA - SAN MARTIN SN' ),
	(    6, 'IE 16281', 'AV. BAGUA SN' ),
	(    6, 'IE 16283', 'AV. CORONEL BENITES SN' ),
	(    6, 'IE 16288 PRIMARIA', 'JR. LIBERTAD SN' ),
	(    6, 'IE 31 NUESTRA SEÑORA DE GUADALUPE - FE Y ALEGRIA', 'JR. MARAÑÓN SN' ),

-- ---- AMAZONAS --- BONGARA
	(    7, 'IE 18088', 'CALLE AMARGURA S/N' ),														-- CISQUILLA
	(    8, 'IE 348', 'PSJ. LOS FICUS S/N BARRIO LA UNION' ),										-- CHURUJA
	(    9, 'IE 18259 RAFAEL JULIAN LOPEZ', 'CARRETERA BALSAPATA - KM 10' ),						-- COROSHA
	(   10, 'IE 18083', 'JR. RAMON CASTILLA 520' ),													-- QUISPES
	(   11, 'IE 18092 POMACOCHAS', 'JR. POMACOCHAS S/N' ),											-- FLORIDA
	(   12, 'IE 18322 ABRAHAN LOPEZ LUCERO', 'AV. SAN CARLOS S/N' ),								-- JAZAN
	(   13, 'IE 18079', 'JR. EMIGDIO LOPEZ HUAMAN 345' ),											-- JUMBILLA
	(   14, 'IE 18094', 'JR. INDEPENDENCIA SN' ),													-- RECTA
	(   15, 'IE 18096', 'CALLE SANTA CATALINA' ),													-- SAN CARLOS
	(   16, 'IE 18104 SANTO TOMAS', 'JR. TORIBIO RODRIGUEZ DE MENDOZA 264' ),						-- SHIPASBAMBA
	(   17, 'IE 18099', 'CALLE PALMAS' ),															-- VALERA
	(   18, 'IE JOSE DE SAN MARTIN - EL PROGRESO', 'AV. FERNADNO BELAUNDE TERRY S/N' ),				-- YAMBRASBAMBA
	(   18, 'IE TORIBIO RODRIGUEZ DE MENDOZA', 'FERNANDO BELAUNDE TERRY KM 435-5' ),

-- ---- AMAZONAS --- CHACHAPOYAS 
	(   19, 'IE 18010 - GONCHA', 'BARRIO SHAMBAR' ),												-- ASUNCION
	(   20, 'IE 18012 BALSAS	', 'JR. EL MAESTRO 130' ),											-- BALSAS
	(   21, 'IE 18002 MARIA AUXILIADORA', 'JR. PIURA CDRA 9' ),										-- CHACHAPOYAS
	(   21, 'IE 18288 ISABEL LYNCH DE RUBIO', 'JR. AYACUCHO 870' ),
	(   21, 'IEP VIRGEN ASUNTA', 'JR. LA MERCED 655' ),
	(   22, 'IE 18017', 'JR. ALFONSO UGARTE S/N' ),													-- CHETO
	(   23, 'IE 18023 VITUYA CHILIQUIN', 'PLAZA DE ARMAS' ),										-- CHILLIQUIN
	(   24, 'IE OCTAVIO ORTIZ ARRIETA', 'JR. EL PROGRESO S/N' ),									-- CHUQUIBAMBA
	(   25, 'IE 18037 JOSE ANTONIO ENCINA FRANCO', 'JR. AMARGURA S/N' ),							-- GRANADA
	(   26, 'IE 18040', 'JR. SIMON BOLIVAR S/N' ),													-- HUANCAS
	(   27, 'IE 18041 PURIFICACION CULQUI PUIQUIN', 'JR. SAN FELIPE 590' ),							-- LA JALCA
	(   27, 'IE 18043', 'CALLE AYACUCHO S/N - FRENTE A LA PLAZA' ),
	(   28, 'IE SAN AGUSTIN', 'JR. SAN CRISTOBAL S/N' ),											-- LEIMEBAMBA
	(   29, 'IE 18052 PADRE BLAS VALERA PEREZ', 'JR. SANTO DOMINGO 264' ),							-- LEVANTO
	(   30, 'IE CESAR VALLEJO', 'JR. LIBERTAD 135 ' ),												-- MAGDALENA
	(   31, 'IE SEÑOR DE LOS MILAGROS', 'JR. LIMATAMBO S/N' ),										-- MARISCAL CASTILLA
	(   32, 'IE 18061', 'JR. AMAZONAS 347' ),														-- MOLINOPAMPA
	(   33, 'IE 18065', 'JR. SANTA ROSA S/N' ),														-- MONTEVIDEO
	(   34, 'IE 18066', 'JR. JERUSALEN S/N' ),														-- OLLEROS
	(   35, 'IE 18068', 'JR. TRIUNFO S/N - PLAZA DE ARMAS' ),										-- QUINJALCA
    (   36, 'IE SAN FRANCISCO PIPUS', 'PSJ. EL ESTUDIANTE 188' ),									-- SAN FRANCISCO DE DAGUAS
	(   37, 'IE 18056', 'PSJ. DOS DE MAYO S/N' ),													-- SAN ISIDRO DE MAINO
	(   38, 'IE 18074', 'JR. BOLIVAR S/N' ),														-- SOLOCO
	(   39, 'IE 18077', 'CARRETERRA A SONCHE' ),													-- SONCHE

-- ---- AMAZONAS --- CONDORCANQUI	
	(   40, 'IE 16342 HUAMPAMI', 'CALLE COMERCIAL SN' ),											-- EL CENEPA
	(   40, 'IE 16345 MAMAYAQUE', 'COMUNIDAD NATIVA MAMAYAQUE' ),
	(   40, 'IE 16347 PAMPA ENTSA', 'COMUNIDAD NATIVA PAMPA ENTSA' ),
	(   40, 'IE 16348 KUSUNUNPATKAIM - CUSU CHICO', 'COMUNIDAD NATIVA KUSUNUNPATKAIM CUSU CHICO' ),
	(   40, 'IE 16364 SHAIM', 'COMUNIDAD NATIVA SHAIM' ),
	(   40, 'IE 16741 KUSUKUBAIM', 'COMUNIDAD NATIVA KUSUKUBAIM' ),
	(   40, 'IE 16745 DE TUTINO', 'COMUNIDAD NATIVA TUTINO' ),
	(   40, 'IE SECUNDARIA DE MENORES WAWAIN', 'COMUNIDAD NATIVA WAWAIM' ),
	(   41, 'IE 16296 NIEVA PRIMARIA', 'JR. EL PORVENIR SN' ),										-- NIEVA
	(   41, 'IE 16305', 'CCPP CAYAMAS' ),
	(   41, 'IE 16309', 'CCPP TAYUNTSA' ),
	(   41, 'IE 16705', 'AV. GERARDO WIPO SN' ),
	(   41, 'IE 16708', 'CALLE MARAÑON SN' ),
	(   41, 'IE 16712 KIGKIS', 'CALLE CHIJIP SN' ),
	(   41, 'IE 16714 SUWIKAI TSAKIM MIYAN', 'CCPP PAANTAM' ),
	(   41, 'IE 17104', 'CCPP PUMPUSHAK' ),
	(   41, 'IE NIEVA SECUNDARIA', 'JR. EL PORVENIR N° 310' ),
	(   42, 'IE 16336 BELEN', 'PLAZA BELEN - CCPP BELEN' ),											-- RIO SANTIAGO
	(   42, 'IE 16337 SAN RAFAEL', 'CENTRO POBLADO MENOR SAN RAFAEL' ),
	(   42, 'IE 16338', 'CCPP CUCUASA' ),
	(   42, 'IE 16375', 'CALLE PECSA SN' ),
	(   42, 'IE 16738 CANDUNGOS', 'CCPP CANDUNGOS' ),
	(   42, 'IE PUERTO GALILEA', 'RIO SANTIAGO - PUERTO GALILEA' ),
	(   42, 'IEP 16736 PUERTO GALILEA', 'AV. ZACARIAS SN' ),
	
-- ---- AMAZONAS --- LUYA
	(   43, 'IE BRAULIO DE CAMPOREDONDO', 'AV. PROGRESO 705' ),										-- CAMPORREDONDO
	(   44, 'IE 18117', 'JR. CHICLAYO S/N' ),														-- COCABAMBA
	(   44, 'IE 18269', 'QUISQUI' ),	
	(   45, 'IE CRISTOBAL BENQUE COLCAMAR', 'JR. SAN FRANCISCO S/N' ),								-- COLCAMAR
	(   46, 'IE 18113 DIVINO NIÑO DEL MILAGRO', 'JR. ALFONSO UGARTE S/N' ),							-- CONILA			
	(   47, 'IE 18130', 'JR. SUCRE S/N' ),															-- INGUILPATA
	(   48, 'IE 18109 LUIS GERMAN MENDOZA PIZARRO', 'AV. BLAS VALERA 479' ),						-- LAMUD
	(   49, 'IE 18138', 'AV. PEDRO GONZALES S/N' ),													-- LONGUITA
	(   50, 'IE 18134 MONSEÑOR ORTIZ ARRIETA', 'JR. ORTIZ ARRIETA 291' ),							-- LONYA CHICO
	(   51, 'IE 18132 JOSE ANTONIO ENCINAS FRANCO', 'JR. SAN MARTIN N° 810' ),						-- LUYA
	(   52, 'IE 18142', 'JR. AMAZONAS' ),															-- LUYA VIEJO
	(   53, 'IE HORACIO ZEVALLOS GAMES', 'JR. SAN MARTIN' ),										-- MARIA
	(   54, 'IE SAN SIMON', 'JR. LA CULTURA 315' ),													-- OCALLI
	(   55, 'IE 18153 TUPAC AMARU', 'BARRIO TUPAC AMARU' ),											-- OCUMAL
	(   56, 'IE 18172 TOMASA OYARCE SALDAÑA', 'SAN MIGUEL' ),										-- PISUQUIA
	(   56, 'IE CIRO ALEGRIA YOMBLON', 'CALLE YOMBLON S/N' ),
	(   56, 'IE JOSE CARLOS MARIATEGUI', 'VILLA PRINCIPAL' ),
	(   56, 'IE RICARDO PALMA', 'CCPP PIRCAPAMPA' ),
	(   57, 'IE CESAR VALLEJO', 'PROVIDENCIA S/N' ),												-- PROVIDENCIA
	(   58, 'IE 18156', 'AV. BONGARA S/N' ),														-- SAN CRISTOBAL
	(   59, 'IE 212', 'JR. SIMON BOLIVAR S/N' ),													-- SAN FRANCISCO DE YESO
	(   60, 'IE 18184', '28 DE JULIO 250' ),														-- SAN JERONIMO
	(   61, 'IE 18139', 'JR. SAN JUAN 450' ),														-- SAN JUAN DE LOPECANCHA
	(   62, 'IE 18200', 'JR. SANTA CATALINA' ),														-- SANTA CATALINA
	(   62, 'IE 18266 YURI RANGEL GOMEZ', 'JR. SANTA ROSA S/N' ),
	(   63, 'IE SAN SALVADOR', 'JR. AMAZONAS S/N' ),												-- SANTO TOMAS
	(   63, 'IE SANTO TOMAS', 'AV. DOS DE MAYO 394' ),
	(   64, 'IE JORGE BASADRE', 'JR. ESPAÑA S/N' ),													-- TINGO
	(   65, 'IE 18205 JOSE R ARCE TUESTA', 'JR. CHACHAPOYAS S/N' ),									-- TRITA

-- ---- AMAZONAS --- RODRIGUEZ DE MENDOZA
	(   66, 'IE 18215', 'ENTRADA A CHIRIMOTO' ),													-- CHIRIMOTO
	(   67, 'IE SAN MARCOS', 'JR. HUAMBO S/N' ),													-- COCHAMAL
	(   68, 'IE 18290', 'JR. AMARGURA S/N' ),														-- HUAMBO
	(   69, 'IE 18029 SAN FRANCISCO', 'JR. SANTO TORIBIO 101' ),									-- LIMABAMBA
	(   70, 'IESM AUGUSTO SALAZAR BONDY', 'JR. AUGUSTO SALAZAR BONDY S/N' ),						-- LONGAR
	(   71, 'IE SAGRADO CORAZON DE JESUS', 'PASJE. DANIEL ALCIDES CARRION S/N' ),					-- MARISCAL BENAVIDES
	(   72, 'IE 18244', 'AV. AMAZONAS S/N' ),														-- MILPUCC
	(   73, 'IE 18331 JOSE CARLOS MARIATEGUI', 'JR. LA LIBERTAD S/N' ),								-- OMIA
	(   73, 'IE 18407 MARIO VARGAS LLOSA', 'JR. SORITOR S/N' ),
	(   73, 'IE 18428 TELMO ABSALON QUISPE DIAZ', 'JR. AMAZONAS S/N' ),
	(   73, 'IE ANTONIO RAIMONDY', 'JR. JORGE CHAVEZ 175' ),
	(   74, 'IE 18207 SAN NICOLAS', 'JR. SAN NICOLAS 320' ),										-- SAN NICOLAS
	(   75, 'IE 18249 SANTA ROSA', 'AV. SANTA ROSA S/N' ),											-- SANTA ROSA
	(   76, 'IE 18251 TOTORA', 'MARGEN DERECHO CARRETERA A MENDOZA LIMABAMBA' ),					-- TOTORA
	(   77, 'IE 18305', 'PLAZA MAYOR' ),															-- VISTA ALEGRE
	(   77, 'IE 18427', 'CCPP SALAS' ),
 	
-- ---- AMAZONAS --- UTCUBAMBA
	(   78, 'IE 16211', 'JR. SIMON BOLIVAR N° 239' ),												-- BAGUA GRANDE
	(   78, 'IE 17065 JULIO C TELLO', 'AV. BAGUA GRANDE N°450' ),
	(   78, 'IE 17074 PEDRO E PAULET MOSTAJO', 'JR. SAN MARTIN N° 1368' ),
	(   78, 'IE 38 FE Y ALEGRIA', 'AV. MARIANO MELGAR N° 860' ),
	(   78, 'IEI INICIAL 203', 'JR. RICARDO PALMA SN' ),
	(   78, 'IST JOSE SANTOS CHOCANO', 'JR. HIPOLITO UNANUE N° 201' ),
	(   78, 'IST PUBLICO UTCUBAMBA', 'JR. LAS DELICIAS N° 380' ),
	(   79, 'COLISEO CERRADO DE CAJARURO', 'JR. SAN MIGUEL SN' ),									-- CAJARURO
	(   79, 'IE 16229', 'JR. TRIUNFO N° 301' ),
	(   79, 'IE ERNESTO VILLANUEVA MUÑOZ', 'JR. SAN JAEN SN' ),
	(   80, 'IE 16245', 'AV. HIPOLITO UNANUE N° 441' ),												-- CUMBA
	(   80, 'IE CESAR ABRAHAM VALLEJO MENDOZA', 'JR. SANTA ROSA SN' ),
	(   81, 'IE 16217', 'AV. LAMBAYEQUE SN' ),														-- EL MILAGRO
	(   82, 'IE 16255', 'JR. MIGUEL GRAU SN' ),														-- JAMALCA
	(   82, 'IE RICARDO PALMA', 'AV. SANTA ROSA SN' ),
	(   83, 'IE 16263', 'JR. SAN MARTIN N° 151' ),													-- LONYA GRANDE
	(   83, 'IE JORGE BASADRE', 'CALLE ELINA CARREAZO SN' ),
	(   84, 'IE ENRIQUE LOPEZ ALBUJAR', 'PLAZA DE ARMAS DE YAMON' )								-- YAMON