use Onpe;
insert LocalVotacion(idDistrito, RazonSocial, Direccion) values

-- ---- ANCASH --- AIJA
	(   85,'IE 86136 MEDALLA MILAGROSA','JR. JACINTO PALACIOS 425' ),								-- AIJA
	(   86,'IE IE 86153 CORIS','AV. PROGRESO' ),													-- CORIS
	(   87,'IE 86161 VIRGEN DEL CARMEN','JR. PROGRESO' ),											-- HUACLLAN
	(   88,'IE 86147 SANTA CRUZ DE RUREK','AV. MAGDALENA ALVA' ),									-- LA MERCED
	(   88,'IE VICENTE GUERRERO PALACIOS','RARAMAPAMPA' ),
    (   89,'IE 86151','JR. RAMON CASTILLA 308' ),													-- SUCCHA

-- ---- ANCASH --- ANTONIO RAYMONDI
    (   90,'IE 86180 TUPAC AMARU II - PRIMARIA','BARRIO TINTICUCHO' ),								-- ACZO
    (   90,'IE 86201 SAN PEDRO DE UCHUPATA','CALLE MAGISTRAL SN' ),
    (   91,'IE 86183 RICARDO PALMA SORIANO','PLAZA DE ARMAS DE CHACCHO' ),							-- CHACCHO
    (   92,'IE JULIO C TELLO','JR. JULIO C TELLO SN' ),												-- CHINGAS
    (   93,'IE 86174 CESAR A VALLEJO MENDOZA','PLAZA DE ARMAS 310' ),		         				-- LLAMELLIN
    (   94,'IE 86231 MANUEL GONZALES PRADA','AV. ANTONIO RAIMONDI SN' ),							-- MIRGAS
    (   94,'IE SANTA ISABEL','JR. ANCASH SN' ),
    (   95,'IE INTEGRADO CRISTO JESUS','AV. RAYMONDI SN' ),											-- SAN JUAN DE RONTOY

-- ---- ANCASH --- ASUNCION
    (   96,'IE 86344 INTEGRADO JAVIER HERAUD PEREZ','CALLE PRINCIPAL SN' ),							-- ACOCHACA
    (   97,'IE MAESTRO UGO DE CENSI','JR. MUSHAYACO SN' ),											-- CHACAS

-- ---- ANCASH --- BOLOGNESI
    (   98,'IE 86243 VICTOR ANDRES BELAUNDE LLACLLA','AV. ABELARDO PARDO LEZAMETA' ),				-- ABELARDO PARDO LEZAMETA
    (   99,'IE 86244 LUIS PARDO NOVOA','JR. LUIS PARDO' ),											-- ANTONIO RAIMONDI
    (  100,'IE 86216 SAN MIGUEL','JR. SIMON BOLIVAR' ),												-- AQUIA
    (  101,'IE 86291 SAN AGUSTIN','AV. SAN AGUSTIN' ),												-- CAJACAY
    (  102,'IE 86247 BENDITA MAGDALENA - PRIMARIA','JR. SIMON BOLIVAR' ),							-- CANIS
    (  103,'IE 86211 CORONEL BOLOGNESI','AV. SANTA ROSA 700' ),										-- CHIQUIAN
    (  103,'IE 86214 GUILLERMO BRACALE RAMOS','JR. FIGUEREDO 820' ),
    (  104,'IE 20850 MARISCAL ANDRES AVELINO CACERES - SECUNDARIA','AV. ALBERTO DE LAS CASAS' ),	-- COLQUIOC
    (  105,'IE JOSE CARLOS MARIATEGUI','JR. 28 DE JULIO' ),											-- HUALLANCA
    (  106,'IE 86223 SANTA MARIA','JR. BOLIVAR' ),													-- HUASTA
    (  106,'IE 86226 POMAPATA','AV. ALFONSO UGARTE' ),
    (  107,'IE 86230','CALLE LLANJA' ),																-- HUAYLLACAYAN
    (  107,'IE 86713 JOSE MARIA ARGUEDAS','AV. LOS FUNDADORES' ),
    (  108,'IE 86235 SAN LORENZO DE GORGORILLO','JR. FRANCISCO BOLOGNESI 306' ),					-- LA PRIMAVERA
    (  109,'IE 86234 SAN FRANCISCO','CALLE TUPAC AMARU' ),											-- MANGAS
    (  110,'IE 86238 TUPAC AMARU','JR. BOLOGNESI' ),												-- PACLLON
    (  110,'IE 86239 NUESTRA SEÑORA DE GUADALUPE - SECUNDARIA','AV. BOLOGNESI' ),
    (  111,'IE 86242 ERMENEGILDO BRIOS','JR. SIMON BOLIVAR' ),										-- SAN MIGUEL DE CORPANQUI
    (  112,'IE 86240 JOAQUIN COTRINA VALVERDE','AV. ANCASH' ),										-- TICLLOS

-- ---- ANCASH --- CARHUAZ
    (  113,'IE 86280 RICARDO PALMA','AV. SANTA TERESA' ),											-- ACOPAMPA
    (  114,'IE 86289 VIRGEN DE NATIVIDAD','CALLE NUEVA' ),											-- AMASHCA
    (  115,'IE 86278 MARIO TORRES MEZARINA','JR. CONSTITUCION' ),									-- ANTA
    (  116,'IE 86288 CARHUAC','CARRETERA PRINCIPAL CARHUAC SN' ),									-- ATAQUERO
    (  117,'IE 86269 MARIA AUXILIADORA','JR. UNIÓN SN' ),											-- CARHUAZ
    (  117,'IE NUESTRA SEÑORA DE LAS MERCEDES','AV. SANTA ROSA' ),
    (  118,'IE 86276 ANTONIO LOLI LAREDO','AV. ANTONIO RAYMONDI 230' ),								-- MARCARA
    (  118,'IE 86277 MARIO VAZQUEZ VARELA','PARQUE PLAZUELA DE VICOS' ),
    (  119,'IE 86284 APOSTOL SANTIAGO','AV. CENTRAL' ),												-- PARIAHUANCA
    (  120,'IE 86290 SAGRADO CORAZON DE JESUS','AV. CARRION MATTOS' ),								-- SAN MIGUEL DE ACO
    (  120,'IE 86816','PLAZUELA ATOCPAMPA' ),
    (  121,'IE 86291 SAN JUAN BAUTISTA','AV. PERU' ),												-- SHILLA
    (  122,'IE 86285 SR DE LOS MILAGROS','CARRETERA SALIDA A MISHQUI' ),							-- TINCO
    (  123,'IE SANTIAGO ANTUNEZ DE MAYOLO','PLAZA DE ARMAS' ),										-- YUNGAR

-- ---- ANCASH --- CARLOS FERMIN FITZCARRALD
    (  124,'IE 86375 DANIEL BADIALI MASIRONI','PRLG JOSE OLAYA 36' ),								-- SAN LUIS
    (  124,'IE 86376 HORACIO ZEBALLOS GAMEZ','CALLE FACUNDO CLEMENTE SN' ),
    (  124,'IE 86378 SANTA ROSA','JR. FITZCARRALD SN' ),
    (  124,'IE 86379 SEÑOR DE POMALLUCAY','CARRETERA YAUYA SN' ),
    (  124,'IE 86456 TARAPAMPA','CARRETERA ENTRADA A TARAPAMPA SN' ),
    (  124,'IE CARLOS FERMIN FITZCARRALD','JR. JOSE OLAYA SN' ),
    (  125,'IE 84156','CCPP RANCHAJ' ),																-- SAN NICOLAS
    (  125,'IE SANTIAGO ANTUNEZ DE MAYOLO','AV. MAGISTERIAL SN' ),
    (  126,'IE 84129 CESAR VALLEJO','JR. 28 DE JULIO SN' ),											-- YAUYA
    (  126,'IE 84153','AV. TAMBO REAL DE HUANCABAMBA SN' ),

-- ---- ANCASH --- CASMA    
    (  127,'IE 88110 NUESTRA SEÑORA DE FATIMA','AV. VILLARREAL SN' ),								-- BUENA VISTA ALTA
    (  128,'IE 88100 INMACULADA CONCEPCION','AV. MIRAFLORES SN' ),									-- CASMA
    (  128,'IE 88102 REPUBLICA DE CHILE','PRLG NEPEÑA MZ A LOTE 29' ),
    (  128,'IE 88212 ANTONIO RAYMONDI','AV. PERU' ),								
    (  128,'IEP SANTA ISABEL DE HUNGRIA','URB FRAY MARTIN MZ D LOTE E' ),
    (  129,'IE 88105 JUAN NOEL LASTRA','CALLE LOS ESTUDIANTES SN' ),								-- COMANDANTE NOEL
    (  130,'IE 88116 JOSE MARIA ARGUEDAS','CARRETERA LAGO CANTARILLAS' ),							-- YAUTAN
    (  130,'IE 89015','CALLE SANTIAGO ANTUNEZ DE MAYOLO MZ J LOTE 1' ),

-- ---- ANCASH --- CORONGO
    (  131,'IE SAN FRANCISCO - PRIMARIA Y SECUNDARIA','JR. ACOPAMPA SN' ),							-- ACO
    (  132,'IE 88129 ERNESTO SANCHEZ FAJARDO','JR. SUAREZ YULFO' ),									-- BAMBAS
    (  133,'IE 88127 SAN PEDRO SECUNDARIA','JR. PROGRESO 703' ),									-- CORONGO
    (  134,'IE 88130 INTEGRAL JORGE BASADRE','JR. SUAREZ YULFO' ),									-- CUSCA
    (  134,'IE SAN ANTONIO PRIMARIA- SECUNDARIA','CARRETERA CENTRAL' ),
    (  135,'IE 88132 SANTIAGO ANTUNEZ DE MAYOLO','JR. LEONCIO PRADO 302' ),							-- LA PAMPA
    (  136,'IE 88134 PEDRO PABLO ATUSPARIA','AV. MARISCAL CASTILLA SN' ),							-- YANAC
    (  137,'IE 88136 SAN PABLO','CALLE SAN PABLO' ),												-- YUPAN

-- ---- ANCASH --- HUARAZ
    (  138,'IE 86061 COCHABAMBA','PSJ. BARRIO DEL CERCADO' ),										-- COCHABAMBA
    (  139,'IE 86063','AV. MANCO CAPAC' ),															-- COLCABAMBA
    (  140,'IE 86054 JAVIER ROMERO MAGUIÑA - PRIMARIA','JR. MIRAMAR' ),								-- HUANCHAY
    (  140,'IE 86058 BARNER MYER','2 CUADRAS DE LA PLAZA DE ARMAS' ),
    (  141,'FACULTAD DE CIENCIAS MEDICAS - UNASAM','AV. AGUSTIN GAMARRA' ),							-- HUARAZ
    (  141,'IE 19 FE Y ALEGRIA','AV. CONFRATERNIDAD INTERNACIONAL ESTE' ),
    (  141,'IE PARROQUIAL SANTA ROSA DE VITERBO','JR. RAMON CASTILLA 1219' ),
    (  141,'IE PEDRO PABLO ATUSPARIA','AV. BOLOGNESI 116' ),
    (  141,'IE SEÑOR DE LA SOLEDAD','JR. 28 DE JULIO' ),
    (  142,'IE 86002 JORGE BASADRE GROHMAN','AV. AUGUSTO B LEGUIA 416' ),							-- INDEPENDENCIA
    (  142,'IE 86017 SABIO ANTONIO RAIMONDI','AV. CENTENARIO 283' ),
    (  142,'IE GRAN UNIDAD ESCOLAR MARISCAL TORIBIO DE LUZURIAGA','AV. CENTENARIO 998' ),
    (  142,'IE SIMON ANTONIO BOLIVAR PALACIOS','AV. CONFRATERNIDAD INTERNACIONAL OESTE 493' ),
    (  142,'INSTITUTO SUPERIOR DE EDUCACIÓN PÚBLICA','AV. LAS FLORES' ),
    (  143,'IE 86043 VIRGEN DE LAS MERCEDES','JR. ANTONIO LOLI LAREDO' ),							-- JANGAS
    (  144,'IE 86059 VIRGEN DE NATIVIDAD','AV. CENTENARIO' ),										-- LA LIBERTAD
    (  145,'IE 86045 CESAR VALLEJO','JR. DAGOBERTO CACERES 106' ),									-- OLLEROS
    (  146,'IE SAN JERONIMO','AV. ALEJANDRO ARDILES CAJA' ),										-- PAMPAS GRANDE
    (  147,'IE 86066','AV. GONZALO SALAZAR 801' ),													-- PARIACOTO
    (  147,'IE 86127 SAN JOSE','CARRETERA HUARAZ PARIACOTO' ),
    (  148,'IE 86064 CORONEL PEDRO PABLO PALACIOS','AV. ANTONIO RAYMONDI' ),						-- PIRA
    (  148,'IE 86125 SAGRADO CORAZON DE JESUS','JR. RAMON CASTILLA 1219' ),
    (  148,'IE 86126 HERMILIO BALDIZAN','JR. RAMON CASTILLA' ),
    (  148,'IE 86131','JR. MIGUEL GRAU' ),
    (  149,'IE 86048 CESAR VALLEJO MENDOZA','CARRETERA CENTRAL' ),									-- TARICA

-- ---- ANCASH --- HUARI
    (  150,'IE ELEAZAR GUZMAN BARRON','JR. NAZARENAS SN' ),											-- ANRA
    (  151,'IE MARIANO MELGAR VALDIVIESO','CALLE NUEVA SN' ),										-- CAJAY
    (  152,'IE 86349 REPUBLICA DE HONDURAS','JR. 17 DE ENERO NORTE SN' ),							-- CHAVIN DE HUANTAR
    (  153,'IE 86351','JR. TUPAC AMARU SN' ),														-- HUACACHI
    (  154,'IE FABIAN ORTEGA OLASCUAGA','JR. MAGISTERIAL SN' ),										-- HUACCHIS
    (  155,'IE 86354 SARITA COLONIA','JR. CONDORCANQUI SN' ),										-- HUACHIS
    (  155,'IE SAN CRISTOBAL','JR. LEONCIO PRADO SN' ),
    (  156,'IE 86360 HUANTAR','JR. MANCO CAPAC SN' ),												-- HUANTAR
    (  157,'IE 86323 VIRGEN DE FATIMA','AV. MAGISTERIAL 155' ),										-- HUARI
    (  157,'IE MANUEL GONZALES PRADA','AV. CIRCUNVALACION 452' ),	
    (  158,'IE 86363 JUAN N GANVINI BEZADA','AV. PROGRESO SN' ),									-- MASIN
    (  159,'IE 86365 PEDRO PAULET MOSTAJO','CALLE MAGISTRAL SN' ),									-- PAUCAS
    (  160,'IE HORACIO ZEBALLOS GAMEZ','AV. JOSE OLAYA SN' ),										-- PONTO
    (  161,'IE MANUEL SEOANE CORRALES','AV. EL COMERCIO SN' ),										-- RAHUAPAMPA
    (  162,'IE 86372 JAVIER CHERO BETETA','JR. GUADALUPE SN' ),										-- RAPAYAN
    (  163,'IE PACHACUTEC','JR. FRANCISCO BOLOGNESI SN' ),											-- SAN MARCOS
    (  163,'IST SAN MARCOS','JR. RAMON CASTILLA 1219' ),
    (  164,'IE AGROPECUARIA SANTA CRUZ DE PICHIU','CARRETERA PRINCIPAL A HUANCAYO' ),				-- SAN PEDRO DE CHANA
    (  164,'IE ELEAZAR GUZMAN BARRON','JR. SIMON BOLIVAR SN' ),
    (  165,'IE GORGONIO HUAMAN OSORIO','JR. SALVERRY SN' ),    										-- UCO

-- ---- ANCASH --- HUARMEY    	
    (  166,'IE 86158 SAN SANTIAGO','JR. BOLIVAR' ),													-- COCHAPETI
    (  166,'IE 88256','CARRETERA A MARAVIA Y SAN ISIDRO' ),
    (  167,'IE 88109 ALFONSO UGARTE','AV. CELESTINO ZAPATA' ),										-- CULEBRAS
    (  168,'IE 88106 JOSE CARLOS MARIATEGUI','MARISCAL CASTILLA 117' ),								-- HUARMEY
    (  168,'IE INCA GARCILAZO DE LA VEGA','JR. GRAU 401' ),
    (  168,'IE VIRGEN DE FATIMA','JR. LOS ANDES 245' ),								
    (  169,'IE 86156 VIRGEN INMACULADA CONCEPCION - PRIMARIA','CALLE TACNA' ),						-- HUAYAN
    (  169,'IE 86157 CESAR VALLEJO PRIMARIA','AV. CESAR VALLEJO' ),
    (  170,'IE 86141 SAN JUAN DE MALVAS NUEVO LOCAL','IE 86141 SAN JUAN DE MALVAS NUEVO LOCAL' ),	-- MALVAS
    (  170,'IE 86146 SABIO SANTIAGO ANTUNEZ DE MAYOLO','PLAZA DE ARMAS' ),

-- ---- ANCASH --- HUAYLAS
    (  171,'IE 86473 MICELINO SANDOVAL TORRES','JR. RAYMONDI 161' ),								-- CARAZ
    (  171,'IE 86519 OSCAR COLCHADO LUCIO','CASERIO DE PAKIAN' ),
    (  171,'IE 86523 SAN MIGUEL ARCANGEL','CARRETERA CENTRAL' ),
    (  172,'IE 86507 SANTA ROSA DE LIMA','CALLE 14 DE ABRIL' ),										-- HUALLANCA
    (  173,'IE 86499 LUIS TORRES SALAZAR','AV. SEÑOR DE LOS MILAGROS' ),							-- HUATA
    (  174,'IE 86484 EMILIANO HARO COLLAS','JR. CUSCO 640' ),										-- HUAYLAS
    (  175,'IE 86492 JOSE STRAUSSBERGER','JR. AUGUSTO B LEGUIA' ),									-- MATO
    (  176,'IE 86502 SAN SANTIAGO','AV. PERU' ),													-- PAMPAROMAS
    (  176,'IE 86504 ANDRES PASCUAL','CARRETERA CENTRAL A CHUNGA' ),
    (  176,'IE 88301 JESUS DE NAZARETH','AV. MIRAMAR' ),
    (  177,'IE 86495 SAN JUAN BAUTISTA','AV. 03 LT 01 MZ F' ),										-- PUEBLO LIBRE
    (  177,'IE 86496 JOSE GALVEZ','JR. LOS PINOS' ),
    (  178,'IE 86506 AMADEO GADEA LANDAVERY','JR. HILDEBRANDO CASTRO' ),							-- SANTA CRUZ
    (  179,'IE 86486 VICTOR FLORES CORTEZ','AV. EL TRIUNFO' ),										-- SANTO TORIBIO
    (  180,'IE 86501 ANDRES AVELINO CACERES','JR. 28 DE JULIO' ),									-- YURACMARCA
    (  180,'IE 86543 MARIANO MELGAR','BARRIO LOCAL' ),

-- ---- ANCASH --- MARISCAL LUZURIAGA    	   
    (  181,'IE 84115 ARMANDO VALVERDE CALDASC','JR. SAN ANTONIO DE PADUA SN' ),						-- CASCA
    (  182,'IE ELEODORO VEGA OCAÑA','AV. PROGRESO SN' ),											-- ELEAZAR GUZMAN BARRON
    (  183,'IE 84118','JR. LOS SAUCES SN' ),														-- FIDEL OLIVAS ESCUDERO
    (  184,'IE 84123 CORONEL FELIX MARTINIANO ROCA LOPEZ','AV. FIDEL OLIVAS ESCUDERO SN' ),			-- LLAMA
    (  185,'IE 84127 JOSE CARLOS MARIATEGUI','PLAZA DE ARMAS DE YURMA SN' ),						-- LLUMPA
    (  185,'IE ANDRES AVELINO CACERES','JR. CENTENARIO SN' ),
    (  186,'IE 84121 VIRGEN DE GUADALUPE','BARRIO CABEZA' ),										-- LUCMA
    (  186,'IE JOSE ANTONIO ENCINAS FRANCO','CCPP SECCHA' ),
    (  187,'IE 84128 VIRGEN DEL ROSARIO - PRIMARIA','JR. PACHACUTEC' ),								-- MUSGA
    (  188,'IE 84025 CESAR EGUZQUIZA DURAND PRIMARIA','ROMERO PAMPA SN' ),							-- PISCOBAMBA

-- ---- ANCASH --- OCROS    	   
    (  189,'IE 20473','CALLE LOS MAESTROS' ),														-- ACAS
    (  190,'IE 86222 CAJAMARQUILLA','JR. HUARIPAMPA' ),												-- CAJAMARQUILLA
    (  191,'IE 20481','CAMPO NARANJAL' ),															-- CARHUAPAMPA
    (  192,'IE 20486 SAN JUAN DE COCHAS','CALLE 30 DE AGOSTO' ),									-- COCHAS
    (  192,'IE 20488 GENARO ABARCA RAMIREZ','JR. SAN MARTIN' ),
    (  193,'IE 20490 SAN SALVADOR','JR. MANUEL PRADO' ),											-- CONGAS
    (  194,'IE 20496 VIRGEN DEL CARMEN','AV. NUEVO PROGRESO' ),										-- LLIPA
    (  195,'IE 20498 VIRGEN DEL ROSARIO','JR. ATAHUALPA' ),											-- OCROS
    (  196,'IE 20508 SAN CRISTOBAL - RAJAN','JR. SANTA CRUZ' ),										-- SAN CRISTOBAL DE RAJAN
    (  197,'IE 20513 SAN PEDRO','JR. MARISCAL CASTILLA' ),											-- SAN PEDRO
    (  198,'IEI 1211 CHILCAS','JR. LEONCIO PRADO' ),												-- SANTIAGO DE CHILCAS

-- ---- ANCASH --- PALLASCA
    (  199,'IE 88160 ANTIGUO LOCAL','JR. JOSE DE SAN MARTIN 450' ),									-- BOLOGNESI
    (  200,'IE 88154 CABANA','JR. LOS ESTUDIANTES 117' ),											-- CABANA
    (  201,'IE 88187','CCPP CHALAN' ),																-- CONCHUCOS
    (  201,'IE 88188 PRIMARIA','AV. APOSTOL SANTIAGO' ),
    (  201,'IE 88190 VICTOR RAUL HAYA DE LA TORRE','AV. ESPAÑA' ),
    (  201,'IE CONCHUCOS','JR. LAVANDA' ),
    (  202,'IE 88163 NUEVO LOCAL','BARRIO SHIMPAMPA' ),												-- HUACASCHUQUE
    (  203,'IE 88159 HECTOR HEREDIA ROSALES','JR. ARCO 700' ),										-- HUANDOVAL
    (  204,'IE 88161 SANTIAGO ANTUNEZ DE MAYOLO','JR. ALFONSO UGARTE' ),							-- LACABAMBA
    (  205,'IE 88152 SAN MARCOS','JR. SAN PEDRO' ),													-- LLAPO
    (  206,'IE 88155 SAN JUAN BAUTISTA','JR. SAN MARTIN 396' ),										-- PALLASCA
    (  207,'IE 88186','CALLE TUPAC AMARU' ),														-- PAMPAS
    (  207,'IE 88191','EL NARANJO' ),
    (  207,'IE 88358 LA CANTUTA','AV. LA CANTUTA 350' ),
    (  208,'IE 88162 SANTA ROSA','JR. MARISCAL SUCRE' ),											-- SANTA ROSA
    (  209,'IE SANTO DOMINGO DE GUZMAN','JR. BOLOGNESI 100' ),										-- TAUCA

-- ---- ANCASH --- POMOBAMBA
    (  210,'IE 84014 ATOJPAMPA','PSJ. ATOJPAMPA SN' ),												-- HUAYLLAN
    (  211,'IE 84019 ALFONSO PONTE GONZALES','PSJ. QUINUARAJRA SN' ),								-- PAROBAMBA
    (  211,'IE 84022 APOSTOL SANTIAGO','JR. POMABAMBA SN' ),
    (  211,'IE 84024 JUAN ALVARADO VILLACHICA CORDOVA','AV. TUPAC AMARU SN' ),
    (  211,'IE 84234 DE CHANGA','CCPP SANTA CRUZ DE CHANGA' ),
    (  212,'IE 84001 ROSENDA SANCHEZ','JR. TENIENTE CORONEL MELGAREJO SN' ),						-- POMABAMBA
    (  212,'IE 84012 EUGENIO MORENO ALVAREZ','CCPP CONOPA' ),
    (  212,'IE MONS FIDEL OLIVAS ESCUDERO - ANTIGUO LOCAL','JR. LUIS NEGREIROS 360' ),
    (  213,'IE HORACIO GONZALES ESCUDERO','JR. TRINIDAD MANCISIDOR SN' ),							-- QUINUABAMBA

-- ---- ANCASH --- RECUAY
    (  214,'IE CESAR VALLEJO MENDOZA','AV. SUECIA 921' ),											-- CATAC
    (  215,'IE 86574 SAN PABLO','CALLE CURMERON' ),													-- COTAPARACO
    (  216,'IE 86573 SAN GREGORIO DE HUAYLLAPAMPA','JR. SAN GREGORIO' ),							-- HUAYLLAPAMPA
    (  217,'IE 86580 EDUARDO AUGUSTO BUSTAMANTE ALVARADO','CALLE MIGUEL GRAU' ),					-- LLACLLIN
    (  217,'IE SAN PEDRO DE LLACCLIN','JR. 28 DE JULIO' ),
    (  218,'IE 86572','AV. 28 DE JULIO' ),															-- MARCA
    (  218,'IE SAN LORENZO DE MARCA','AV. SALAVERRY' ),
    (  219,'IE 86575 VIRGEN DE FATIMA','JR. TAHUANTINSUYO' ),										-- PAMPAS CHICO
    (  219,'IE 86612 SEÑOR DE LOS MILAGROS','AV. SEÑOR DE LOS MILAGROS' ),
    (  220,'IE 86566 JULIO C TELLO','JR. PACIFICO' ),												-- PARARIN
    (  221,'IE 86562 MANUEL SCORZA TORRES','AV. OLIMPICO' ),										-- RECUAY
    (  221,'IE JAVIER HERAUD PEREZ 86560','JR. RAYO' ),
    (  222,'IE 86579 VIRGEN DEL ROSARIO','PRLG DOS DE MAYO' ),										-- TAPACOCHA
    (  223,'IE 86569 SANTIAGO ANTUNEZ DE MAYOLO','AV. CAMINO REAL 1020' ),							-- TICAPAMPA
    (  223,'IE CEBA NUESTRA SEÑORA DEL PILAR','AV. PRIMAVERA 300' ),

-- ---- ANCASH --- SANTA
    (  224,'IE 88050','JR. ALFONSO UGARTE 251' ),													-- CACERES DEL PERU
    (  225,'CEBE CENTRO DE EDUCION BASICA ALTERNATIVA','JR. SAENZ PEÑA 760' ),						-- CHIMBOTE
    (  225,'IE 16 FE Y ALEGRIA','CALLE CARMELITAS' ),
    (  225,'IE 302 RUSO','AV. PARDO 941' ),
    (  225,'IE 329 GLORIOSA','JR. LEONCIO PRADO 227' ),
    (  225,'IE 88001 EX 314','JR. LEONCIO PRADO' ),
    (  225,'IE 88005 CORAZON DE JESUS','AV. FRANCISCO BOLOGNESI 930' ),
    (  225,'IE 88009 ENRIQUE MEIGGSS','AV. MEIGGS 2274' ),
    (  225,'IE 88013 ELEAZAR GUZMAN BARRON','JR. 28 DE JULIO' ),
    (  225,'IE 88014 JOSE OLAYA','JR. AMAZONAS' ),
    (  225,'IE 88023 ALMIRANTE MIGUEL GRAU SEMINARIO','PRLG LEONCIO PRADO' ),
    (  225,'IE 88031 REPUBLICA PERUANA','URB. LAS LADERAS DEL NORTE' ),
    (  225,'IE 88034 PEDRO RUIZ GALLO','AV. LOS INCAS' ),
    (  225,'IE 88037 ANTENOR SANCHEZ','AV. BUENOS AIRES' ),
    (  225,'IE 89001 EX PREVOCACIONAL','JR. LADISLAO ESPINAR 235' ),
    (  225,'IE 89004 MANUEL GONZALES PRADA','PRLG ALFONS UGARTE' ),
    (  225,'IE 89007','URB 21 DE ABRIL' ),
    (  225,'IE 89011 ELIAS AGUIRRE ROMERO','PRLG 21 DE ABRIL' ),
    (  225,'IE ERASMO ROCA','AV. JOSE PARDO' ),
    (  225,'IE INMACULADA DE LA MERCED','CALLE FERROCARRIL' ),
    (  225,'IE POLITECNICO NACIONAL DEL SANTA','AV. ENRIQUE MEIGGS 680' ),
    (  225,'IE SAN PEDRO','JR. CASMA' ),
    (  225,'IE SANTA MARIA REYNA','ZONA A MZ 16 LTE C2' ),
    (  225,'UNIVERSIDAD SAN PEDRO','JR. WIRACOCHA' ),
    (  226,'IE 88025 RAMON CASTILLA','JR. ANCASH' ),												-- COISHCO
    (  226,'IE 88044','AV. SANTA MARINA 200' ),
    (  227,'IE 88048','AV. VICTOR RAUL HAYA DE LA TORRE' ),											-- MACATE
    (  227,'IE 88054 SANTO TORIBIO','JR. SAN MARTIN 250' ),
    (  227,'IE 88062','CALLE CAMINO REAL' ),
    (  227,'IE 88241 SANTA ROSA DE PAQUIRCA','AV. VICTORIA ESPINOZA' ),
    (  228,'IE SANTO DOMINGO','JR. ESTUDIANTES 250' ),												-- MORO
    (  229,'IE MARCOS EVARISTO VILLACRE','CALLE TERESA GONZALES DE FANNING' ),						-- NEPEÑA
    (  229,'IE SAN JACINTO','CALLE HORACIO ZEVALLOS' ),
    (  230,'IE 88017 CESAR VALLEJO MENDOZA','AV. PANAMERICANA SUR 	' ),							-- NUEVO CHIMBOTE
    (  230,'IE 88021 ALFONSO UGARTE','URB BRUCES' ),
    (  230,'IE 88047 SALAZAR BONDY','AV. CHIMBOTE' ),
    (  230,'IE 88061 JOSE ABELARDO QUIÑONEZ','MZ V LT 5 5 SEGUNDA ETAPA' ),
    (  230,'IE 88227 PEDRO PABLO ATUSPARIA','AV. LOS ALCATRACES S/N' ),
    (  230,'IE 88298','DAVIS DASSO' ),
    (  230,'IE 88336 GASTON VIDAL PORTURAS','AV. BRASILIA' ),
    (  230,'IE 88389 JUAN VALER SANDOVAL','URB NICOLAS GARATEA' ),
    (  230,'IE REPUBLICA FEDERAL SOCIALISTA DE YUGOSLAVIA','AV. CENTRAL' ),
    (  230,'IE SEÑOR DE LA VIDA','AV. LAS CASUARINAS' ),
    (  230,'IE VILLA MARIA','JR. INDEPENDENCIA' ),
    (  230,'IST CARLOS SALAZAR ROMERO','AV. PACIFICO SN' ),
    (  231,'IE RAMON CASTILLA','JR. ALFONSO UGARTE 201' ),											-- SAMANCO
    (  232,'IE 88039 JAVIER HERAUD','AV. 09 DE OCTUBRE' ),											-- SANTA
    (  232,'IE 88320 SAN BARTOLO','CALLE ATAHUALPA' ),
    (  232,'IE SANTIAGO ANTUNEZ DE MAYOLO','JR. MARAÑON 245' ),

-- ---- ANCASH --- SIHUAS
    (  233,'IE 84172','JR. 30 DE OCTUBRE SN' ),														-- ACOBAMBA
    (  234,'IE ALFONSO UGARTE','JR. TORIBIO LISTER GUERRA SN' ),									-- ALFONSO UGARTE
    (  235,'IE 84176 VIRGEN DEL ROSARIO ANTIGUO LOCAL','JR. PROGRESO SN' ),							-- CASHAPAMPA
    (  235,'IE JOSE MARIA EGUREN','CCPP PASACANCHA' ),
    (  236,'IE 84178 EL AMAUTA','JR. PEDRO CORTEZ MONROY SN' ),										-- CHINGALPO
    (  237,'IE 84180 GASTON VIDAL PORTURAS','AV. 28 DE JULIO SN' ),									-- HUAYLLABAMBA
    (  237,'IE SANTIAGO ANTUNEZ DE MAYOLO','CCPP SANTA CLARA' ),
    (  238,'IE VIRGEN DE LA NATIVIDAD','JR. RAYMONDI SN' ),											-- QUICHES
    (  239,'IE 84185 SANTA CRUZ','JR. SIMON BOLIVAR SN' ),											-- SIHUAS
    (  240,'IE 84189 HORACIO ZEBALLOS GAMES SECUNDARIA','AV. CAMINO REAL SN' ),						-- SAN JUAN
    (  240,'IE 84189 HORACIO ZEBALLOS GAMES PRIMARIA','AV. CAMINO REAL SN' ),
    (  240,'IE 84228 JOSE ANTONIO ENCINAS','AV. 14 DE OCTUBRE SN' ),
    (  241,'IE SAN MARCOS','AV. SANTO TORIBIO SN' ),												-- SICSIBAMBA
    (  242,'IE CAPITAN MARCELINO VALVERDE SOLORZANO','JR. JUAN VELAZCO ALVARADO 230' ),				-- SIHUAS

-- ---- ANCASH --- YUNGAY
    (  243,'IE 86668','CCPP ANCHIN' ),																-- CASCAPARA
    (  243,'IE SANTO TORIBIO','CARRETERA CIRCUNVALACIÓN' ),
    (  244,'IE 86633 ANTONIO RAYMONDI','JR. ATUSPARIAS' ),											-- MANCOS
    (  244,'IE JOSE CARLOS MARIATEGUI','CARRETERA MANCOS HUAYPAN' ),
    (  244,'IEP 86630 VIRGEN DEL ROSARIO - HUAYPAN','CALLE PRINCIPAL' ),
    (  244,'IEP SAN ROQUE','JR. AMARGURA' ),
    (  245,'IE 86644 SAN MARTIN DE PORRAS','PLAZA DE ARMAS DE MATACOTO' ),							-- MATACOTO
    (  246,'IE 86645 RICARDO PALMA','CALLE CONVENTO 179' ),											-- QUILLO
    (  246,'IE 86677 SANTIAGO ANTUNEZ DE MAYOLO','AV. YUNGAY' ),	
    (  246,'IE 86748 JORGE BASADRE GROHMAN','CARRETERA CENTRAL PARTE BAJA' ),
    (  246,'IEP 86672 SAN ROQUE','CALLE CORACOLLO' ),
    (  247,'IE 86640 SEÑOR DE LOS MILAGROS','JR. LAS PALMERAS' ),									-- RANRAHIRCA
    (  248,'IE 86646 ISABEL ROMERO SOTELO','AV. GARCILAZO DE LA VEGA' ),							-- SHUPLUY
    (  248,'IE 86679 PRIMORPAMPA','CARRETERA CIRCUNVALACIÓN' ),
    (  249,'IE LA INMACULADA DE CUNYA','CCPP CUNYA' ),												-- YANAMA
    (  249,'IE SAN JUAN BOSCO','JR. LOS EDUCADORES' ),
    (  250,'IE 86620 SANTA FE PRIMARIA','AV. SAN MARTIN' ),											-- YUNGAY
    (  250,'IE 86751 SAN PEDRO','CARRETERA LLANGANUCO' ),
    (  250,'IE SANTA INES - PRIMARIA','AV. ARIAS GRAZIANI' ),
    (  250,'IE SANTA INES - SECUNDARIA','AV. ARIAS GRAZIANI' ),
    (  250,'IEP CESAR VALLEJO','CARRETERA LLANGANUCO KM 14' ),
    (  250,'IEP MARTIR JOSE OLAYA','CALLE ALFONSO UGARTE' )