use Onpe;
insert LocalVotacion(idDistrito, RazonSocial, Direccion) values

-- ---- APURIMAC --- ABANCAY
     (  251, 'IE 54002 SANTA ROSA', 'AV. GARCILAZO N° 420' ),										-- ABANCAY
	 (  251, 'IE 55001 MANUEL JESUS SIERRA AGUILAR- MAJESA', 'R. ARICA SN' ),
	 (  251, 'IE 55002 AURORA INES TEJADA', 'JR. AREQUIPA N° 108' ),
	 (  251, 'IE EMBLEMATICO MIGUEL GRAU', 'AV. SEOANE N° 507' ),
	 (  251, 'IE LA SALLE ABANCAY', 'AV. DANIEL ALCIDES CARRION SN' ),
	 (  251, 'IE MANUEL JESUS SIERRA AGUILAR-MAJESA', 'JR. APURIMAC SN' ),
	 (  251, 'UNIVERSIDAD TECNOLOGICA DE LOS ANDES', 'PSJ. LOS LIRIOS SN' ),
	 (  252, 'IE 54027', 'CALLE LIMA SN' ),															-- CHACOCHE
	 (  252, 'IE 54059 CASINCHIHUA', 'AV. ALAMEDA ESTUDIANTIL SN' ),
	 (  253, 'IE JOSE CARLOS MARIATEGUI', 'CAMINO DE HERRADURA SN' ),								-- CIRCA
	 (  253, 'IE VARIANTE AGROPECUARIO OCOBAMBA', 'CARRETERA OCOBAMBA SN' ),
	 (  253, 'LUIS FERNANDO BUENO QUINO', 'CALLE NUEVA SN' ),
	 (  254, 'IE 54019 CCOLLPA', 'PLAZA DE ARMAS' ),												-- CURAHUASI
	 (  254, 'IE 55004 VIRGEN DE FATIMA', 'CALLE ABANCAY N° 100' ),
	 (  254, 'IE ANTILLA MARIO VARGAS LLOSA', 'ASCO MARCA SN' ),
	 (  254, 'IE ANTONIO OCAMPO', 'JR. ANTONIO OCAMPO SN' ),
	 (  254, 'IE INMACULADA', 'PRLG AUGUSTO B. LEGUIA SN' ),
	 (  255, 'IE 54030 VIRGEN DEL CARMEN', 'JR. BOLOGNESI SN' ),									-- HUANIPACA
	 (  256, 'IE 54028 VIRGEN DE FATIMA', 'PSJ. DEL ESTUDIANTE' ),									-- LAMBRAMA
	 (  256, 'IE 54512 SUNCHO', 'PLAZA DE ARMAS' ),
	 (  256, 'IE GUILLERMO VILLADEGUT', 'PSJ. DEL ESTUDIANTE SN' ),
	 (  257, 'IE 54031 VIRGEN NATIVIDAD', 'PLAZA DE ARMAS' ),										-- PICHIRHUA
	 (  257, 'IE 54034 VIRGEN MARIA', 'BARRIO MOLLEBAMBA' ),
	 (  257, 'IE 54702 ACCOPAMPA COTARMA', 'AV. SAN FRANCISCO SN' ),
	 (  257, 'IE SAN FRANCISCO - SECUNDARIA', 'CARRETERA LUCUCHANGA' ),
	 (  258, 'IE 54013 VIRGEN DEL CARMEN', 'JR. SAN MARTIN' ),										-- SAN PEDRO DE CACHORA
	 (  259, 'IE 54036 SEÑOR DE LA EXALTACION', 'AV. TUPAC AMARU 129' ),							-- TAMBURCO
	 (  259, 'IE MICAELA BASTIDAS PUYUCAHUA', 'AV. CORONEL GONZALES' ),

-- ---- APURIMAC --- ANDAHUAYLAS
     (  260, 'IE 55005 DIVINO MAESTRO', 'AV. MARTINELLY 651' ),										-- ANDAHUAYLAS
     (  260, 'IE 55006', 'AV. JOSE MARIA ARQUEDAS' ),
	 (  260, 'IE BELEN DE OSMA Y PARDO', 'AV. PERU 710' ),
	 (  260, 'IE JUAN ESPINOZA MEDRANO', 'AV. PERU 565' ),
	 (  261, 'IE 54082', 'JR. 24 DE JUNIO' ),														-- ANDARAPA
	 (  261, 'IE SAN FRANCISCO DE ASIS', 'JR. 24 DE JUNIO 150' ),
	 (  262, 'IE 13 VILLA CHIARA', 'CERCADO' ),														-- CHIARA
	 (  263, 'IE 54085', 'JR. AREQUIPA' ),															-- HUANCARAMA
	 (  263, 'IE MARIA PARADO DE BELLIDO', 'AV. BOLIVAR' ),
	 (  264, 'IE 2 DE MAYO', 'JR. PORVENIR' ),														-- HUANCARAY
	 (  265, 'IE 54108', 'JR. ALAMEDA' ),															-- HUAYANA
	 (  266, 'IE 54080', 'AV. ICA' ),																-- JOSE MARIA AGUEDAS
	 (  267, 'IE 54098', 'AV. OSCAR DARIO MONTES SN' ),												-- KAQUIABAMBA
	 (  268, 'DIVINO MAESTRO', 'AV. JHANS DUDA' ),													-- KISHUARA
	 (  268, 'IE 54101', 'AV. LIMA' ),
	 (  268, 'IE 54539 SAN CARLOS II', 'AV. CULTURA' ),
	 (  268, 'IE JOSE MARIA ARGUEDAS', 'AV. ESTUDIANTES' ),
	 (  269, 'IE 54092 SAN JUAN BAUTISTA LA SALLE', 'AV. SIMON BOLIVAR 117' ),						-- PACBAMBA
	 (  270, 'IE 54095 BRISAS DE PACUCHA', 'AV. PASEO DE LA REPUBLICA' ),							-- PACUCHA
	 (  270, 'IE JOSE OLAYA BALANDRA', 'AV. PASEO DE LA REPUBLICA' ),
	 (  271, 'IE 54099 VIRGEN DEL CARMEN', 'AV. ALAMEDA' ),											-- PAMPACHIRI
	 (  272, 'IE 54100', 'AV. MANUEL ROMERO BLANCO' ),												-- POMACOCHA
	 (  273, 'IE 54207', 'JR. MAURO QUISPE' ),														-- SAN ANTONIO DE CACHI
	 (  273, 'IE 54208', 'CCPP CHULLISANA' ),	
	 (  274, 'IE 54104 CRISTO REY', 'JR. ARICA 146' ),												-- SAN JERONIMO
	 (  274, 'IE 54105 JUAN PABLO II', 'JR. BOLOGNESI 117' ),	
	 (  274, 'IE 8 AGROPECUARIO', 'JR. ALFONSO UGARTE 700' ),
	 (  274, 'IE SAN MARTIN DE PORRES DE ANCATIRA', 'CCPP ANCATIRA' ),
	 (  275, 'IE 54192', 'AV. CANADA' ),															-- SAN MIGUEL DE CHACCRAMPA
	 (  276,  'IE 54210 NUESTRA SEÑORA DE FATIMA', 'JR. TUPAC AMARU' ),								-- SANTA MARIA DE CHICMO
	 (  276, 'IE 54213 VIRGEN DEL CARMEN', 'CASCABAMBA' ), 
	 (  276, 'IE GUILLERMO PINTO ISMODES', 'JR. TUPAC AMARU' ),
	 (  277, 'IE 54177 BUEN PASTOR', 'JR. LIMA 242' ),												-- TALAVERA
	 (  277, 'IE 54178 SAGRADO CORAZON DE JESUS', 'JR. APURIMAC 380' ),	
	 (  277, 'IE GREGORIO MARTINELLI', 'AV. HUALALACHI 134' ),
	 (  278, 'IE 54107', 'JR. BOLIVAR' ),															-- TUMAY HUARACA
	 (  278, 'IE JOSE GALVEZ EGUSQUIZA', 'AV. LUCANAS' ),
	 (  279, 'IE 54109 VIRGEN DEL CARMEN', 'AV. VICTOR AREVALO' ),									-- TURPO
	 (  279, 'IE JUAN ANTONIO LIGARDA PINEDO', 'AV LIGARDA'),	
	  
-- ---- APURIMAC --- ANTABAMBA
	 (  280, 'IE 54253 ESCUELA BARRIO ALTO', 'BARRIO ALTO' ),										-- ANTABAMBA
	 (  281, 'IE 54258 JUAN ESPINOZA MEDRANO', 'CALLE 28 DE JULIO' ),								-- EL ORO
	 (  282, 'IE 55008 ANTONIO CENTENO ZELA', 'PRLG TRIUNFO CACERES' ),								-- HUAQUIRCA
	 (  283, 'IE JOSE MARIA ARGUEDAS MOLLEBAMBA', 'PLAZA DE ARMAS' ),								-- JUAN ESPIPNOZA MEDRANO
	 (  284, 'IE 54271', 'AV. SAN MARTIN' ),														-- OROPESA
	 (  285, 'IE 54266 JOSE MARIA ARGUEDAS', 'CALLE PROGRESO' ),									-- PACHACONAS
	 (  286, 'IE CESAR ABRAHAM VALLEJO MENDOZA', 'PROLONGACION MUNICIPAL SN' ),						-- SABAINO

-- ---- APURIMAC --- AYMARAES
	 (  287, 'IE 54304 VIRGEN DE CARMEN', 'JR. APURUCCO' ),											-- CAPAYA
	 (  288, 'IE 54306 NUESTRA SEÑORA DE FÁTIMA', 'PLAZA DE ARMAS' ),								-- CARAYBAMBA
	 (  289, 'IE LIBERTADORES DE AMERICA', 'AV. PANAMERICANA SN' ),									-- CHALHUANCA
	 (  290, 'IE SANTA CATALINA DE CHAPIMARCA', 'BARRIO SAYOPAMPA' ),								-- CHAPIMARCA
	 (  291, 'IE 54308 SAN PEDRO DE COLCABAMBA', 'JR. COMERCIO' ),									-- COLCABAMBA
	 (  292, 'IE JOSE MARIA ARGUEDAS', 'JR. SAN MARTIN' ),											-- COTARUSE
	 (  292, 'IE MIGUEL GRAU SEMINARIO DE TOTORA', 'CCPP TOTORA' ),
	 (  293, 'IE 54316 INMACULADA CONCEPCION', 'JOSE GABRIEL AYVAR' ),								-- HUAYLLO
	 (  294, 'IE 54380 SAN MIGUEL DE PICHIGUA', 'PLAZA DE ARMAS' ),									-- JUSTO APU SAHUARAURA
	 (  295, 'IE 54318 VIRGEN DE LAS NIEVES', 'JR. APURIMAC' ),										-- LUCRE
	 (  296, 'IE 54319 PATRON SAN FELIPE', 'PLAZA DE ARMAS' ),										-- POCOHUANCA
	 (  297, 'IE 54311 VIRGEN DEL CARMEN', 'AV. LOS INCAS' ),										-- SAN JUAN DE CHACÑA
	 (  298, 'IE 54321 LOS ANGELES DE SAN FRANCISCO', 'PLAZA DE ARMAS' ),							-- SAÑAYCA
	 (  299, 'IE 54323 SAN ANTONIO DE PADUA', 'PLAZA DE ARMAS' ),									-- SORAYA
	 (  300, 'IE 54325', 'JR. GALEANO' ),															-- TAPAIRIHUA
	 (  301, 'IE 54326 HORACIO ZEVALLOS', 'AV. INSTITUCIONAL' ),									-- TINTAY
	 (  301, 'IE DAVID SAMANEZ OCAMPO', 'CALLE AYMARAES' ),
	 (  301, 'IE FRANCISCO BOLOGNESI CERVANTES', 'CARRETERA PRINCIPAL DE SANMATEO' ),
	 (  302, 'IE 54330 RICARDO PALMA TORAYA', 'PLAZA DE ARMAS' ),									-- TORAYA
	 (  303, 'IE TUPAC AMARU II', 'PLAZA DE ARMAS' ),												-- YANACA

-- ---- APURIMAC --- CHINCHEROS
	 (  304, 'IE JOSE MARIA ARGUEDAS', 'AV. LA CULTURA' ),											-- ANCO HUALLO
	 (  304, 'IE MIGUEL GRAU SEMINARIO', 'AV. ANDAHUAYLAS' ),
	 (  305, 'IE SM TUPAC AMARU', 'AV. TUPAC AMARU' ),												-- CHINCHEROS
	 (  306, 'IE 54187 VIRGEN DE COCHARCAS', 'JR. CATEDRAL COCHARCAS' ),								-- COCHARCAS
	 (  307, 'IE 54454', 'AV. PRIMAVERA' ),															-- HUACCANA
	 (  307, 'IE CIRO ALEGRIA', 'AV. JUAN VELASCO ALVARADO' ),
	 (  307, 'IE JOSE MARIA FLORES', 'JR. JOSE CARLOS MARIATEGUI' ),
	 (  308, 'IE 54196 CESAR BENIGNO FLORES FALCONI', 'AV. ZONA DE TARAPATA OCOBAMBA' ),			-- OCOBAMBA
	 (  308, 'IE 54242', 'JUAN VELASCO ALVARADO' ),
	 (  309, 'IE 54205', 'CALLE LA JUVENTUD' ),														-- ONGOY
	 (  309, 'IE 54506 SAN JUAN BAUTISTA', 'AV. 11 DE JUNIO' ),
	 (  309, 'IE LUIS ALBERTO SANCHEZ', 'AV. ANDAHUAYLAS' ),
	 (  310, 'IE 54198 VIRGEN INMACULADA CONCEPCION RANRACANCHA', 'AV. CONCEPCION' ),				-- RANRACANCHA
	 (  311, 'IE 54188', 'AV. ANDAHUA- TRECE DE NOVIEMBRE' ),										-- URANMARCA
	 (  311, 'IE 54189', 'AV. LOS CHANCAS' ),

-- ---- APURIMAC --- COTABAMBAS
	 (  312, 'IEP 50633', 'MOLINOPAMPA' ),															-- CHALLHUAHUACHO
	 (  313, 'IE 50637 SAN MARTIN DE PORRES', 'BARRIO LITAMPAMPA' ),								-- COTABAMBAS
	 (  313, 'IE 50639', 'CALLE COROCO' ),
	 (  314, 'IE 50693 ÑAHUINLLA', 'CCPP ÑAHUINLLA MOLINOPAMPA' ),									-- COYLLURQUI
	 (  314, 'IST COYLLURQUI', 'AV. JOSE CARLOS MARIATEGUI' ),
	 (  315, 'IE 50634 JOSE MARIA ARGUEDAS', 'ESTADIO LUNA' ),										-- HAQUIRA
	 (  315, 'IE 50677 VIRGEN DE LAS NIEVES', 'CCPP HUANCASCCA' ),
	 (  315, 'IE CESAR VALLEJO', 'AV. HUISTAC' ),
	 (  316, 'IE 50631 MARA', 'PROLONGACION CHUMBIVILCAS' ),										-- MARA
	 (  316, 'IE APUMARCA', 'BARRIO SANTANA' ),
	 (  317, 'ERASMO DELGADO VIVANCO', 'PLAZA DE ARMAS' ),											-- TAMBOBAMBA
	 (  317, 'IE 50629 CHACCARO', 'PLAZA DE ARMAS' ),
	 (  317, 'IE 50650 DE ASACASI', 'PLAZA DE ARMAS' ),
	 (  317, 'SAN FRANCISCO DE ASIS', 'PROLONGACION AMAUTA' ),
 
-- ---- APURIMAC --- GRAU
	 (  318, 'IE 54385 SEÑOR DE LA EXALTACION', 'CALLE AUGUSTO B LEGUIA SN' ),						-- CHUQUIBAMBILLA
	 (  318, 'IE JOSE MARIA ARGUEDAS', 'CALLE SANTA ELENA' ),
	 (  318, 'IST GREGORIO MENDEL', 'AV. RENZO MICHELI' ),	
	 (  319, 'IE 54409', 'AV. ESTUDIANTES' ),														-- CURASCO
	 (  320, 'IE SAN JUAN BAUTISTA', 'CARRETERA PUCURHUAY' ),										-- CURPAHUASI
	 (  320, 'IEI PUBLICA 24', 'CALLE N° 2' ),	
	 (  321, 'IE 54398 SEÑOR DE HUANCA', 'AV. ESTUDIANTES' ),										-- HUAILLATI
	 (  322, 'IE 54401 SAN LUIS GONZAGA MAMARA', 'AV. PANAMERICANA' ),								-- MAMARA
	 (  323, 'IE 54436 SEÑOR DE EXALTACION', 'CCPP PACCAYPATA' ),									-- MARISCA GAMARRA
	 (  323, 'IE AGUSTIN GAMARRA', 'MARISCAL GAMARRA - PALPACACHI' ),
	 (  324, 'IE 54408', 'SANTIAGO PATA' ),															-- MICAELA BASTIDAS
	 (  325, 'IE JUAN ESPINOZA MEDRANO', 'AV. CENTENARIO' ),										-- PATAYPAMA
	 (  326, 'IE 54413 SAN JOSE', 'AV. EDUCACION' ),												-- PROGRESO
	 (  327, 'IE 54415', 'AV. VIRGEN DEL CARMEN' ),													-- SAN ANTONIO
	 (  328, 'IEP ANDRES AVELINO CACERES', 'CHOCCHO' ),												-- SANTA ROSA
	 (  329, 'IE 54416', 'ESTADIO MUNICIPAL' ),														-- TURPAY
	 (  330, 'IE JOSE ANTONIO ENCINAS FRANCO', 'BARRIO JUANPAMPA SN' ),								-- VILCABAMBA
	 (  331, 'IE 54417 SANTA ROSA', 'CALLE SANTA ROSA' )											-- VIRUNDO