use Onpe;
insert LocalVotacion(idDistrito, RazonSocial, Direccion) values

-- ---- AREQUIPA --- AREQUIPA
	(  332, 'IE 40003 ALTO SELVA ALEGRE', 'CALLE 13 DE ABRIL 513' ),								-- ALTO SELVA ALEGRE
	(  332, 'IE 40024 MANUEL GONZALES PRADA', 'AV. OBRERA 100' ),
	(  332, 'IE 40028 GUILLERMO MERCADO BARROSO', 'AV. HUARAZ Y ABANCAY SN' ),
	(  332, 'IE 40029 LUDWING VAN BEETHOVEN', 'AV. FRANCISCO MOSTAJO 900' ),
	(  332, 'IE 40034 MARIO VARGAS LLOSA', 'CALLE OSCAR NIEVES SN' ),
	(  332, 'IE 41035 NICANOR RIVERA CACERES', 'AV. LOS INCAS SN' ),
	(  332, 'IE SAN MARTIN DE PORRES - CIRCA', 'AV. ATLANTIDA 401' ),
	(  332, 'IE SANTA ROSA DE LIMA - CIRCA', 'CALLE PACIFICO Y AMAZONAS SN' ),
	(  332, 'IE SANTA ROSA DE LIMA - CIRCA NIVEL PRIMARIA', 'CALLE VILCANOTA 208' ),
	(  333, 'IE 41008 MANUEL MUÑOZ NAJAR', 'PSJ. FERNANDEZ DAVILA 107' ),							-- AREQUIPA
	(  333, 'IE AREQUIPA', 'CALLE LUCAS POBLETE 214' ),
	(  333, 'IE INDEPENDENCIA AMERICANA', 'AV. INDEPENDENCIA 1457' ),
	(  333, 'IE MICAELA BASTIDAS', 'CALLE MELGAR 307' ),
	(  333, 'IE SALESIANO DON BOSCO', 'CALLE SAN PEDRO 218' ),
	(  333, 'UNIVERSIDAD CATOLICA SANTA MARIA', 'CALLE SAMUEL VELARDE 320' ),
	(  333, 'UNIVERSIDAD NACIONAL SAN AGUSTIN', 'AV. VENEZUELA SN' ),
	(  334, 'IE 40045 LIVIA BERNAL DE BALTAZAR', 'AV. CAYMA 213' ),									-- CAYMA
	(  334, 'IE 40046 JOSE L CORNEJO ACOSTA', 'CALLE LIBERTAD SN' ),
	(  334, 'IE 40049 FRANCISCO BOLOGNESI', 'IE 40049 FRANCISCO BOLOGNESI' ),
	(  334, 'IE 40616 CASIMIRO CUADROS', 'AV. HEROES DEL CENEPA 350' ),
	(  334, 'IE LEON XIII - CIRCA', 'AV. CHACHANI SN' ),
	(  334, 'IE MAYTA CAPAC', 'AV. FRANCISCO BOLOGNESI SN' ),
	(  334, 'IST AREQUIPA', 'AV. RAMON CASTILLA 700' ),
	(  334, 'IST HONORIO DELGADO ESPINOZA', 'CALLE LOS ARCES 202' ),
	(  335, 'IE 40044 SAN MARTIN DE PORRAS', 'MZ Q LT 1 ZONA 2' ),									-- CERRO COLORADO
	(  335, 'IE 40054 JUAN DOMINGO ZAMACOLA Y JAUREGUI', 'CALLE JORGE CHAVEZ 401' ),
	(  335, 'IE 40055 ROMEO LUNA VICTORIA', 'CALLE YAPURA 306' ),
	(  335, 'IE 40056 HORACIO ZEBALLOS GAMES', 'CALLE 28 DE JULIO 118' ),
	(  335, 'IE 40058 IGNACIO ALVARES THOMAS', 'AV. ALFONSO UGARTE SN' ),
	(  335, 'IE 40061 ESTADO DE SUECIA', 'AV. CHACHANI SN' ),
	(  335, 'IE 40670 EL EDEN FE Y ALEGRIA SI', 'TIERRA PROMETIDA MZ I LOTE 1' ),
	(  335, 'IE 40677 SAN MIGUEL FEBRES CORDERO', 'AV. INDUSTRIAL (CALLE 8) SN' ),
	(  335, 'IE 41025 200 MILLAS PERUANAS LA LIBERTAD', 'CALLE 27 DE NOVIEMBRE 307' ),
	(  335, 'IE 41026 MARIA MURILLO DE BERNAL', 'CALLE MARIANO MELGAR 401' ),
	(  335, 'IE GRAN PACHACUTEC', 'AV. MANCO CAPAC SN' ),
	(  335, 'IE IGNACIO ALVARES THOMAS - SECUNDARIA', 'JR. JOSE OLAYA SN' ),
	(  335, 'IE JUAN DE LA CRUZ CALIENES', 'AV. CALIENES 101' ),
	(  335, 'IE LIBERTADORES DE AMERICA', 'AV. IQUITOS SN' ),
	(  335, 'IE NUESTRA SEÑORA DE LOS DOLORES', 'MIGUEL GRAU 301' ),
	(  335, 'IE SANTO THOMAS DE AQUINO - CIRCA', 'CALLE SAN MARTIN 214' ),
	(  336, 'IE 40123 SAN JUAN BAUTISTA', 'CALLE SANTA ROSA SN' ),									-- CHARACATO
	(  336, 'IE ANGEL FRANCISCO ALI GUILLEN', 'CALLE COLEGIO NACIONAL' ),
	(  337, 'IE 40127 SEÑOR DEL ESPIRITU SANTO', 'CALLE 27 DE OCTUBRE SN' ),						-- CHIGUATA
	(  338, 'IE 40033 SAN AGUSTIN DE HUNTER', 'URB A MZ F LOTE 1 UPIS PAISAJISTA' ),				-- JACOBO HUNTER
	(  338, 'IE 40043 NUESTRA SRA DE LA MEDALLA MILAGROSA', 'AVENIDA ITALIA CUADRA 3 SN' ),
	(  338, 'IE 40200 REPUBLICA FEDERAL DE ALEMANIA', 'CALLE ITALIA 700' ),
	(  338, 'IE 40206 SEÑOR DE LOS MILAGROS', 'CALLE SAN SALVADOR 401' ),
	(  338, 'IE 40207 MARIANO MELGAR VALDIVIESO', 'CALLE SANCHEZ CERRO 100' ),
	(  338, 'IE JACOBO DICKSON HUNTER', 'AV. ITALIA CDRA. 7' ),
	(  338, 'IE JUAN PABLO VIZCARDO Y GUZMAN', 'AV. VIÑA DEL MAR 1300' ),
	(  339, 'IE 41038 JOSE OLAYA BALANDRA', 'CALLE URUBAMBA 206' ),									-- JOSE LUIS BUSTAMANTE Y RIVERO
	(  339, 'IE GRAN LIBERTADOR SIMON BOLIVAR', 'AV. ULRICH NEISSER SN' ),
	(  339, 'IE INMACULADA CONCEPCION', 'PEDRO DIEZ CANSECO MZ I LOTE 11' ),
	(  339, 'IE JORGE BASADRE GROHMANN', 'CALLE SANGARARA N° 100' ),
	(  339, 'UNIVERSIDAD ALAS PERUANAS', 'URB. DANIEL ALCIDES CARRIÓN G-14' ),
	(  340, 'IE 40037 HUMBERTO LEON GARCIA', 'CALLE MIGUEL GRAU 201' ),								-- LA JOYA
	(  340, 'IE CARLOS W SUTTON', 'JR. 2 DE MAYO SN' ),
	(  341, 'GUE MARIANO MELGAR', 'AV. JESUS 513' ),												-- MARIANO MELGAR
	(  341, 'IE 40134 MANDIL AZUL', 'CALLE PARQUE BOLIVAR GENERALISIMO SAN MARTIN 103' ),
	(  341, 'IE 41030 EDUARDO LOPEZ DE ROMAÑA', 'AV. SIMON BOLIVAR 1201' ),
	(  341, 'IE ANDREA VALDIVIESO DE MELGAR', 'CALLE PIURA 600' ),
	(  341, 'IE MANUEL VERAMENDI E HIDALGO', 'CALLE COMANDANTE CANGA 2117' ),
	(  341, 'IE PIO XII', 'AV. BRASIL 325' ),
	(  342, 'IE 40144 AUGUSTO SALAZAR BONDY', 'AV. PRO HOGAR 1002' ),								-- MIRAFLORES
	(  342, 'IE 40148 GERARDO IQUIRA PIZARRO', 'AV. GOYENECHE 2900' ),
	(  342, 'IE 40151 CAP FAP JOSE QUIÑONES', 'CALLE MANUEL GONZALES PRADA 100' ),
	(  342, 'IE 40156 DE MUJERES', 'AV. SAN MARTIN 3000' ),
	(  342, 'IE 40157 JORGE LUIS BORGES', 'CALLE ARTURO VILLEGAS 115' ),
	(  342, 'IE 40158 EL GRAN AMAUTA', 'AV. SAN MARTIN 4403' ),
	(  342, 'IE 40159 EJERCITO AREQUIPA', 'AV. PROGRESO 1220' ),
	(  342, 'IE 41016 REPUBLICA DE ARGENTINA', 'CALLE ARICA 259' ),
	(  342, 'IE 41037 JOSE GALVEZ', 'CALLE JOSE GALVEZ 612' ),
	(  342, 'IE FRANCISCO JAVIER DE LUNA PIZARRO', 'AV. SAN MARTIN 2303' ),
	(  342, 'IE MISTI', 'AV. ALTO DE LA ALIANZA 226' ),
	(  343, 'IE 40160 OBDULIO BARRIGA VIZCARRA', 'CALLE UNION S/N' ),								-- MOLLEBAYA
	(  344, 'IE 40010 JULIO C TELLO', 'AV. REVOLUCION 1100' ),										-- PAUCARPATA
	(  344, 'IE 40161 MONSEÑOR JOSE LUIS DEL CARPIO RIVERA', 'CALLE COLON 105' ),
	(  344, 'IE 40163 BENIGNO BALLON FARFAN', 'AV. BRASIL 300' ),
	(  344, 'IE 40164 JOSE CARLOS MARIATEGUI', 'CALLE AREQUIPA 100' ),
	(  344, 'IE 40178 VICTOR RAUL HAYA DE LA TORRE', 'PASAJE ELIAS AGUIRRE SN' ),
	(  344, 'IE 40300 MIGUEL GRAU', 'AVENIDA VENEZUELA ZONA B' ),
	(  344, 'IE JUAN XXIII CIRCA', 'AVENIDA AREQUIPA 7MA CUADRA SN' ),
	(  344, 'IE NEPTALI VALDERRAMA AMPUERO', 'AV. PIZARRO 132' ),
	(  344, 'IE PAOLA FRASSINETTI FE Y ALEGRIA', 'AV. SOL 301' ),
	(  344, 'IE SAN PEDRO Y SAN PABLO CIRCA', 'AV. LA MAR SN' ),
	(  344, 'IE SOR ANA CIRCA', 'CALLE 24 DE JUNIO' ),
	(  344, 'IESTP PEDRO P DIAZ', 'AV. PIZARRO 130' ),
	(  345, 'IE 40188', 'AV. PLAZA PRINCIPAL SN' ),													-- POCSI
	(  346, 'IE 40190 SANTISIMA VIRGEN DE CHAPI', 'PLAZA PRINCIPAL SN' ),							-- POLOBAYA
	(  347, 'IE 40192', 'CALLE PLAZA PRINCIPAL' ),													-- QUEQUEDEÑA
	(  348, 'IE 40193 FLORENTINO PORTUGAL', 'CALLE PRINCIPAL 328' ),								-- SABANDIA
	(  349, 'IE 40074 JOSE LUIS BUSTAMANTE Y RIVERO', 'AV. ROBERTO PONCE SN' ),						-- SACHACA
	(  349, 'IE 40075 HORACIO MORALES DELGADO', 'CALLE LAS ROSAS 200' ),
	(  349, 'IEP COLEGIO PERUANO ALEMAN MAX UHLE', 'AV. FERNANDINI SN' ),
	(  350, 'IE 40072', 'PANAMERICANA SUR KM 918' ),												-- SAN JUAN DE SIGUAS
	(  351, 'IE 40196 TECNICO AGROPECUARIO ARTESANAL', 'AV. BOLOGNESI 301' ),						-- SAN JUAN DE TARUCANI
	(  352, 'IE 40108', 'PLAZA SONDOR MZ A LOTE 8' ),												-- SANTA ISABEL DE SIGUAS
	(  353, 'IE 40073 VICTOR MANUEL PEROCHENA LUQUE', 'CALLE VICTOR A PEROCHENA SN' ),				-- SANTA RITA DE SIHUAS
	(  354, 'IE 40172 VILLA EL GOLF', 'CALLE PANAMA 101' ),											-- SOCABAYA
	(  354, 'IE 40199', 'CALLE SANCHEZ TRUJILLO 301' ),
	(  354, 'IE 40205 MANUEL BENITO LINARES ARENAS', 'CALLE CARAVELI 200' ),
	(  354, 'IE 40208 PADRE FRANCOIS DELATTE', 'CALLE JORGE CHAVEZ CUADRA 2 SN' ),
	(  354, 'IE 40256 CARLOS MANCHEGO RENDON', 'AVENIDA CESAR VALLEJO SN' ),
	(  354, 'IE SAN MARTIN DE SOCABAYA', 'CALLE IQUITOS 201' ),
	(  355, 'I.E. CARLOS JOSE ECHAVARRI OSACAR NIVEL SECUNDARIO', 'CALLE JUAN MANUEL POLAR SN' ),	-- TIABAYA
	(  355, 'IE 40083 FRANKLIN ROOSEVELT', 'CALLE PROGRESO SN' ),
	(  355, 'IE FRANCISCO MOSTAJO', 'CALLE LOS PERALES SN' ),
	(  356, 'IE 40088 REINO DE BELGICA', 'CALLE SAN MARTIN 101' ),									-- UCHUMAYO
	(  356, 'IE 40091 ALMA MATER DE CONGATA', 'AV. CONGATA SN' ),
	(  356, 'IE 40092 JOSE DOMINGO ZUZUNAGA OBANDO', 'JR. TOQUEPALA SN' ),
	(  357, 'IE VICTOR RAUL HAYA DE LA TORRE', 'CALLE ATAHUALPA SN' ),								-- VITOR
	(  358, 'IE 40048 GRAN MARISCAL ANTONIO JOSE DE SUCRE', 'CALLE LEON VELARDE' ),					-- YANAHUARA
	(  358, 'IE 40165 SAN JUAN BAUTISTA DE LA SALLE', 'CALLE JOSE MARIA ARGUEDAS SN' ),
	(  358, 'IE LA RECOLETA', 'CALLE RECOLETA 117' ),
	(  358, 'IE SANTA ROSA DE VITERBO', 'AV. ZAMACOLA 106' ),
	(  358, 'SENCICO', 'CALLE LEON VELARDE SN' ),
	(  359, 'IE LEONIDAS BERNEDO MALAGA', 'CALLE PROGRESO SN' ),									-- YARABAMBA
	(  360, 'IE 40100 LA CALERA', 'CALLE PRINCIPAL SN' ),											-- YURA
	(  360, 'IE 40102 NUESTRA SEÑORA DEL CARMEN LA ESTACION', 'PSJ. EL PORVENIR MZ L LT 1 CARRETERA A PUNO' ),
	(  360, 'IE CHARLOTTE', 'KILOMETRO 13.5 CIUDAD DE DIOS CARRETERA A YURA' ),
	(  360, 'IE SEÑOR DE LOS MILAGROS CIRCA', 'KILOMETRO 13.5 CIUDAD DE DIOS CARRETERA A YURA' ),
 
-- ---- AREQUIPA --- CAMANA
	(  361, 'IE 41040 JOSE CARLOS MARIATEGUI', 'JR. COMERCIO 244' ),								-- CAMANA
	(  361, 'IE SEBASTIAN BARRANCA', 'AV. 09 DE NOVIEMBRE 401' ),
	(  362, 'IE 40233 JOSE MARIA QUIMPER CABALLERO', 'CALLE LIVERPOOL 200' ),						-- JOSE MARIA QUIMPER
	(  363, 'IE 40194', 'CALLE 8 SN SECOCHA BAJA' ),												-- MARIANO NICOLAS VALCARCEL
	(  364, 'IE 40235 SAN JOSE', 'PLAZA DE ARMAS 100' ),											-- MARISCAL CACERES
	(  364, 'IE 40236 CESAR VALLEJO', 'AV. PANAMERICANA MZ. F LT. 6 -PUCCHUN' ),
	(  365, 'IE 40239 NICOLAS DE PIEROLA', 'AV. NICOLAS DE PIEROLA 1800' ),							-- NICOLAS DE PIEROLA
	(  366, 'IE JOSE MARIA MORANTE', 'CALLE JOSE MARIA MORANTE 101' ),								-- OCOÑA
	(  367, 'IE 40244 VIRGEN DE LA CANDELARIA DE QUILCA', 'CALLE MIRAMAR SN' ),						-- QUILCA
	(  368, 'IE FAUSTINO B FRANCO', 'AV. SAMUEL PASTOR 1301' ),										-- SAMUEL PASTOR
	(  368, 'IE NUESTRA SRA DE LA CANDELARIA', 'AV. SAMUEL PASTOR 1203' ),

-- ---- AREQUIPA --- CARAVELI
	(  369, 'IE NICOLAS DE PIEROLA', 'CALLE MARISCAL ORBEGOSO' ),									-- ACARI
	(  370, 'IE MIGUEL GRAU', 'CALLE PORVENIR SN' ),												-- ATICO
	(  371, 'IE 40289', 'PLAZA PRINCIPAL SN' ),														-- ATIQUIPA
	(  372, 'I.E. 40268 PRIMARIA', 'AV. FRANCISCO FLORES BERRUEZO SN' ),							-- BELLA UNION
	(  373, 'IE VIRGEN DE COPACABANA', 'AV. ERNESTO PORTUGAL SN' ),									-- CAHUACHO
	(  374, 'IE INDEPENDENCIA DEL PERU', 'JR. AYACUCHO 800' ),										-- CARAVELI	
	(  375, 'IE HORTENCIA PARDO MANCEBO', 'AVENIDA FRANKLIN PEASE OLIVERA SN' ),					-- CHALA
	(  376, 'IE NUESTRA SEÑORA MARIA DEL PILAR', 'AV. HORTENCIA NEYRA SN' ),						-- CHAPARRA
	(  377, 'IE 40297 JUAN BAUTISTA DE TOCOTA', 'AV. JULIAN DONGO CHACON SN' ),						-- HUANUHUANU
	(  377, 'IE CARLOS NORIEGA JIMENEZ', 'CALLE PEROL CON AV. MOLLEHUACA SN' ),
	(  378, 'IE SAN FRANCISCO DE ASIS', 'AV. SOLOGUREN SN' ),										-- JAQUI
	(  379, 'IE 40299 JOSE ALFREDO MOLINA', 'CALLE VICTORIA SN' ),									-- LOMAS
	(  380, 'IE SAN ANTONIO DE LA PIEDRA', 'CALLE MAGISTERIAL SN' ),								-- QUICACHA
	(  381, 'IE SAN PEDRO DE YAUCA', 'CALLE NICOLAS DE PIEROLA SN' ),								-- YAUCA

-- ---- AREQUIPA --- CASTILLA
	(  382, 'IE 40314 NUESTRA SEÑORA DE LA ASUNCION', 'CALLE LA MOCCA SN' ),						-- ANDAGUA
	(  383, 'IE 40440 CORAZON DE FATIMA', 'CALLE JORGE CHAVEZ L1-1' ),								-- APLAO
	(  383, 'IE LIBERTADOR CASTILLA', 'AV. 3 DE ABRIL SN' ),
	(  384, 'IE 40316 JULIO ERNESTO LAZO DIAZ', 'CALLE ROSARIO SN' ),								-- AYO
	(  385, 'IE 40317 SAN ANTONIO DE PADUA', 'CALLE CALVARIO SN' ),									-- CHACHAS
	(  385, 'IE 40349 TOLCONI', 'AV. FRANCISCO BOLOGNESI' ),
	(  385, 'IE 40607 CHECOTAÑA', 'PLAZA PRINCIPAL SN' ),
	(  386, 'IE 40352 BENJAMIN GOMEZ', 'PLAZA DE ARMAS SN' ),										-- CHILCAYMARCA
	(  387, 'IE 40318 LLANCA', 'PLAZA PRINCIPAL SN' ),												-- CHOCO
	(  387, 'IE 40319', 'CALLE PROLONGACIÓN PROGRESO SN' ),
	(  387, 'IE 40354 UCUCHACHAS', 'CALLE PRINCIPAL SN' ),
	(  387, 'LOCAL COMUNAL MIÑA', 'PLAZA PRINCIPAL SN' ),
	(  388, 'IE 40320 NUESTRA SEÑORA DEL ROSARIO', 'AVENIDA AREQUIPA SN' ),							-- HUANCARQUI
	(  389, 'IE 40322 NUESTRA SEÑORA DE LA ASUNTA', 'CALLE SANTIAGO HUACO SN' ),					-- MACHAGUAY
	(  390, 'IE ALBERTO FLORES GALINDO', 'AV. SANTA ROSA DE LIMA SN' ),								-- ORCOPAMPA
	(  391, 'IE 40140 JUAN PABLO VIZCARDO Y GUZMAN', 'CALLE SALAVERRY 309' ),						-- PAMPACOLCA
	(  392, 'IE CESAR AUGUSTO DURAN LAZARTE', 'CALLE TORREBLANCA SN' ),								-- TIPAN
	(  393, 'IE 40331 MARIA AUXILIADORA', 'CALLE PLAZA 28 DE JULIO 209' ),							-- URACA
	(  394, 'IE 40330', 'CALLE PROGRESO SN' ),														-- UÑON
	(  395, 'IE 40336 SAGRADO CORAZON DE JESUS', 'CALLE COMERCIO SN' ),								-- VIRACO

-- ---- AREQUIPA --- CAYLLOMA
	(  396, 'IE 40376 MIXTO ACHOMA', 'CALLE SUCRE SN' ),											-- ACHOMA
	(  397, 'IE 40379', 'SANCHEZ CERRO SN' ),														-- CABANACONDE
	(  397, 'IE 40600 CLOTILDE FRANCISCA ODICIO ZUÑIGA', 'CALLE PRESBITERO SALAS SN' ),
	(  398, 'IE 40380 CALLALLI', 'CALLE TAHUANTISUYO SN' ),											-- CALLALLI	
	(  399, 'IE 40030 SAN FRANCISCO DE ASIS', 'AV. CAYLLOMA CAYARANI SN' ),							-- CAYLLOMA
	(  399, 'IE 40381 SANTA ROSA DE LIMA', 'CALLE MODESTO MALAGA SN' ),
	(  400, 'IE FRANCISCO GARCIA CALDERON', 'CALLE LADISLAO ESPINAR SN' ),							-- CHIVAY
	(  401, 'IE VIRGEN DE CHAPI', 'CALLE HUANCAVELICA SN' ),											-- COPORAQUE
	(  402, 'IE 40383 JUAN PABLO II', 'CALLE PLAZA DE ARMAS SN' ),									-- HUAMBO
	(  403, 'IE 40384 SONCCOY QUILLA', 'PAMPA BERNEDO SN' ),											-- HUANCA
	(  404, 'IE 40386 TUPAC AMARU', 'CALLE BOLOGNESI SN' ),											-- ICHUPAMPA
	(  405, 'IE 40387', 'AV. UCAYALI SN' ),															-- LARI
	(  406, 'IE 40388', 'CALLE CALVARIO SN' ),														-- LLUTA
	(  406, 'IE 40389 MIGUEL LINARES MALAGA', 'CALLE MIGUEL LINARES MALAGA SN' ),
	(  407, 'IE 40390 MAYTA CAPAC', 'AV. AREQUIPA SN' ),											-- MACA
	(  408, 'IE 40391 CORAZON DE JESUS', 'AV. SAN MARTIN SN' ),										-- MADRIGAL
	(  409, 'IE 40201 TECNICO AGROPECUARIO LA COLINA', 'AV. PRINCIPAL SN' ),						-- MAJES
	(  409, 'IE 40230 SAN ANTONIO DE PEDREGAL', 'AV. TERMINAL TERRESTRE SN' ),
	(  409, 'IE 40594 GENERAL JUAN VELASCO ALVARADO', 'CALLE PRINCIPAL SN' ),
	(  409, 'IE 40698 COLEGIO SAN JUAN BAUTISTA', 'AV. VIRGEN DE CHAPI MZ C4 LT 1' ),
	(  409, 'IE ALMIRANTE MIGUEL GRAU', 'CALLE YARABAMBA SN' ),
	(  409, 'IE JUSTO JUEZ', 'AV. DIAGONAL SN' ),
	(  410, 'IE 40392 JOSE ANTONIO ENCINAS', 'CALLE SIMON BOLIVAR SN' ),							-- SAN ANTONIO DE CHUCA
	(  411, 'IE TECNICO AGROPECUARIO SIBAYO', 'PSJ. FUNDICION SN' ),									-- SIBAYO
	(  412, 'IE 40418', 'CALLE GARCILAZO SN' ),														-- TAPAY
	(  413, 'IE 40395', 'CALLE 28 DE JULIO SN' ),													-- TISCO
	(  413, 'IE 40421 JOSE OLAYA - SECUNDARIA', 'PJ. UNION SN' ),
	(  414, 'IE 40396 TUTI', 'CALLE JERUSALEN SN' ),												-- TUTI
	(  415, 'IE 40397 SAN ANTONIO DE PADUA', 'CALLE SAN ANTONIO DE PADUA 300' ),					-- YANQUE
	(  415, 'IE 40399 GENERAL JUAN VELASCO ALVARADO', 'CALLE JERUSALEN 508' ),

-- ---- AREQUIPA --- CONDESUYOS
	(  416, 'IE 40430 JOSE SIMEON TEJEDA', 'CALLE FRANCISCO BOLOGNESI 200' ),						-- ANDARAY
	(  417, 'IE 40458 SAN JUAN BAUTISTA', 'CALLE TRIUNFO SN' ),										-- CAYARANI
	(  417, 'IE 40459 SAN ROQUE', 'PSJ. SANTA ROSA SN' ),
	(  417, 'IE 40568 ARCATA', 'CALLE ARCATA SN' ),
	(  418, 'IE 40432 VICTOR RAUL HAYA DE LA TORRE', 'PLAZA PRINCIPAL SN' ),						-- CHICHAS
	(  419, 'IE 41045 CORAZON DE JESUS', 'AV. CIRO ALEGRIA 201' ),									-- CHUQUIBAMBA
	(  420, 'IE 40434 SAN MARTIN DE PORRAS', 'AV. PRINCIPAL SN' ),									-- IRAY
	(  421, 'IE 40446 MIGUEL GRAU', 'PLAZA PRINCIPAL SN' ),											-- RIO GRANDE
	(  422, 'IE 40436 SALAMANCA', 'PSJ. SANTA IGLESIA SN' ),										-- SALAMANCA
	(  423, 'IE 40439 SAN JUAN BAUTISTA DE LA SALLE', 'CALLE 5 DE AGOSTO SN' ),						-- YANAQUIHUA
	(  423, 'IE JORGE BASADRE', 'AV. BRASIL SN' ),

-- ---- AREQUIPA --- ISLAY
	(  424, 'IE MARIANO EDUARDO DE RIVERO Y USTARIZ MERU', 'AV. PROGRESO 1200' ),					-- COCACHACRA
	(  425, 'IE 40484 VIRGEN DE FATIMA', 'CALLE FATIMA SN' ),										-- DEAN VALDIVIA
	(  426, 'IE 40479 MIGUEL GRAU', 'CALLE MIGUEL GRAU SN' ),										-- ISLAY
	(  427, 'IE 40494 JOSE ABELARDO QUIÑONES', 'AV. TAMBO SN' ),									-- MEJIA
	(  428, 'IE 40472 CARLOS MANUEL FEBRES', 'CALLE TEOFILO NUÑEZ 201' ),							-- MOLLENDO
	(  428, 'IE 40473 JOSE EMILIO PACHECO ANTESANA', 'CALLE PUNO 347' ),
	(  428, 'IE 40476 MERCEDES MANRIQUE', 'CALLE FLORIDA MZ F Y G' ),
	(  428, 'IE JOSE CARLOS MARIATEGUI', 'CALLE SAN MARTIN SN' ),
	(  428, 'IE SAN VICENTE DE PAUL', 'CALLE COMERCIO SN' ),
	(  429, 'IE VICTOR MANUEL TORRES CACERES', 'CALLE VICTOR LIRA SN' ),							-- PUNTA DE BOMBON

-- ---- AREQUIPA --- LA UNION
	(  430, 'IE CORONEL CASIMIRO PERALTA', 'AV. MARISCAL CASTILLA 106' ),							-- ALCA
	(  431, 'IE 40515 SAN SEBASTIAN', 'CALLE STADIUM RADA SN' ),									-- CHARCANA
	(  432, 'IE MARISCAL ORBEGOSO', 'AV. SANTA ANA 222' ),											-- COTAHUASI
	(  433, 'IE 40517 CAPITAN EVARISTO AMESQUITA', 'PLAZA DE ACHO SN' ),							-- HUAYNACOTAS
	(  434, 'IE 40523 JUAN LUIS SOTO MOTTA', 'CALLE 28 DE JULIO SN' ),								-- PAMPAMARCA
	(  435, 'IE 40525 SAN SANTIAGO', 'CALLE 13 DE OCTUBRE SN' ),									-- PUYCA
	(  436, 'IE 40558 VELINGA', 'PLAZA PRINCIPAL SN' ),												-- QUECHUALLA
	(  437, 'IE 40526 SAN MARTIN DE TOURS', 'CALLE 28 DE JULIO SN' ),								-- SAYLA
	(  438, 'IE 40529 VICTOR ANDRES BELAUNDE', 'CALLE HUARCARPUNA SN' ),							-- TAURIA
	(  439, 'IE 40531 HONOFRE BENAVIDES', 'PLAZA DE ARMAS SN' ),									-- TOMEPAMPA
	(  440, 'IE 40534 JUAN MANUEL GUILLEN BENAVIDES', 'BARRIO DE CCATO' )							-- TORO