use Onpe;
insert LocalVotacion(idDistrito, RazonSocial, Direccion) values

-- ---- AYACUCHO --- CANGALLO
	(  441, 'IE MARIA PARADO DE BELLIDO', 'AV. CENTENARIO SN' ),									-- CANGALLO
	(  442, 'IE 38126 MX-P', 'AV. RAMON CASTILLA SN' ),												-- CHUSCHI
	(  443, 'IE 38197 MIXTO-SATICA', 'PLAZA PRINCIPAL SN' ),										-- LOS MOROCHUCOS
	(  443, 'IE HUMBERTO SANCHEZ DEL PINO', 'AV. LOS ESTUDIANTES SN' ),
	(  443, 'IEP LOS MOROCHUCOS', 'AV. LOS ESTUDIANTES SN' ),
	(  444, 'IE 38131 PRIMARIA', 'AV. CENTENARIO SN' ),												-- MARIA PARADO DE BELLIDO
	(  445, 'IE 38136 PMX MARIA PARADO JAYO', 'PLAZA PRINCIPAL SN' ),								-- PARAS
	(  445, 'IE 38203 MXP CCARHUACCOCCO', 'JR. AREQUIPA SN' ),
	(  445, 'IE REPÚBLICA INDEPENDENCIA AMERICANA', 'CCPP DE CCARHUALICAPA' ),
	(  445, 'IE SAN CRISTOBAL', 'AV. LA LIBERTAD SN' ),
	(  446, 'IE 38139 PRIMARIA', 'JR. JOSE OLAYA SN' ),												-- TOTOS

-- ---- AYACUCHO -- HUAMANGA
	(  447,	'CE INTEGRADO GENERAL TRINIDAD MORAN', 'BARRIO PARASPAMPA S/N' ),						-- ACOCRO
	(  448, 'IE MARISCAL GUILLERMO MILLER', 'AV. MARISCAL GUILLERMO MILLER S/N'	),					-- ACOS VINCHOS
	(  449,	'IE SIMON BOLIVAR', 'JR. MOQUEGUA S/N' ),												-- ANDRES AVELINO CACERES
	(  450, 'CENTRO PRE UNIVERSITARIO UNSCH', 'URB. MARISCAL CARECES MZ. R LT. 22' ),				-- AYACUCHO
	(  450, 'IE 9 DE DICIEMBRE', 'JR. BELLIDO N° 561' ),
	(  450, 'IE JOSE BALTA MONTERO', 'PLAZA PRINCIPAL S/N' ),
	(  450, 'IE LUIS CARRANZA', 'JR. ASAMBLEA N° 339' ),
	(  450, 'IE MARIA PARADO DE BELLIDO', 'JR. CALLAO N° 289' ),
	(  450, 'IE N° 38001 GUSTAVO CASTRO PANTOJA', 'JR. GARCILAZO DE LA VEGA N° 111' ),
	(  450, 'IE PLANTELES DE APLICACION GUAMAN POMA DE AYALA', 'PSJ. SAN JOAQUIN S/N' ),
	(  450, 'IEI N° 102 ROSITA DE LIMA', 'JR. LIMA N° 248' ),
	(  450, 'IEP LOS LIBERTADORES', 'JR. JOSE OLAYA N° 227' ),
	(  450, 'IEP NUESTRA SEÑORA DE FATIMA', 'CALLE CORCOVADO N° 120' ),
	(  450, 'UNIVERSIDAD NACIONAL DE SAN CRISTOBAL DE HUAMANGA', 'AV. INDEPENDENCIA S/N' ),
	(  450, 'UNSCH - CIENCIAS FISICO MATEMATICAS - EX EDUCACIÓN', 'AV. INDEPENDENCIA S/N' ),
	(  451, 'IEP ABRAHAM VALDELOMAR', 'PLAZA PRINCIPAL VISTA ALEGRE S/N' ),							-- CARMEN ALTO
	(  451, 'IEP JOSE GABRIEL CONDORCANQUI', 'JR. SACSAYHUAMAN S/N' ),
	(  451, 'IEP N° 38023 MX-P NUESTRA SEÑORA DEL CARMEN', 'AV. MARICAL CACERES N° 290' ),
	(  452, 'IE N° 38035 MX-P ESCUELA ESTATAL', 'JR. SAN MARTIN S/N' ),								-- CHIARA
	(  452,	'IE N° 38073 MX-P', 'CALLE DEMETRIO SALVATIERRA S/N' ),
	(  452, 'IEP CORONEL JUAN VALER SANDOVAL', 'PRLG. SAN MARTIN S/N' ),
	(  453, 'IE SEÑOR DE LOS MILAGROS', 'PSJ.FLORES N° 500' ),										-- JESUS NAZARENO
	(  453, 'IEP VILLA SAN CRISTOBAL', 'PROLONGACIÓN LOS INCAS MZ. LL LT. 7' ),
	(  453, 'IST ESCUELA SUPERIOR DE BELLAS ARTES PÚBLICA FELIPE HUAMAN POMA DE AYALA',	'JR. MARIANO MELGAR N° 398' ),
	(  454, 'IE ANDRES AVELINO CACERES', 'AV. ANDRES AVELINO MARISCAL CACERES S/N' ),				-- OCROS
	(  455, 'IE MARISCAL ANTONIO JOSE DE SUCRE', 'AV. ESMERALDA DE LOS ANDES S/N' ),				-- PACAYCASA
	(  456, 'IE LIBERTAD DE AMERICA', 'JR. LA MAR S/N' ),											-- QUINUA
	(  457, 'IE ENRIQUE LOPEZ ALBURJAR', 'CALLE CHAUPI S/N' ),										-- SAN JOSE DE TICLLAS
	(  458, 'IE CAP FAP JOSE ABELARDO QUIÑONES GONZALES', 'AV. LAS MALVINAS S/N' ),					-- SAN JUAN BAUTISTA
	(  458, 'IE N° 38030 SAN MARTIN DE PORRES', 'JR. JOSE OLAYA N° 235' ),
	(  458, 'IE N° 38056 SEÑOR DE AREQUIPA CAP FAP JOSE ABELARDO QUIÑONES GONZALES', 'AV. RAMON CASTILLA N° 836' ),
	(  458, 'IE N° 39009 EL MAESTRO', 'JR. MARIANO BELLIDO N° 119' ),
	(  458, 'IE SAN JUAN','JR. BASILIO AUQUI N° 302' ),
	(  459, 'IE N° 38046 MX-P SAN PEDRO DE CACHIS', 'JR. TUPAC AMARU N° 104' ),						-- SANTIAGO DE PISCHA
    (  459, 'IE N° 38802 INCA GARCILAZO DE LA VEGA', 'JR. JOSE CAVERO TORRES S/N' ),
    (  460, 'IE N° 38048 JOSE ENCINAS FRANCO', 'JR. 15 DE AGOSTO S/N' ),							-- SOCOS
	(  461, 'IE N° 409', 'PLAZA PRINCIPAL S/N' ),													-- TAMBILLO
	(  461, 'IEP TNTE. GUSTAVO ESCUDERO OTERO', 'PLAZA PRINCIPAL S/N' ),
	(  462, 'IE N° 38049 MX-P SAN FRANCISCO DE ASIS', 'PLAZA PRINCIPAL S/N' ),						-- VINCHOS
	(  462, 'IE N° 38050 MX-P ARISTIDES GUILLEN VALDIVIA', 'BARRIO TRIGOPAMPA S/N' ),
	(  462, 'IE N° 38104 DE OCCOLLO', 'PLAZA PRINCIPAL OCCOLLO S/N' ),
	(  462, 'IE N° 38575 PUTAQA', 'AV. CENTENARIO S/N' ),
	(  462, 'IEP JOSE DE SAN MARTIN', 'BARRIO ACOPAMPA S/N' ),
	
-- ---- AYACUCHO --- HUANCA SANCOS
	(  463, 'IE 38467', 'JR. PROGRESO SN' ),														-- CARAPO
	(  463, 'IE 38469 MIXTO POLIDOCENTE', 'JR. FRAY MARTIN DE PORRAS SN' ),
	(  463, 'IE 38470', 'JR. 28 DE JULIO SN' ),
	(  463, 'IE 38472 ANEXO CPM MANCHIRI', 'JR. HATUN PAMPA SN' ),
	(  464, 'IE 38493', 'JR. SAN MARTIN SN' ),														-- SACSAMARCA
	(  464, 'IE ANANIAS SUMARI MENDOZA', 'AV. ANANIAS SUMARI MENDOZA SN' ),
	(  465, 'IE 38491 DE MENORES NUESTRA SEÑORA DE FATIMA', 'JR. HUANCAVELICA SN' ),				-- SANCOS
	(  466, 'IE N° 38487 MX-P', 'CALLE LEONCIO PRADO SN' ),											-- SANTIAGO DE LUCANAMARCA

-- ---- AYACUCHO --- HUANTA
	(  467, 'IE 38553 MX- POLIDOCENTE', 'AV. PERU S/N' ),											-- AYAHUANCO
	(  468, 'IE N° 400 MIXTO CANAYRE', 'AV. AVIACION S/N' ),										-- CANAYRE
	(  469, 'IE N° 38270 MIXTO POLIDOCENTE SAN ANTONIO', 'JR. FRANCISCO PIZARRO S/N' ),				-- HUAMAGUILLA
	(  470, 'IE ESMERALDA DE LOS ANDES', 'JR. MARIA JESUS RUIZ SN' ),								-- HUANTA
	(  470, 'IE MARIA AUXILIADORA', 'JR. RASHUILCA N° 924' ),
	(  470, 'IE N° 39013 CLARA CASTILLO DE GALLOZO', 'JR. F. VALLADARES N° 229' ),
	(  470, 'IE SAN RAMON', 'JR. OSVALDO N. REAL N° 625' ),
	(  471, 'IE AGROPECUARIO CARLOS CH. HIRAOKA', 'CALLE HOSPITAL PAMPA SN' ),						-- IGUAIN
	(  472, 'IE N° 38356 PEDRO RUIZ GALLO', 'JR. 28 DE JULIO S/N' ),								-- LLOCHEGUA
	(  472, 'IE N° 38951 MX.U. CHONGOS CARMEN PAMPA', 'CC.PP. CHONGOS CARMEN PAMPA S/N' ),
	(  473, 'IE N° 38276 MX-P SAN MARTIN DE PORRAS', 'AV. CARLOS CHE HIRAOKA S/N' ),				-- LURICOCHA
	(  474, 'IE N° 38269 JOSE CARLOS MAREATEGUI', 'CC.PP. HUALLHUA S/N' ),							-- PUCACOLPA
	(  474, 'IE N° 38321 SEÑOR DE LA DIVINA MISERICORDIA', 'CC.PP. CHACHASPATA S/N' ),
	(  474, 'IE N° 38322 MX-P PALOMA ALEGRE', 'CC.PP. PALOMA ELEGRE S/N' ),
	(  474, 'IE N° 38326', 'AV. VIZCATAN S/N' ),
	(  475, 'IE CESAR VALLEJO MENDOZA', 'RAZOHUYCA S/N' ),											-- SANTILLANA
	(  475, 'IE N° 38285 MX POLIDOCENTE SAGRADO CORAZON DE JESUS', 'JR. 28 DE JULIO S/N' ),
	(  476, 'IE N° 38268 MX-P', 'JR. QUINACHO S/N' ),												-- SIVIA
	(  476, 'IE N° 38313 MIXTO SAN MIGUEL ARCANGEL', 'AV. ANCON S/N' ),
	(  476, 'IE N° 38316', 'CC.PP. GUAYAQUIL S/N' ),
	(  476, 'IEI N° 429-68 MX', 'CC.PP. TUTUMBARO' ),
	(  477, 'I.E.I N° 429-7 MX POLIDOCENTE', 'AV. KEIKO FUJIMORI S/N' ),							-- UCHURACCAY
	(  477, 'IE N° 38290 MX POLIDOCENTE', 'CALLE PRINCIPAL S/N' ),
	(  477, 'IE SIMON ENRIQUE SANCHEZ TORRES', 'CC.PP. PAMPALCA S/N' ),
	(  477, 'IE VIRGEN DEL ROSARIO', 'CARRETERA AL VRAE S/N' ),
	(  477, 'IEI N° 429-4 HUAYCHAO', 'CC.PP. HUAYCHAO S/N' ),
	(  477, 'IEI N° 429-5 MIXTO HUAYNACANCHA', 'CARRETERA HUAYNACANCHA S/N' ),

-- ---- AYACUCHO --- LA MAR
	(  478, 'IE NERY GARCIA ZARATE', 'AV. 24 DE ABRIL S/N' ),										-- ANCHICHUAY
	(  479, 'IE CESAR VALLEJO', 'AV. SAN MARTIN S/N' ),												-- ANCO
	(  479, 'IE DOS DE MAYO', 'AV. QUNQAY WAÑUY S/N' ),
	(  479, 'IE FRANCISCO DE ZELA', 'CALLE MAGISTERIAL S/N' ),
	(  479, 'IE N° 38991 MARIA ANTONIETA MOROTE DE JERI', 'CC.PP. SACHARACCAY -HUALLHUA S/N' ),
	(  479, 'IE VIRGEN DE LAS NIEVES', 'CC.PP. ARHUIMAYO S/N' ),
	(  480, 'IE N° 39017 MX-P', 'PLAZA 4 DE OCTUBRE S/N' ),											-- AYNA
	(  481, 'IEP RAMIRO PRIALE PRIALE', 'PLAZA PRINCIPAL S/N' ),									-- CHILCAS
	(  482, 'IE LEONCIO PRADO', 'AV. PROGRESO S/N' ),												-- CHUNGUI
	(  482, 'IE N° 38692', 'CC.PP. ORONCCOY S/N' ),
	(  482, 'IE N° 38865', 'CC.PP. SAN JOSE DE VILLA VISTA S/N' ),
	(  482, 'IEP N° 38377 MX-P', 'PLAZA PRINCIPAL S/N' ),
	(  482, 'IEP N° 38781 MX-P VILLA AURORA', 'CC.PP. VILLA AURORA S/N' ),
	(  483, 'IEP N° 38430 MX-P', 'AV. LOS HERMANOS ANYOSA S/N' ),									-- LUIS CARRANZA
	(  484, 'IE N° 38599 MX-P', 'AV. LAS PALMAS S/N' ),												-- SAMUGARI
	(  484, 'IE SAN JOSE', 'AV. MARISCAL CACERES S/N' ),
	(  485, 'IE 9 DE DICIEMBRE', 'JR. FRANCISCO PIZARRO S/N' ),										-- SAN MIGUEL
	(  485, 'IE SEÑOR DE LOS MILAGROS', 'AV. RAMON CASTILLA N° 316' ),
	(  486, 'IEP N° 38445 MX-P SANTA ROSA', 'JR. AYACUCHO S/N' ),									-- SANTA ROSA
	(  487, 'IE 38379 MX-P', 'CERCADO DE TAMBO MZ D LT .01' ),										-- TAMBO
	(  487, 'IE SAN MARTIN DE PORRAS', 'JR. JOSE GALVEZ N° 105' ),

-- ---- AYACUCHO --- LUCANAS
	(  488, 'IE 24076 VIRGEN DE LAS MERCEDES', 'AV. TUPAC AMARU 300' ),								-- AUCARA
	(  488, 'IE 24078 SAN DIEGO DE ISHUA', 'JR. 28 DE JULIO SN' ),
	(  488, 'IE 24101', 'JR. JOSE OLAYA SN' ),
	(  488, 'IE 24102 MARIA AUXILIADORA PAMPAMARCA', 'AV. MARIA PARADO DE BELLIDO SN' ),
	(  489, 'IE MANUEL SEOANE CORRALES', 'JR. EUSEBIO DELGADO VELARDE SN' ),						-- CABANA
	(  490, 'IE 24073 LUIS ALFARO CALLE', 'JR. LIMA 702' ),											-- CARMEN SALCEDO
	(  491, 'IE 24001 CHAVIÑA', 'JR. LA CANTUTA SN' ),												-- CHAVIÑA
	(  492, 'IE 24085', 'JR. CAHUIDE SN' ),															-- CHIPAO
	(  492, 'IE 24117', 'JR.28 DE JULIO SN' ),
	(  493, 'IE 24157 SAN MIGUEL ARCANGEL', 'CALLE SOCOS SN' ),										-- HUAC-HUAS
	(  494, 'IE 23019',	'AV. MOISES GALIMIDE SUSEN SN' ),											-- LARAMATE
	(  495, 'IE 24004', 'CALLE HAYA ORCCO SN' ),													-- LEONCIO PRADO
	(  495, 'IE 24003 SARA SANABRIA HERMOZA', 'PLAZA DE ARMAS SN' ),
	(  496, 'IE 24162', 'CALLE COMERCIO SN' ),														-- LLAUTA
	(  497, 'IE PATRON APOSTOL SANTIAGO', 'JR. MERCURIO SN' ),										-- LUCANAS
	(  498, 'IE 24164 PLINIO G BENDEZU HUAMAN', 'AV. QUINTILIANO BENDEZU SN' ),						-- OCAÑA
	(  498, 'IE 24166', 'PSJ. CHEJELE SN' ),
	(  498, 'IE 24207', 'MARIA REICH SN' ),
	(  499, 'IE 24168 SANTA ROSA DE OTOCA', 'JR. MALAMBO SN' ),										-- OTOCA
	(  500, 'IE 24049', 'PLAZA PRINCIPAL SN' ),														-- PUQUIO
	(  500, 'IE 25501', 'JR. 9 DE DICIEMBRE 123' ),
	(  500, 'IE NUESTRA SEÑORA DEL PERPETUO SOCORRO', 'JR. 9 DE DICIEMBRE 461' ),
	(  501, 'IE 24020 MARIA AUXILIADORA', 'PLAZA DE ARMAS SN' ),									-- SAISA
	(  502, 'IE 24007', 'PLAZA PRINCIPAL SN' ),														-- SAN CRISTOBAL
	(  503, 'IE 24021 JOSE MARIA ARGUEDAS', 'JR. RAMON CASTILLA SN' ),								-- SAN JUAN
	(  504, 'IE 24025 SAN PEDRO', 'AV. JUAN VELASCO ALVARADO SN' ),									-- SAN PEDRO
	(  504, 'IE 24064 SR. DE LOS MILAGROS - SAN PABLO', 'PLAZA DE ARMAS SN' ),
	(  505, 'IE 24169 PRIMARIA PALCO', 'CALLE PLAZA DE ARMAS SN' ),									-- SAN PEDRO DE PALCO
	(  505, 'IE 24217 SAGRADO CORAZON DE JESUS', 'JR. TUPAC AMARU SN' ),
	(  506, 'IE 24017 VIRGEN DEL ROSARIO', 'AV.PARQUE EL SOL SN' ),									-- SANCOS
	(  506, 'IE 24058 SAN JUAN BAUTISTA - CHAQUIPAMPA', 'JR. CHAVIÑA SN' ),
	(  506, 'IE 24345', 'CARRETERA PRINCIPAL CHICALLE SN' ),
	(  506, 'IE 24460 SAN LUIS ALTA', 'ESTADIO SAN LUIS ALTA SN' ),
	(  507, 'IE 24091 VICTOR MOISES BRINGAS', 'JOLL PAPAMPA SN' ),									-- SANTA ANA DE HUAYCAHUACHO
	(  508, 'IE 24067', 'PLAZA DE ARMAS SN' ),														-- SANTA LUCIA
	(  508, 'IE 24072', 'PLAZA DE ARMAS SN' ),
	(  508, 'IE SECUNDARIA JORGE MEIER DE HUANCA', 'CALLE ESTUDIANTES SN' ),
	(  508, 'IE VIRGEN DE SANTA LUCIA', 'CALLE LIMA SN' ),

-- ---- AYACUCHO --- PARINACOCHAS
	(  509, 'IE 24231 PATROCINIA SEVILLA DE PIMENTEL - PRIMARIA DE MENORES MIXTO', 'CRUZ PAMPA SN' ),	-- CHUMPI
	(  510, 'IE 24220 VIRGEN DE FATIMA - PRIMARIA DE MENORES MIXTO', 'PARQUE CEFERINO VASQUEZ SN' ),	-- CORACORA
	(  510, 'IE 24379 PRIMARIA DE MENORES MIXTO PAMPAMARCA', 'AV. PARINACOCHAS SN' ),
	(  510, 'IE 24383 PRIMARIA MENORES MIXTO', 'CARRETERA INTEROCEANICA SN' ),
	(  511, 'IE NUESTRA SEÑORA DE COPACABANA', 'BARRIO CCASAPAMPA SN' ),							-- CORONEL CASTAÑEDA
	(  512, 'IE 24311 TRINIDAD GUTIERREZ DE VALDIVIA', 'AV. EL MAESTRO SN' ),						-- PACAPAUSA
	(  513, 'IE 24236 LINO DE LA CRUZ GARCIA M. MX', 'PRLG SAN ANTONIO' ),							-- PULLO
	(  513, 'IE 24296', 'CALLE PROCERES DE LA INDEPENDENCIA SN' ),
	(  514, 'IE HEROES DE AYACUCHO', 'PROLONGACION SAN ISIDRO SN' ),								-- PUYUSCA
	(  515, 'IE SEGUNDINO JIMENEZ ALVAREZ', 'CALLE PRINCIPAL SN' ),									-- SAN FRANCISCO DE RAVACAYCHO
	(  515, 'IE TUPAC AMARU', 'CALLE EMANCIPACION SN' ),
	(  516, 'IE 24243 PORTAL DEL VALLE HUANCA HUANCA', 'JR. 9 DE DICIEMBRE SN' ),					-- UPAHUACHO
	(  516, 'IE 24281 CAMINOS DEL INCA', 'CALLE PRINCIPAL SN' ),
	(  516, 'IE 24282 PRIMARIA DE MENORES MIXTO', 'AV. 28 DE JULIO SN' ),
	(  516, 'IE 24284 ALBERTO FUJIMORI FUJIMORI', 'JR. LOS CEDROS SN' ),
	(  516, 'IE 24287 DESIDERIO OSEDA HUAYLLANI', 'AV. APURIMAC SN' ),

-- ---- AYACUCHO --- PAUCAR DEL SARA SARA
	(  517, 'IE RAUL HEREDIA GUARDIA', 'AV. 28 DE JULIO SN' ),										-- COLTA
	(  518, 'IE SAN PEDRO DE CORCULLA', 'JR. AREQUIPA SN-PLAZA PRINCIPAL' ),						-- CORCULLA
	(  519, 'IE 24297 SEÑOR DE LAMPA', 'PLAZA DE ARMAS SN' ),										-- LAMPA
	(  519, 'IE 24327 SEÑOR DE LOS MILAGROS', 'PLAZA DE ARMAS SN' ),
	(  520, 'IE 24291 MIXTO POLIDOCENTE PERUANO ALEMAN', 'AV. TUPAC AMARU SN' ),					-- MARCABAMBA
	(  521, 'IE 24369 LOS ANDES', 'CARRETERA A LA MINA INMACULADA SN' ),							-- OYOLO
	(  521, 'IE ANDRES AVELINO CACERES', 'PLAZA PRINCIPAL SN' ),
	(  522, 'IE 24234 SANTA CRUZ', 'JR. BRASIL SN' ),												-- PARARCA
	(  523, 'IEP MARIA PARADO DE BELLIDO', 'AV. APOSTOL SANTIAGOS SN' ),							-- PAUSA
	(  524, 'IE 24340 VIRGEN DE COCHARCAS', 'JR. AVIACION SN' ),									-- SAN JAVIER DE ALPABAMBA
	(  525, 'IE 24343 AGUSTIN BELLIDO FERNANDEZ', 'JR. DANIEL ALCIDES CARRION SN' ),				-- SAN JOSE DE USHUA
	(  526, 'IE 6 DE JULIO MIXTO', 'JR. PARINACOCHAS SN' ),											-- SARA SARA

-- ---- AYACUCHO --- SUCRE
	(  527, 'IE JOSE CARLOS MARIATEGUI', 'CALLE OCROPAMPA SN' ),									-- BELEN
	(  528, 'IE 24084', 'JR. SAN JUAN DE CHALCOS SN' ),												-- CHALCOS
	(  529, 'IE SAN PEDRO DE CHILCAYOC', 'JR. SUCRE SN' ),											-- CHILCAYOC
	(  530, 'IE 24090 MARIA PARADO DE BELLIDO', 'AV. MARIA PARADO DE BELLIDO SN' ),					-- HUACAÑA
	(  531, 'IE CESAR VALLEJO', 'JR. TUPAC AMARU SN' ),												-- MORCOLLA
	(  531, 'IE MARISCAL ANTONIO JOSE DE SUCRE', 'JR. 28 DE JULIO SN' ),
	(  532, 'IEI MARISCAL ANDRES AVELINO CACERES', 'JR. LIBERTAD SN' ),								-- PAICO
	(  533, 'IE FELIPE GUAMAN POMA DE AYALA', 'JR. MARISCAL CACERES SN' ),							-- QUEROBAMBA
	(  534, 'IEP 24132 PRIMARIA', 'AV. MARCIANO FERREL SN' ),										-- SAN PEDRO DE LARCAY
	(  535, 'IEI EL AMAUTA', 'AV. ANDAHUAYLAS SN' ),												-- SAN SALVADOR DE QUIJE
	(  536, 'IE 24146', 'CALLE TUMBES SN' ),														-- SANTIAGO DE PAUCARAY
	(  536, 'IE INCA GARCILAZO DE LA VEGA', 'KM. 6 CARRETERA CAUCARAY' ),
	(  537, 'IST EP HATUN SORAS', 'JR. BOLIVAR SN' ),												-- SORAS

-- ---- AYACUCHO --- VICTOR FAJARDO
	(  538, 'IE 38456', 'JR. HUAMANGA SN' ),														-- ALCAMENCA
	(  538, 'IE 38457 MIXTO PUBLICO', 'AV. 28 DE JULIO SN' ),
	(  538, 'IE 38458', 'JR. GRAU SN' ),
	(  539, 'IE 38459', 'PLAZA PRINCIPAL SN' ),														-- APONGO
	(  540, 'IE 38460', 'JR. MARISCAL SUCRE SN' ),													-- ASQUIPATA
	(  541, 'IE 38463', 'JR. SAN MARTIN SN' ),														-- CANARIA
	(  541, 'IE 38464 MXP TACA', 'JR. AMAUTA SN' ),
	(  542, 'IE RICARDO PALMA', 'CALLE REAL SN' ),													-- CAYARA
	(  543, 'IE 38475', 'JR. SAN MARTIN SN' ),														-- COLCA
	(  544, 'IE VIRGEN DE FATIMA', 'JR. MARISCAL CACERES SN' ),										-- HUALLA
	(  545, 'IE 38481', 'JR. BOLIVAR SN' ),															-- HUAMANQUIQUIA
	(  546, 'IE 38454 PUBLICO DE VARONES MARTIRES DE LA EDUCACION', 'JR. ALAMEDA N° 114' ),			-- HUANCAPI
	(  547, 'IE 38482 SANTO DOMINGO', 'JR. ALFONSO UGARTE SN' ),									-- HUANCARAYLLA
	(  548, 'IE 38495 MX-P', 'JR. PIQUIAPAMPA SN' ),												-- SARHUA
	(  548, 'IE JOSE RODOLFO SABOGAL WISSE', 'CCPP TOMANGA' ),
	(  548, 'IE NUESTRA SEÑORA DE ASUNCION', 'PLAZA DE ARMAS SN' ),
	(  549, 'IE ERNESTO RIOS PANTOJA', 'ASOCIACION LOS OLIVOS SN' ),								-- VILCANCHOS
	(  549, 'IE JORGE BASADRE', 'JR. PROGRESO SN' ),
	(  549, 'IE SAN PEDRO', 'CALLE PRINCIPAL SN' ),

-- ---- AYACUCHO --- VILCAS HUAMAN
	(  550, 'IEP N° 38153 MX-P CESAR VALLEJO', 'JR. CESAR VALLEJO S/N' ),							-- ACOMARCA
	(  551, 'IEP SAN PEDRO DE CARHUANCA	', 'ESTADIO SAN PEDRO DE CARHUANCA S/N' ),					-- CARHUANCA
	(  552, 'IE GARCILAZO DE LA VEGA', 'AV. ABANCAY S/N' ),											-- CONCEPCION
	(  553, 'IE N° 38164', 'AV. 28 DE JULIO S/N' ),													-- HUAMBALPA
	(  554, 'IE N° 38231 MXP', 'AV. CIRCUNVALACION S/N' ),											-- INDEPENDENCIA
	(  555, 'IEP CORAZON DE JESUS - SAURAMA', 'AV. LOS INCAS S/N' ),								-- SAURAMA
	(  556, 'IE N° 39012 DE MENORES MICAELA BASTIDAS', 'PLAZA PRINCIPAL S/N' ),						-- VILCAS HUAMAN
	(  556, 'IEP GENERAL CORDOVA', 'JR. APUMAYLA N° 130' ),
	(  557, 'IE N° 38174', 'CC.PP. POMACOCHA S/N' ),												-- VISCHONGO
	(  557, 'IE VICTOR ANDRES BELAUNDE', 'AV. INCA GARCILAZO DE LA VEGA S/N' )