use Onpe;
insert LocalVotacion(idDistrito, RazonSocial, Direccion) values

-- ---- CUSCO --- ACOMAYO 
	(  692,'IE TOMASA TITO CONDEMAYTA', 'JR. ESCALANTE' ),											-- ACOMAYO
	(  693,'IE 50072 SAN MARTIN DE PORRAS','AV. PADRE MOLINA' ),									-- ACOPIA
	(  693,'IE 56374','AV. LOS FUNDADORES' ),
	(  694,'IE 50070','AV. FINLANDIA' ),															-- ACOS
	(  695,'IE 56373 DANIEL ESTRADA PEREZ','CARRETERA A SURIMANA' ),								-- MOSOC LLACTA
	(  696,'IE 50058','PLAZA DE ARMAS' ),															-- POMACANCHI
	(  696,'IE SIMON BOLIVAR (SECUNDARIA)','CALLE CULTURA NRO 139' ),
	(  697,'IE INTEGRADA CRISTO REY (SECUNDARIA)','PLAZA DE ARMAS' ),								-- RONDOCAN
	(  698,'IE LIBERTADORES DE AMERICA','PLAZA DE ARMAS' ),											-- SANGARARA

-- ---- CUSCO --- ANTA 
	(  699,'IE 50123', 'AV. JORGE CHAVEZ' ),														-- ANCAHUASI
	(  700,'IE 50098 SAN LUIS GONZAGA','CUESTA ANTA' ),												-- ANTA
	(  700,'IE 50103 CHACAN','SECTOR LUCRE CCPP CHACAN' ),
	(  700,'IE 51025 LA INTEGRADA','JR. AGUSTIN GAMARRA' ),
	(  700,'IST AGROPECUARIA MIXTA AGUSTIN GAMARRA','CALLE PRINCIPAL' ),
	(  701,'IE 50121 SAGRADO CORAZON DE JESUS','PLAZA PRINCIPAL S/N' ),								-- CACHIMAYO
	(  702,'IE SAN ANTONIO ABAD','CALLE COMPAÑÍA S/N' ),											-- CHINCHAYPUJIO
	(  703,'IE 50108 HUAROCONDO','AV. EDUCANDAS' ),													-- HUAROCONDO
	(  703,'IE JULIO CESAR BENAVENTE DIAZ','AV. LIBERTAD SN' ),
	(  704,'IE 50111 COLEGIO LIMATAMBO','CALLE RIMACPAMPA' ),										-- LIMATAMBO
	(  705,'IE DAVID SAMANEZ OCAMPO','CALLE CUSIHUAYCO S/N' ),										-- MOLLEPATA
	(  706,'IE RAMON CASTILLA','PLAZA DE ARMAS S/N' ),												-- PUCYURA
	(  707,'IST 118 MIXTO AGROPECUARIO INA','CALLE ERASIQUI S/N' ),									-- ZURITE

-- ---- CUSCO --- CALCA
	(  708,'IE 50166', 'AV. EJERCITO S/N' ),														-- CALCA
	(  708,'IE HUMBERTO LUNA','CALLE ESPINAR 401' ),
	(  708,'IE NUESTRA SEÑORA DE BELEN','JIRON UCAYALI S/N' ),
	(  708,'IE SAGRADO CORAZON DE JESUS','AV. VILCANOTA S/N' ),
	(  709,'IE 50159 CLORINDA MATTO DE TURNER','AV. PACHACUTEC' ),									-- COYA
	(  710,'IE 50160 SAN LUIS GONZAGA LAMAY','AV. AREQUIPA 149' ),									-- LAMAY
	(  711,'IE 50167','JR. OLLANTA' ),																-- LARES
	(  711,'IE 50205','INTIKAHUARINA' ),
	(  712,'IE 50178 MIXTO BERNARDO TAMBOHUACSO','AV. AMAZONAS S/N' ),								-- PISAC
	(  713,'IE SEÑOR DE HUANCA','AV. LARGA PAMPA' ),												-- SAN SALVADOR	
	(  714,'IE 50185 MARIA AUXILIADORA','CALLE GARCILAZO' ),										-- TARAY
	(  715,'IE 50163','JR. BENJAMIN HERMOZA' ),														-- YANATILE
	(  715,'IE NUESTRA SEÑORA DEL CARMEN','AV. CALCA' ),

-- ---- CUSCO --- CANAS
	(  716,'IE 56127', 'AV. PROGRESO SN' ),															-- CHECCA
	(  717,'IE ANDRES ALENCASTRE GUTIERREZ', 'AV. MARISCAL GAMARRA' ),								-- KUNTURKANKI
	(  718,'IE 56131', 'CALLE TUPAC AMARU 245' ),													-- LANGUI
	(  719,'IE 56133', 'CALLE SAN MARTIN' ),														-- LAYO
	(  720,'IE 56118', 'AV. MICAELA BASTIDAS' ),													-- PAMPAMARCA
	(  721,'IE 56121', 'PLAZA DE ARMAS' ),															-- QUEHUE
	(  721,'IE HIPOLITO TUPAC AMARU', 'CALLE SN' ),
	(  722,'IE 56114 FERNANDO TUPAC AMARU', 'AV. TUPAC AMARU' ),									-- TUPAC AMARU
	(  723,'IE 56106', 'CALLE 28 DE JULIO NRO 1708' ),												-- YANAOCA
	(  723,'IE INDEPENDENCIA AMERICAN', 'AV. FERNANDO TUPAC AMARU' ),
	(  723,'IE JOSE GABRIEL CONDORCANQUI', 'AV. TUPAC AMARU' ),

-- ---- CUSCO --- CANCHIS
	(  724,'IE MIGUEL GRAU', 'AV. CENTRAL' ),														-- CHECACUPE
	(  725,'IE 56044', 'CALLE AYACUCHO SN' ),														-- COMBAPATA
	(  726,'IE JORGE CHAVEZ', 'AV. ROGER AGUILAR CALLO' ),											-- MARANGANI
	(  727,'IE LIBERTADORES DE AMERICA', 'JR. GARCILASO 260' ),										-- PITUMARCA
	(  728,'IE LIBERTADOR SIMON BOLIVAR', 'CALLE LEGUIA' ),											-- SAN PABLO
	(  729,'IE 56035', 'CALLE GENERAL VARELA' ),													-- SAN PEDRO
	(  730,'IE 56002', 'CALLE RICARDO PALMA 161' ),													-- SICUANI
	(  730,'IE 56003 791', 'JR. EUSEBIO DELGADO' ),
	(  730,'IE 56017 TRAPICHE AMAUTA PRIMARIA', 'PSJ. AMAUTA' ),
	(  730,'IE 57001 792', 'JR. PIURA 231' ),
	(  730,'IE EL AMAUTA', 'AV. HUNGRIA' ),
	(  730,'IE JULIO ALBERTO PONCE ANTUNEZ DE MAYOLO', 'JR. CANCHIS 201' ),
	(  731,'IE EMANCIPACION AMERICANA', 'CALLE JUNTUMA SN' ),										-- TINTA

-- ---- CUSCO --- CHUMBIVILCAS
	(  732,'IE 56260 SEÑOR DE HUANCA', 'PARQUE CCOCHAPATA' ),										-- CAPACMARCA
	(  733,'IE 56364', 'CALLE LAS ESCALERAS' ),														-- CHAMACA
	(  733,'IE DANIEL ALCIDEZ CARRION', 'CALLE SEMINARIO SN' ),
	(  734,'IE 52326', 'CCPP YANQUE' ),																-- COLQUEMARCA
	(  734,'IE 56257', 'AV. LA CULTURA' ),
	(  735,'IE 56266 LIVITICA', 'CALLE HUARARI BARRI PATAPAMPA' ),									-- LIVITACA
	(  735,'IE RAMON PONCE MOLINA (SECUNDARIA)', 'PLAZOLETA' ),
	(  736,'IE 561270 SANTA ROSA', 'CALLE SANTO TOMAS' ),											-- LLUSCO
	(  737,'IE 56272 MILAGROSO SEÑOR DE HUANCA', 'AV. GRAU SN' ),									-- QUIÑOTA
	(  738,'IE 56248', 'CALLE BOLOGNESI' ),															-- SANTO TOMAS
	(  738,'IE 57004 ROSA DE AMERICA', 'CALLE MIRAFLORES 208' ),
	(  738,'IE ANTERO EFRAIN UGARTE VIZCARRA DE PULPERA', 'CALLE AGROPECUARIO' ),
	(  739,'IE 56275 TUPAC AMARU II', 'AV. LA CULTURA' ),											-- VELILLE

-- ---- CUSCO --- CUSCO
	(  740,'IE 50007', 'PLAZA DE ARMAS' ),															-- CCORCA
	(  741,'IE 51009 FRANCISCO SIVIRICHE', 'AV. NUEVA BAJA Y ARONES S/N' ),							-- CUSCO
	(  741,'IE CIENCIAS', 'PLAZA SAN FRANCISCO SN' ),
	(  741,'IE DE MUJERES EDUCANDAS', 'CALLE TEATRO' ),
	(  741,'IE EMBLEMATICA INCA GARCILAZO DE LA VEGA', 'LA CULTURA' ),
	(  741,'IE GRAN UNIDAD ESCOLAR CLORINDA MATO DE TURNER', 'AV. LA CULTURA' ),
	(  741,'IE INSTITUCION DE MUJERES COMERCIO 41', 'AV. MARISCAL GAMARRA SN' ),
	(  741,'IE SAN FRANCISCO DE BORJA', 'PLAZA TRICENTENARIO' ),
	(  741,'UNIVERSIDAD NACIONAL SAN ANTONIO DE ABAD DEL CUSCO', 'AV. DE LA CULTURA S/N' ),
	(  742,'IE MIXTO MANUEL SEOANE CORRALES', 'JR. OSORIO S/N' ),									-- POROY
	(  743,'IE 51023 SAN LUIS GONZAGA', 'CALLE SORAMA S/N' ),										-- SAN JERONIMO
	(  743,'IE ALEJANDRO VELASCO ASTETE', 'AV. MANCO CAPAQ 02' ),
	(  743,'IE FE Y ALEGRIA', 'CALLER ARICA 363' ),
	(  744,'IE 50868 FERNANDO TUPAC AMARU', 'CALLE TOMASA TTITO CONDEMAYTA Q-1' ),					-- SAN SEBASTIAN
	(  744,'IE DIEGO QUISPE TITO', 'CALLE DANIEL ARTEAGA' ),
	(  744,'IE MIXTA VICTOR RAUL HAYA DE LA TORRE', 'CALLE TUPAC KATARI' ),
	(  744,'IE PUKLLASUNCHIS', 'TTICAPATA - TENERIA' ),
	(  744,'IE REVOLUCIONARIA SANTA ROSA', 'AV. VIA EXPRESA' ),
	(  744,'IE VIRGEN DE FATIMA', 'CALLE GARCILAZO 100' ),
	(  744,'IST TUPAC AMARU', 'AV. CUSCO 496' ),
	(  745,'IE 50707 SIMON BOLIVAR', 'AV. TUPAC AMARU SN PICCHU ALTO' ),							-- SANTIAGO
	(  745,'IE 51003 MIXTA ROSARIO', 'AV. GRAU 725' ),
	(  745,'IE 51006 TUPAC AMARU', 'CALLE BELEN S/N' ),
	(  745,'IE CECILIA TUPAC AMARU', 'AV. RAMIRO PRIALE PRIALE' ),
	(  745,'IE CORONEL FRANCISCO BOLOGNESI', 'VILLA MILITAR S/N' ),
	(  745,'IE FE Y ALEGRIA 20', 'AV. ROCOPATA 451' ),
	(  745,'IE LUIS VALLEJO SANTONI', 'JR. AYACUCHO J- 5' ),
	(  745,'IE MIXTA ANDRES AVELINO CACERES', 'CALLE RAMON CASTILLA' ),
	(  745,'IE MIXTA HUMBERTO LUNA', 'AV. CENTENARIO 700' ),
	(  745,'IE VIVA EL PERU', 'PPJJ VIVA EL PERU' ),
	(  746,'IE MIXTO ANTONIO RAYMONDI DE SAYLLA', 'AV. HUASCAR' ),									-- SAYLLA
	(  747,'IE 50025 DANIEL ESTRADA PEREZ', 'AV. PEDRO VILCA APAZA' ),								-- WANCHAQ
	(  747,'IE MARIA DE LA MERCED', 'AV. TOMASA TITO C Y AV. PEDRO VILCA APAZA' ),
	(  747,'IE MIGUEL GRAU SEMINARIO', 'AV. TOMASA TITO CONDEMAYTA' ),
	(  747,'IE NUESTRA SEÑORA DE FATIMA', 'JR. 18 DE MAYO' ),
	(  747,'IE PNP ARTURO PALOMINO', 'CALLE AGUA MARINA C-9' ),
	(  747,'IE ROMERITOS', 'CALLE CUSCO' ),
	(  747,'IE SAGRADO CORAZON DE JESUS', 'AV. 28 DE JULIO' ),
	(  747,'IE SAN JOSE DE LA SALLE', 'AV. TULLUMAYO 135' ),
	(  747,'IE URIEL GARCIA', 'AV. JORGE CHAVEZ' ),

-- ---- CUSCO --- ESPINAR
	(  748,'IE GRAL JUAN VELASCO ALVARADO', 'AV. CUZCO' ),											-- ALTO PICHIGUA
	(  749,'IE 56189', 'CALLE CANCHINITA SN' ),														-- CONDOROMA
	(  750,'CEGECON', 'CCPP TAHUAPALCA' ),															-- COPORAQUE
	(  750,'IE 56182 INTEGRADO HORACIO ZEVALLOS GAMES DE COPORAQUE PRIMARIA', 'AV. REPUBLICA' ),
	(  750,'IE BARTOLOME DE LAS CASAS', 'CCPP HUAYHUAHUASI' ),
	(  750,'IE INTEGRADO HORACIO ZEVALLOS GAMEZ DE COPORAQUE SECUNDARIA', 'AV. REPUBLICA' ),
	(  750,'IE JOSE MARIA ARGUEDAS ALTAMIRANO', 'CALLE COPORAQUE' ),
	(  750,'IE TUPAC AMARU', 'CALLE CRISTO REY' ),
	(  751,'IE 501258 CORONEL FRANCISCO BOLOGNESI', 'CALLE CAHUIDE 115' ),							-- ESPINAR
	(  751,'IE ALMIRANTE MIGUEL GRAU PRIMARIA', 'CALLE 22 DE FEBRERO' ),
	(  751,'IE CORONEL LADISLAO ESPINAR', 'AV. SAN MARTIN 802' ),
	(  751,'IE TENIENTE CORONEL PEDRO RUIZ GALLO', 'AV. CAYLLOMA' ),
	(  752,'IE SECUNDARIA JOSE CARLOS MARIATEGUI', 'CALLE AREQUIPA' ),								-- OCORURO
	(  753,'IE 56191 INDEPENDENCIA AMERICANA', 'JR. MANUEL PRADO' ),								-- PALLPATA
	(  754,'IE 56187 PICHIGUA', 'CALLE RAMON CASTILLA' ),											-- PICHIGUA
	(  754,'IE 56348 DE SAN MIGUEL ARCANGEL', 'CALLE TAHUANTINSUYO' ),
	(  755,'IE 56369 INDREY ALFREDO SALINAS PERES', 'CALLE ARICA' ),								-- SUYCKUTAMBO
--
-- ---- CUSCO --- LA CONVENCION
	(  756,'IE 269', 'AV. CAMISEA' ),																-- ECHARATE
	(  756,'IE 501108 IVOCHOTE', 'AV. UNION S/N' ),
	(  756,'IE 50243', 'JR. QUILLABAMBA' ),
	(  756,'IE 50247 PISPITAYOC', 'SECTOR PISPITAYOC ECHARATE' ),
	(  756,'IE 50285 CALZADA', 'INGRESO A ECHARATE' ),
	(  756,'IE 50300 PALMAREAL', 'COMUNIDAD IVANQUI' ),
	(  756,'IE 50898 MIGUEL GRAU KITENI', 'JUAN OLARTE' ),
	(  756,'IE 64125 FRAY JULIAN MACEGOZA PRIMARIA', 'AV. TIMPIA' ),
	(  756,'IE 64443 CAMISEA', 'AV. CAMISEA S/N' ),
	(  756,'IE 64447 NUEVO MUNDO', 'AV. 28 DE JULIO S/N' ),
	(  756,'IE FIDEL PEREYRA', 'CALLE BARRIO S/N' ),
	(  756,'IE JAVIER PEREZ DE CUELLAR', 'CALLE LAS BEGONIAS' ),
	(  756,'IE JOSE MARIA ARGUEDAS', 'AV. JOSE MARIA ARGUEDAS' ),
	(  756,'IE MONSEÑOR JAVIER ARIS HUARTE', 'AV. KIRIGUETI' ),
	(  756,'IE SANTO DOMINGO DE PANGOA', 'AV. MEGANTONI S/N' ),
	(  757,'IE JOSE CARLOS MARIATEGUI', 'AV. JOSE CARLOS MARIATEGUI' ),								-- HUAYOPATA
	(  758,'IE 50885 SAN MARTIN', 'SECTOR SAN MARTIN' ),											-- INKAWASI
	(  758,'IE 50913 CHOQUETIRA', 'CHOQUETIRA' ),
	(  758,'IE SECUNDARIO SAN FERNANDO', 'AV. PRINCIPAL' ),
	(  759,'IE 38704', 'JR. LA UNION S/N' ),														-- KIMBIRI
	(  759,'IE 38761 LIBERTADORES DEL VRAE', 'AV. LIBERTARDORES' ),
	(  759,'IE DIVINO MAESTRO', 'JR. CUSCO 455' ),
	(  759,'IE SAN JOSE DE CHIRUMPIARI', 'JR. CHIRUMPIARI' ),
	(  760,'IE MICAELA BASTIDAS', 'JR. REVOLUCION' ),												-- MARANURA
	(  761,'IE 50334 SAN LUIS GONZAGA', 'JR. NATALIA PAIVA S/N' ),									-- OCOBAMBA
	(  762,'IE LA VICTORIA', 'AV. INCA GARCILAZO DE LA VEGA' ),										-- PICHARI
	(  763,'IE 50238 SANTA ROSA DE LIMA', 'JR. MARIO LOZANO 200' ),									-- QUELLOUNO
	(  763,'IE JOSE OLAYA', 'CALLE TUPAC AMARU S/N' ),
	(  764,'IE 50227 SAN FRANCISCO JAVIER', 'JR. KUMPIRUSHATO' ),									-- SANTA ANA
	(  764,'IE 50236 SANTA ANA', 'JR. VILCABAMBA 401' ),
	(  764,'IE INA 67 AGROPECUARIO', 'PRLG BOLOGNESI' ),
	(  764,'IE LA CONVENCION', 'AV. MARTIN PIO CONCHA' ),
	(  764,'IST QUILLABAMBA', 'JR. KUMPIRUSHIATO' ),
	(  765,'IE 50273 VIRGEN DEL CARMEN', 'PRLG CALIXTO SANCHEZ' ),									-- SANTA TERESA
	(  766,'IE 50321 YUBENI', 'CALLE AREQUIPA 149' ),												-- VILCABAMBA
	(  766,'IE 50322 MANCO INCA DE PUCYURA', 'CALLE SN-SECTOR ABASPATA' ),
	(  766,'IE JOSE ANTONIO ENCINAS FRANCO KUQUIPATA', 'KM. 6.8 CARRETERA VILCABAMBA' ),
	(  767,'IE 50710 VILLA VIRGEN', 'AV. TAHUANTISUYO' ),											-- VILLA VIRGEN

-- ---- CUSCO --- PARURO
	(  768,'IE JOSE MARIA ARGUEDAS ALTAMIRANO', 'SECTOR LLOQUEYOC-URIN' ),							-- ACCHA
	(  769,'IE SAN MARTIN DE PORRES', 'SECTOR MOLLEYOC CCARANCANCHON LOCALIDA' ),					-- CCAPI
	(  770,'IE 50347 SAN JUAN BAUTISTA', 'CALLE DOS DE MAYO' ),										-- COLCHA	
	(  771,'IE INTEGRADA DE HUANOQUITE', 'MIRADOR' ),												-- HUANOQUITE	
	(  772,'IE OSCOLLOPATA', 'CCPP HUASQUILLAY' ),													-- OMACHA
	(  772,'IE SAN ISIDRO', 'COMUNIDAD ANTAJE' ),
	(  773,'IE 50357', 'CALLE FERNANDO BELAUNDE TERRY' ),											-- PACCARITAMBO
	(  774,'IE 50343 VARONES SAGRADO CORAZON DE JESUS', 'PROLONGACION GRAU HUATACALLA' ),			-- PARURO
	(  775,'IE VIRGEN DE ASUNCION PILLPINTO', 'PALOMAPATA' ),										-- PILLPINTO
	(  776,'IE SECUNDARIA MIXTA SAN ESTEBAN', 'CALLE PRINCIPAL S/N' ),								-- YAURISQUE
		
-- ---- CUSCO --- PAUCARTAMBO
	(  777,'IE 50414', 'CANUPAMPA' ),																-- CAICAY
	(  778,'IE 50427 PRIMARIA-JOSE ANTONIO ENCINAS', 'CALLE ESTUDIANTIL' ),							-- CHALLABAMBA
	(  778,'IE 50465 PRIMARIA - SECUNDARIA DANIEL ALCIDES CARRION', 'CALLE HUASCARAN' ),
	(  778,'IE MIXTO SECUNDARIO RAMIRO PRIALE PRIALE', 'JR. CONDESUYO' ),
	(  779,'IE 50421 AUGUSTO SALAZAR BONDI', 'AV. EL ESTUDIANTE' ),									-- COLQUEPATA
	(  779,'IE AUGUSTO SALAZAR BONDI', 'AV. EL ESTUDIANTE' ),
	(  780,'IE SATURNINO HUILLCA QUISPE', 'CALLE 28 DE JULIO' ),									-- HUANCARANI
	(  781,'IE 50430', 'AV. CORONEL FERNANDEZ SN' ),												-- KOSÑIPATA
	(  782,'IE 50411 SAN LUIS GONZAGA', 'AV. ENRIQUE YAVAR' ),										-- PAUCARTAMBO
	(  782,'IE 51029 SERAPIO CALDERON LAZO DE LA VEGA', 'AV. ERICKSON' ),
	(  782,'IE SECUNDARIO JOSE PEREZ Y ARMENDARIZ', 'AV. ENRIQUE YAVAR' ),

-- ---- CUSCO --- QUISPICANCHI
	(  783,'IE 50477', 'AV. GARCILAZO 316' ),														-- ANDAHUAYLILLAS
	(  784,'IE 50497 INTEGRADO ROSA DE AMERICA', 'PLAZA DE ARMAS' ),								-- CAMANTI
	(  785,'IE 50494 PRIMARIA - CCARHUAYO', 'CALLE 27 DE NOVIEMBRE' ),								-- CCARHUAYO
	(  786,'IE 50490 ESCUELA ESTATAL MIXTA - LAS MERCEDES', 'CALLE ALMIRANTE GRAU' ),				-- CCATCA
	(  786,'IE SECUNDARIO CESAR VALLEJO MENDOZA', 'CALLE MATIAS TRONCOSO' ),
	(  787,'IE TUPAC AMARU II - CUSIPATA', 'CALLE ALIPIO YABAR' ),									-- CUSIPATA
	(  788,'IE NARCISO ARESTEGUI', 'CALLE SAN MARTIN' ),											-- HUARO
	(  789,'IE 50480', 'PRLG 27 DE NOVIEMBRE' ),													-- LUCRE
	(  790,'IE 50496', 'CALLE SAQRA' ),																-- MARCAPATA
	(  791,'IE 50492 OCONGATE', 'CALLE LA LIBERTAD' ),												-- OCONGATE
	(  791,'IE 50492 PRIMARIA II', 'CALLE LA LIBERTAD' ),
	(  792,'IE 50499 JUSTO BARRIONUEVO ALVAREZ', 'CALLE UNIVERSIDAD' ),								-- OROPESA
	(  793,'IE 50483 VIRGEN DEL CARMEN', 'AV. SAN MARTIN' ),										-- QUIQUIJANA
	(  794,'IE 50472 CORAZON DE FATIMA', 'PLAZA DE ARMAS' ),										-- URCOS
	(  794,'IE 50505', 'PISTA PRINCIPAL CARRETERA INTEROCEANICA' ),
	(  794,'IE 51030 SAN MARTIN DE PORRES', 'JR. KENEDY 382' ),

-- ---- CUSCO --- URUBAMBA
	(  795,'IE 50581 NUESTRA SEÑORA DE FATIMA', 'AV. GARCILAZO 244' ),								-- CHINCHERO
	(  796,'IE NUESTRA SEÑORA DE NATIVIDAD', 'AV. LA PLAYA' ),										-- HUAYLLABAMBA
	(  797,'IE 50622 SAN JUAN BAUTISTA DE LA SALLE', 'CALLE ANTISUYO S/N' ),						-- MACHUPICCHU
	(  797,'IE INKA PACHACUTEC', 'CALLE ORQUIDEAS' ),
	(  798,'IE 50578 VIRGEN DEL CARMEN', 'CALLE JESUS' ),											-- MARAS
	(  798,'IE ANTONIO SINCHIRROCA', 'PLAZA DE ARMAS SN' ),
	(  799,'IE 50582 MANCO INCA', 'AV. DEL ESTUDIANTE' ),											-- OLLANTAYTAMBO
	(  799,'IE OLLANTAY', 'AV. DEL ESTUDIANTE 152' ),
	(  800,'IE 51031 SANTA ROSA DE LIMA', 'AV. MARISCAL CASTILLA' ),								-- URUBAMBA
	(  800,'IE GENERAL OLLANTA', 'AV. SEÑOR DE TORRECHAYOC 620' ),
	(  801,'IE 50592 SAN MARTIN DE PORRES', 'AV. SAN MARTIN 320' )									-- YUCAY