use Onpe;
insert LocalVotacion(idDistrito, RazonSocial, Direccion) values

-- ---- HUANCAVELICA --- ACOBAMBA
	(  802, 'IE NUESTRA SEÑORA DE LA CANDELARIA', 'AV. MANUEL CANDAMO SN' ),						-- ACOBAMBA
	(  802, 'IE SAN FRANCISCO DE ASIS', 'AV. MANUEL CANDAMO 288' ),
    (  803, 'IE 36305', 'AV. PLAZA PRINCIPAL S/N' ),                                                -- ANDABAMBA
	(  803, 'IE ANDRES BELLO', 'CALLE ANDABAMBA' ),
	(  803, 'IE MANUEL SCORSA TORRES', 'CALLE SIN NOMBRE' ),
	(  804, 'IE 36159', 'AV. ELVIRO CALDERON S/N' ),												-- ANTA
	(  804, 'IE 36160', 'AV. PLAZA MATIAS SN' ),
	(  804, 'IE CIRO ALEGRIA BAZAN', 'AV. ELVIRO CALDERON SN' ),
	(  805, 'IE 36161', 'AV. CENTENARIO' ),														    -- CAJA
	(  806, 'IE 36166', 'AV. MARISCAL CACERES' ),													-- MARCAS
	(  807, 'IE 36326', 'JR. TIWINSA S/N' ),														-- PAUCARA
	(  807, 'IE 36170 PAUCARA', 'CALLE AYACUCHO N 200' ), 
	(  807, 'IE 36301', 'JR. ALFONSO UGARTE' ),  
	(  808, 'IE 36172', 'JR. HUANCAVELICA S/N' ),													-- POMACOCHA
    (  809, 'IE 36177 PUCACRUZ', 'AV. LIBERTADORES' ),												-- ROSARIO

-- ---- HUANCAVELICA --- ANGARAES
	(  810, 'IE 36217 ANCHONGA', 'CALLE TUPAC AMARU' ),											    -- ANCHONGA
	(  810, 'IE 36297', 'JR. CUSCO' ),
	(  810, 'IE 36334 PARCO ALTO', 'AV. SAN JOSE S/N' ),
	(  810, 'IE SAN PABLO', 'JR. LIMA - PLAZA PRINCIPAL' ),
	(  811, 'IE 36219', 'JR. ATAHUALPA' ),															-- CALLANMARCA
	(  812, 'IE 1RO DE MAYO', 'JR. 30 DE OCTUBRE' ),												-- CCOCHACCASA
	(  813, 'CENTRO CIVICO', 'JR. BOLIVAR S/N' ),													-- CHINCHO
	(  813, 'IE 36222', 'AV. HUANTA' ), 
    (  814, 'IE 36220', 'BARRIO CUNCAPAMPA' ),														-- CONGALLA
	(  814, 'IE FRANCISCO BOLOGNESI CERVANTES', 'CCPP YUNYACCASA' ),
	(  814, 'IE JOSE OLAYA BALANDRA', 'CENTRO POBLADO CHAYNABAMBA' ),
	(  815, 'IE 36224 JOSE CARLOS MARIATEGUI', 'PLAZA PRINCIPAL' ),									-- HUALLAY-GRANDE
	(  816, 'IE 36223', 'JR. PAULINO ARAUJO' ),														-- HUANCA-HUANCA
	(  817, 'IE 36225 ALFONSO UGARTE', 'JR. ALFONSO UGARTE' ),										-- JULCAMARCA
	(  818, 'IE 37002 RICARDO FERNANDEZ', 'JR. RICARDO FERNANDEZ N° 305' ),							-- LIRCAY
    (  818, 'IE 36214', 'AV. ESMERALDA 215' ),
    (  818, 'IE 36233', 'AV. LIBERTADORES' ),
	(  818, 'IE NUESTRA SEÑORA DEL CARMEN', 'AV. ESMERALDA 450' ),
	(  818, 'IE RICARDO PALMA', 'AV. RICARDO PALMA 57' ),
	(  819, 'IE CESAR VALLEJO MENDOZA', 'AV. AYACUCHO S N' ),										-- SAN ANTONIO DE ANTAPARCO
	(  820, 'IE 36228', 'JR. ALEGRIA' ),															-- SANTO TOMAS DE PATA 
	(  821, 'IST LA CANTUTA', 'AV. VALENTIN ANAYA S N' ),											-- SECCLLA
       
-- ---- HUANCAVELICA --- CASTROVIRREYNA
	(  822, 'IE 22051 DOMINGO F. SALDAÑA GUTIERREZ', 'AV. 8 DE DICIEMBRE 116' ),					-- ARMA
    (  823, 'IE CESAR ABRAHAM VALLEJO MENDOZA', 'AV. MANCHEGO MUÑOZ 458' ),							-- AURAHUA
	(  824, 'IE 22011 CAPILLAS', 'JR. BALTA S/N' ),													-- CAPILLAS
	(  825, 'IE SAN ROQUE', 'AV. LOS LIBERTADORES S/N' ),											-- CASTROVIRREYNA
	(  826, 'IE 22019', 'AV. LOS LIBERTADORES' ),													-- CHUPAMARCA
    (  827, 'IE SAN FRANCISCO DE COCAS', 'JR. HUANCAVELICA' ),										-- COCAS
    (  828, 'IE 22009', 'PLAZA PRINCIPAL' ),														-- HUACHOS
    (  828, 'IE SAN CRISTOBAL DE HUACHOS', 'JR. LIBERTAD' ),   
    (  829, 'IE 22026', 'CALLE ESCUELA' ),															-- HUAMATAMBO
    (  830, 'IE 22032', 'PLAZA PRINCIPAL' ),														-- MOLLEPAMPA
    (  831, 'IEP SAN JUAN', 'AV. ASUNCION 205' ),													-- SAN JUAN 
    (  832, 'IE 22 DE MAYO', 'JR. 22 DE MAYO' ),													-- SANTA ANA
    (  833, 'IE FRANCISCO BOLOGNESI', 'AV. EL ANGEL 102' ),											-- TANTARA
    (  834, 'IE LOS LIBERTADORES', 'CALLE SAN JOSE' ),												-- TICRAPO
         
 -- ---- HUANCAVELICA --- CHURCAMPA
	(  835, 'IE 30978 JOSE ANTONIO ENCINAS', 'JR. SANTA ROSA' ),									-- ANCO
    (  835, 'IE 31116 ROSA DE AMERICA', 'JR. PROGRESO' ),
    (  835, 'IE LA ESMERALDA', 'AV. AYACUCHO' ),
    (  835, 'PABLO BACILIO AUQUI', 'CUYUCC CHINCHAYPAMPA' ),
    (  836, 'IE 30948 VICTOR SANCHEZ TUEROS', 'JR. NIÑO JESUS' ),									-- CHINCHIHUASI
    (  837, 'IE 30981 SAN LUIS GONZAGA', 'AV. LA CULTURA 292' ),									-- CHURCAMPA
    (  838, 'IE 30979 COSME', 'PLAZA PRINCIPAL' ),													-- COSME
    (  839, 'IE 30985', 'JR. 28 DE JULIO S/N' ),													-- EL CARMEN
    (  840, 'IE 30987 NUESTRA SEÑORA DE LAS MERCEDES', 'AV. ALEJANDRO VILLENA' ),					-- LA MERCED
    (  841, 'IE LEONCIO PRADO', 'PLAZA PRINCIPAL' ),												-- LOCROJA
    (  841, 'IEP 30989 JESUS DE NAZARETH', 'JR. 28 DE JULIO' ),
    (  842, 'IE JOSE MARIA ARGUEDAS', 'CARRETERA A TEXAS' ),										-- PACHAMARCA
    (  843, 'IE 30958 SEÑOR DE LA AGONIA', 'JR. AMANCIO BUSTAMANTE RIVICHAGUA' ),					-- PAUCARBAMBA
    (  844, 'IE SAN MIGUEL', 'JR. LIMA' ),															-- SAN MIGUEL DE MAYOCC
    (  845, 'IE JAVIER HERAUD', 'AV. CAJAMARCA 701' ),												-- SAN PEDRO DE CORIS
         
 -- ---- HUANCAVELICA --- HUANCAVELICA
	(  846, 'IE 36033', 'CALLE REAL' ),																-- ACOBAMBILLA
    (  846, 'IE 36034', 'AV. UNION' ),
    (  846, 'IE 36035', 'JR. 28 DE JULIO' ),
    (  846, 'IE SAN JOSE DE ACOBAMBILLA', 'AV. VISTA ALEGRE' ),
    (  847, 'IE 36013', 'PLAZA SAN LORENZO 412' ),													-- ACORIA
    (  847, 'IE 36013 ANEXO B', 'JR. INCA GARCILAZO DE LA VEGA 212' ),
    (  847, 'IE 36015 VIRGEN NATIVIDAD', 'AV. REAL' ),
    (  847, 'IE 36018', 'PRLG PLAZA PRINCIPAL 28 DE JULIO CCACCASIRI' ),
    (  847, 'IE 36067', 'JR. SAN JUAN' ),
    (  847, 'IE 36070', 'BARRIO CAMINOS' ),
    (  847, 'IE 36074', 'AV. 28 DE JULIO' ),
    (  847, 'IE 36083', 'PLAZA PRINCIPAL' ),
    (  847, 'IE 36292', 'PLAZA PRINCIPAL' ),
	(  847, 'IE 36311', 'PLAZA PRINCIPAL' ),
    (  847, 'IE 36314', 'PLAZA PRINCIPAL' ),
    (  847, 'IE 36364', 'PLAZA PRINCIPAL' ),
    (  847, 'IE 36471 PATOCCOCHA', 'PLAZA PRINCIPAL' ),
    (  847, 'IE 36594', 'PLAZA PRINCIPAL' ),
    (  847, 'IE SECUNDARIA LOS ANGELES DE CCARAHUASA', 'CARRETERA A ACORIA (frente del cementerio)' ),
    (  847, 'IE SIMON BOLIVAR PALACIOS', 'PLAZA PRINCIPAL SN' ),
    (  848, 'IE AMERICA', 'AV. SANTOS VILLA 1005' ),												-- ASCENSION
    (  849, 'IE 36040', 'PLAZA PRINCIPAL' ),														-- CONAYCA
    (  850, 'IE 36044', 'AV. 28 DE JULIO SN' ),														-- CUENCA	
    (  850, 'IE INDOAMERICA', 'CALLE ALFONSO UGARTE' ),
    (  851, 'IE RICARDO PALMA SORIANO', 'AV. PORVENIR' ),											-- HUACHOCOLPA
    (  852, 'IE 36002', 'JR. FRANCISCO ANGULO' ),													-- HUANCAVELICA
    (  852, 'IE 36009 MOISES ORDAYA ALIAGA', 'JR. TAMBO DE MORA 294' ),
    (  852, 'IE 37001', 'JR. MANCO CAPAC 519' ),
    (  852, 'IE FRANCISCA DIEZ CANSECO DE CASTILLA', 'PSJ. CADENILLAS' ),
    (  852, 'IE LA VICTORIA DE AYACUCHO', 'AV. HILDAURO CASTRO' ),
    (  852, 'IE MUJERES MICAELA BASTIDAS PUYUCAHUA', 'JR. CASTROVIRREYNA' ),
    (  852, 'IE TERESA DE LA CRUZ', 'JR. NICOLAS DE PIEROLA 603' ),
    (  852, 'IST PEDAGOGICO HUANCAVELICA', 'JR. CHURCAMPA' ),
    (  853, 'IE 36022 HUANDO', 'AV. HUANCAYO 534' ),												-- HUANDO
    (  853, 'IE MX FRANCISCO BOLOGNESI', 'CCPP TINYACCLLA' ),
    (  854, 'IE SAN FRANCISCO', 'CALLE PROGRESO' ),													-- HUAYLLAHUARA
    (  855, 'IE MANUEL ASCENCIO SEGURA', 'AV. ANDRES AVELINO CACERES 485' ),						-- IZCUCHACA
    (  856, 'IE 36048', 'CALLE 28 DE JULIO' ),														-- LARIA
    (  857, 'IE 36024', 'CALLE REAL S N' ),															-- MANTA
    (  858, 'IE 36049', 'CALLE NICANOR RUIZ ESPONDA' ),												-- MARISCAL CACERES
    (  859, 'IE SAN MIGUEL', 'AV. HUANCAVELICA' ),													-- MOYA
    (  860, 'IE 36027', 'JR. 4 DE OCTUBRE Y JR. DIEZ DE MAYO' ),									-- NUEVO OCCORO
    (  860, 'IE 36097 TANSIRI', 'PLAZA PRINCIPAL' ),
    (  860, 'IE 36101', 'CCPP TAMBOPATA' ),
    (  861, 'IE 36029', 'CALLE PORVENIR' ),															-- PALCA
    (  862, 'IE 36054', 'PLAZA PRINCIPAL SN' ),														-- PILCHACA
	(  863, 'IE 36056', 'JR. SAN JUAN BAUTISTA' ),													-- VILCA
	(  863, 'IE JOSE CARLOS MARIATEGUI', 'CCPP HUANCALPI' ),
	(  864, 'IE 36036', 'PLAZA PRINCIPAL' ),														-- YAULI
	(  864, 'IE 36293 SAN JUAN DE CCARHUACC', 'PLAZA PRINCIPAL' ), 
    (  864, 'IE 36303 JOSE CARLOS MARIATEGUI', 'AV. 28 DE JULIO' ),
	(  864, 'IE 36319', 'AV. JUAN VELAZCO ALVARADO' ),
    (  864, 'IE SAN MARTIN DE PORRES', 'JR. SAN MARTIN DE PORRES PLAZA PRINCIPAL' ),

-- ---- HUANCAVELICA --- HUAYTARA
	(  865, 'I.E 22569 NIÑO JESUS DE AYAVI', 'AV. LOS LIBERTADORES' ),								-- AYAVI
    (  866, 'IE CESAR VALLEJO', 'CALLE MUNICIPALIDAD 22' ),											-- CORDOVA
    (  867, 'IE 22029', 'CALLE CORAZON DE JESUS' ),													-- HUAYACUNDO ARMA
    (  868, 'IE 22023 SAN JUAN BAUTISTA', 'AV. EL SOL' ),											-- HUAYTARA
    (  869, 'IE LARAMARCA', 'PSJE: SAHUACHA S/N' ),													-- LARAMARCA
    (  870, 'IE CELESTINO MANCHEGO MUÑOZ', 'AV. HUANCAVELICA S/N' ),								-- OCOYO
    (  870, 'IE SECUNDARIA PACOMARCA', 'VISTA ALEGRE' ),
    (  871, 'IE 22033', 'AV. LOS LIBERTADORES' ),													-- PILPICHACA
    (  871, 'IE INGAHUASI', 'CALLE PRINCIPAL' ),
    (  871, 'IE TECNICO AGROPECUARIO ARTESANAL', 'CALLE PRINCIPAL S/N' ), 
    (  872, 'IE SAN FRANCISCO DE ASIS', 'CALLE CARMEN ALTO' ),										-- QUERCO
    (  873, 'IE ELODORO BELLIDO BRAVO', 'AV. MUNICIPALIDAD' ),										-- QUITO ARMA
    (  874, 'IE JOSE MARIA ARGUEDAS', 'AV. PERU' ),													-- SAN ANTONIO DE CUSICANCHA
    (  875, 'IE 22169 SAN FRANCISCO', 'AV. LOS PROCERES' ),											-- SAN FRANCISCO DE SANGAYAICO
    (  876, 'IEP LIBERTADOR SIMON BOLIVAR', 'AV. CARRETERA YERBABUENAYOCC S/N' ),					-- SAN ISIDRO
    (  877, 'IE 22164', 'AV. SAN FELIPE' ),															-- SANTIAGO DE CHOCORVOS
    (  878, 'IE FELIPE SANTIAGO DE QUIRAHUARA', 'PANTEON PAMPA' ),									-- SANTIAGO DE QUIRAHUARA
    (  879, 'IE JOSE CARLOS MARIATEGUI', 'JR. JOSE CARLOS MARIATEGUI' ),							-- SANTO DOMINGO DE CAPILLAS
    (  880, 'IE 22048', 'AV. ALAMEDA' ),															-- TAMBO

-- ---- HUANCAVELICA --- TAYACAJA
	(  881, 'IE NUESTRA SEÑORA DE LA ASUNCION', 'CARRETERA CENTRAL' ),								-- ACOSTAMBO
    (  882, 'IE JOSE MARIA ARGUEDAS ALTAMIRANO', 'JR. ALFONSO UGARTE' ),							-- ACRAQUIA
    (  883, 'IE 31369', 'PLAZA PRINCIPAL' ),														-- AHUAYCHA
    (  883, 'IE MI PERU', 'A MEDIA CDRA. DE LA PLAZA DE AHUAYCHA' ),
    (  883, 'IE SAN MIGUEL DE HUALLHUA', 'JR. MANUEL DE LA TORRE' ),
    (  884, 'IE AUGUSTO SALAVERRY', 'CALLE CARRETERA CENTRAL' ),									-- ANDAYMARCA
    (  885, 'IE 30943 SAN MARTIN DE PORRAS', 'AV. CENTENARIO' ),									-- COLCABAMBA
    (  885, 'IE 30944', 'JR. SAN MARTIN S/N' ),
    (  885, 'IE 30945', 'CALLE VIRGEN DEL CARMEN S/N' ),
    (  885, 'IE 30946', 'CALLE BOLIVAR S/N' ),
    (  885, 'IE 31028', 'PLAZA PRINCIPAL' ),
    (  885, 'IE 31036 OCORO', 'BARRIO FLORIDA' ),
    (  885, 'IE SANTIAGO ANTUNEZ DE MAYOLO', 'PASAJE SAN JUAN XXIII' ),
    (  886, 'IE MARISCAL CACERES', 'JR. JOSE OLAYA SN' ),											-- DANIEL HERNANDEZ
    (  887, 'COLEGIO SANTA ROSA', 'AV. AUGUSTO HINOSTROZA SN' ),									-- HUACHOCOLPA
    (  888, 'IE 30952', 'AV. HUANCAVELICA' ),														-- HUARIBAMBA
    (  888, 'IE 30954', 'AV. DE AGOSTO S/N' ),
    (  888, 'IE 31059', 'CARRETERA HUAYARQUI S/N' ),
	(  889, 'IE 30956', 'JR. PUMACAHUA SN' ),														-- ÑAHUIMPUQUIO
    (  890, 'IE 30999 MARISCAL CACERES', 'AV. HUANCAYO S N' ),										-- PAMPAS
    (  890, 'IE 31521 JESUS OSPINA DIAZ', 'AV. CENTENARIO CUADRA 2 S/N' ),
    (  890, 'IE 36428 ABRAHAM VALDELOMAR', 'CARRETERA HUANCAYO-AYACUCHO KM 90' ),
    (  890, 'IE CASAY', 'PLAZA PRINCIPAL DE AHUAYCHA CASAY' ),
    (  891, 'IE 30961 PAZOS', 'PLAZA PRINCIPAL' ),													-- PAZOS
    (  892, 'CEN 31367', 'PIE DE CARRETERA' ),														-- QUICHUAS
    (  892, 'IE 31315 SANTA ROSA DE MALLMA', 'SANTA ROSA DE MALLMA' ),
    (  892, 'IE 31330', 'AV. JUAN VELASCO ALVARADO' ),
    (  892, 'IE MARISCAL CASTILLA', 'CCPP COLCA' ),
    (  892, 'IE MICAELA BASTIDAS PUYUCAHUA', 'CALLE TARAPACA S/N' ),
    (  893, 'IE 30964 QUISHUAR', 'AV. MARISCAL CASTILLA' ),											-- QUISHUAR
    (  894, 'IE 30968 ENRIQUE AVILA SANTIVAÑEZ', 'PLAZA PRINCIPAL S/N' ),							-- SALCABAMBA
    (  894, 'IE JORGE BASADRE GROMMAN', 'CARRETERA PRINCIPAL AYACCOCHA' ),
    (  895, 'IE DANIEL ALCIDES CARRION', 'CALLE DANIEL ALCIDES CARRION' ),							-- SALCAHUASI
    (  896, 'IE 7 DE JUNIO', 'AV. HUANCAYO' ),														-- SAN MARCOS DE ROCCHAC
    (  897, 'IE SAN PEDRO', 'AV. SAN PEDRO' ),														-- SURCUBAMBA
    (  898, 'IE 31110', 'JR. SANTA ROSA SN' )														-- TINTAY PUNCU