use Onpe;
insert LocalVotacion(idDistrito, RazonSocial, Direccion) values

-- ---- HUANUCO --- AMBO  
	(  899, 'IE 32133', 'JR. CARMEN ALTO 187' ),													-- AMBO
	(  899, 'IE INTEGRADO JULIO BENAVIDES SANGUINETTI', 'AV. MARISCAL CASTILLA N 378' ),
    (  900, 'IE 32173 UTCUSH', 'CCPP UTCUSH' ),														-- CAYNA
	(  900, 'IE FERNANDO BELAUNDE TERRY', 'CCPP QUIO' ),
    (  900, 'IE INTEGRADA MANUEL GONZALES PRADA', 'JR. MARISCAL CASTILLA S/N' ),
    (  901, 'IE INTEGRAL JOSE ANTONIO ENCINAS FRANCO', 'BARRIO PAMPAVERDE' ),						-- COLPAS
	(  901, 'IE SAN JUAN DE COLPAS', 'ESTADIO HUANTAR' ),
    (  902, 'IE 32149 SAN ANTONIO ÑAUZA', 'SECTOR DE SHALLA' ),										-- CONCHAMARCA
	(  902, 'IE INTEGRADO SAN LORENZO DE CONCHAMARCA', 'JR. TARATA S/N' ),
    (  903, 'IE 32150 HUACAR', 'JR. BOLOGNESI 106' ),												-- HUACAR
	(  903, 'IE 32181 MOSCATUNA', 'CCPP MOSCATUNA' ),
    (  903, 'IE 32183 CESAR VALLEJO INICIAL', 'CCPP SAN PEDRO DE ACOBAMBA' ),
    (  903, 'IE 59 DE HUACAR', 'JR. 28 DE JULIO S/N' ),
    (  903, 'IE AGROPECUARIO GREGORIO CARTAGENA', 'JR. COMERCIO S/N PLAZA DE ARMAS' ),
    (  903, 'IE SIMON BOLIVAR DE ANGASMARCA', 'CCPP ANGASMARCA' ),
    (  904, 'IE 32188 DANIEL ALOMIA ROBLES', 'CCPP SAN ANTONIO DE QUIRCAN' ),						-- SAN FRANCISCO
	(  904, 'IE HERMILIO VALDIZAN', 'JR. HERMILIO VALDIZAN S/N' ),
    (  904, 'IE LEONCIO PRADO - RODEO', 'CCPP TRES DE MAYO DE RODEO' ),
    (  905, 'IE 32159 DIVINO MAESTRO', 'JR. CRESPO CASTILLO S/N' ),									-- SAN RAFAEL
	(  905, 'IE 32199 INTEGRADA', 'CCPP ACOBAMBA' ),
    (  905, 'IE 32732', 'CCPP AYANCOCHA ALTA' ),
    (  905, 'IE VICTOR RAUL HAYA DE LA TORRE', 'PLAZA DE ARMAS' ),
    (  906, 'IE RICARDO FLORES GUTIERREZ', 'ALAMEDA GARCILAZO DE LA VEGA' ),						-- TOMAY KICHWA

-- ---- HUANUCO --- DOS DE MAYO
    (  907, 'IE 32224 CHUQUIS', 'JR. UNION' ),														-- CHUQUIS
    (  908, 'IE YAROWILCA', 'JR. ESPAÑA' ),															-- LA UNION
    (  909, 'IE 32310', 'JR. LAS ORQUIDEAS' ),														-- MARIAS
    (  909, 'IE 32311 JOSE CARLOS MARIATEGUI', 'CALLE JUAN GAGALSO S/N' ),
    (  909, 'IE COLEGIO NACIONAL INTEGRADO PATAY RONDOS', 'CALLE VICTOR DURAN' ),
    (  909, 'IEP DE MARIAS', 'JR. PROGRESO' ),
    (  910, 'IEP AUGUSTO CARDICH LOARTE', 'AV. CARRETERA CENTRAL' ),								-- PACHAS
    (  911, 'IE COLEGIO NACIONAL DE QUIVILLA', 'AV. CARRETERA CENTRAL 1101' ),						-- QUIVILLA
    (  912, 'IE VIRGEN DEL CARMEN RIPAN', 'JR. SAN ANTONIO' ),										-- RIPAN
    (  913, 'IEP JOSE MARIA ARGUEDAS', 'AV. JOAQUIN MIRAVAL AQUINO' ),								-- SHUNQUI
    (  914, 'IEP DE SILLAPATA', 'JR. IZCUCHATA' ),													-- SILLAPATA
    (  915, 'IEP NUESTRA SEÑORA DEL CARMEN', 'JR. INDEPENDIENCIA' ),								-- YANAS

-- ---- HUANUCO --- HUACAYBAMBA
	(  916, 'IE LEONCIO PRADO', 'AV. LEONCIO PRADO' ),												-- CANCHABAMBA
    (  917, 'IE JOSE CARLOS MARIATEGUI', 'JR. HUANUCO' ),											-- COCHABAMBA
    (  918, 'IE 33230 HUACAYBAMBA', 'AV. EL EJERCITO' ),											-- HUACAYBAMBA
    (  919, 'IE 297', 'JR. CARMEN' ),																-- PINRA
    (  919, 'IE 33353 VIRGEN DEL CARMEN', 'JR. TINYASH' ),
    (  919, 'IE HERMILIO VALDIZAN MEDRANO', 'CCPP CAJAN' ),
    (  919, 'IE INTEGRADO CESAR VALLEJO', 'AV. CESAR VALLEJO SN' ),

-- ----HUANUCO---HUAMALIES
	(  920, 'IE 32731', 'BELLA AURORA' ),															-- ARANCAY
    (  920, 'IE ULDARICO VIDAL SAN MARTIN', 'JR. DANIEL ALCIDES CARRION' ),
    (  921, 'IE CHAVIN DE PARIARCA', 'JR. AMARILIS' ),												-- CHAVIN DE PARIARCA
    (  922, 'IE 32400', 'CALLE PLAZA PRINCIPAL SN' ),												-- JACAS GRANDE
    (  923, 'IE 32403 INTEGRADA', 'JR. SAN ANTONIO' ),												-- JIRCAN
    (  924, 'IE 32384 CESAR VERGARA TELLO', 'JR. SAN MARTIN 549' ),									-- LLATA
    (  924, 'IE INDUSTRIAL JAPON', 'JR. JORGE CHAVEZ 167' ),
    (  925, 'IE REPUBLICA DE CANADA- MIRAFLORES', 'JR. SUCRE 164' ),								-- MIRAFLORES
    (  926, 'IE CARLOS ISMAEL NORIEGA JIMENEZ', 'CARRETERA TINGO MARIA MONZON KM 36.5' ),			-- MONZON
    (  926, 'IE INTEGRADO ANTONIO RAIMONDI', 'JR. GONZALES PRADA' ),
    (  926, 'IE JAVIER PEREZ DE CUELLAR', 'BARRIO PASHI' ),
    (  926, 'IE JAVIER PULGAR VIDAL - PALO DE ACERO', 'CCPP PALO DE ACERO' ),
    (  927, 'IE 32412', 'CALLE MARCELINO NIETO OCHOA' ),											-- PUHANCO
    (  928, 'IE 32414', 'JR. ESTUDIANTES' ),														-- PUÑOS
    (  929, 'IE 32417', 'PRLG LEONCIO PRADO' ),														-- SINGA
    (  930, 'IE SECUNDARIA TANTAMAYO', 'JR. SANTA ROSA' ),											-- TANTAMAYO

-- ---- HUANUCO --- HUANUCO
	(  931, 'IE 32005 ESTEBAN PAVLETICH', 'VIA REGIONAL KM 1.5 LLICUA BAJA' ),						-- AMARILIS
    (  931, 'IE 32043 SAN JOSE DE PAUCAR', 'JR. 15 DE AGOSTO SN' ),
    (  931, 'IE 32126', 'JR. 15 DE AGOSTO MZ. H LT. 03' ),
    (  931, 'IE 32223 MARIANO DAMASO BERAUN', 'JR. MACCHU PICCHU S/N - PAUCARBAMBA' ),
    (  931, 'IE 32962 ROSULO SOTO CARRILLO', 'JR. JIRISHANCA MZ B LT 6 - SECTOR 1' ),
    (  931, 'IE CESAR VALLEJO', 'MALECON LOS INCAS' ),
    (  931, 'IE EL AMAUTA JOSE CARLOS MARIATEGUI', 'AV. LOS GIRASOLES PAUCARBAMBILLA' ),
    (  931, 'IE JULIO ARMANDO RUIZ VASQUEZ', 'JR. JULIO CENTELLO 300' ),
    (  931, 'IE MARCOS DURAN MARTEL', 'AV. MARCOS DURAN MARTEL S/N' ),
    (  931, 'IE MARISCAL CACERES', 'JR. RIMAC 210 SECTOR 3 PAUCARBAMBA 210' ),
    (  931, 'IST MARCOS DURAN MARTEL', 'AV. MARCOS DURAN MARTEL NRO 200 200' ),
    (  932, 'IE 32055', 'CCPP PUENTE DURAND SN' ),													-- CHINCHAO
    (  932, 'IE 32066 DE SAN JOSE DE HUAMPANI', 'CCPP SANTA ISABEL SN' ),
    (  932, 'IE 33386', 'CCPP HUANIPAMPA SN' ),
    (  932, 'IE HORACIO ZEBALLOS GAMEZ', 'JR. SANTA ROSA SN PILLAO' ),
    (  932, 'IE NUESTRA SEÑORA DE LOURDES', 'JR. SAN PEDRO SN' ),
    (  933, 'IE 32075 INTEGRADA TAMBOGAN', 'JR. PLAZA DE ARMAS SN TAMBOGAN' ),						-- CHURUBAMBA
    (  933, 'IE JAVIER PULGAR VIDAL', 'JR. CATALINA HUANCA SN' ),
    (  933, 'IE MICAELA BASTIDAS', 'COMUNIDAD LAS PALMERAS SN' ),
    (  934, 'IE 32002 VIRGEN DEL CARMEN', 'JR. 28 DE JULIO NRO 1617' ),								-- HUANUCO
    (  934, 'IE 32004 SAN PEDRO', 'PRLG AYANCOCHA 235' ),
    (  934, 'IE 32011 HERMILIO VALDIZAN', 'JR. ABTAO 1060' ),
    (  934, 'IE GRAN UNIDAD ESCOLAR LEONCIO PRADO', 'JR. GENERAL PRADO 411' ),
    (  934, 'IE ILLATHUPA', 'JR. CRESPO Y CASTILLO CDRA. 1' ),
    (  934, 'IE INDUSTRIAL HERMILIO VALDIZAN', 'AV. MALECON CENTENARIO LEONCIO PRADO 287' ),
    (  934, 'IE JUANA MORENO', 'JR. CRESPO Y CASTILLO NRO 789' ),
    (  934, 'IE MILAGRO DE FATIMA', 'JR. HUALLAYCO NRO 169' ),
    (  934, 'IE PEDRO SANCHEZ GAVIDIA', 'JR. TARMA CDRA 2' ),
    (  935, 'IE 32025', 'AV. JUAN DURAND 1050' ),													-- MARGOS
    (  936, 'IE JUAN VELASCO ALVARADO', 'AV.UNIVERSITARIA KM 3 CARRETERA CENTRAL HUÁNUCO LIMA' ),	-- PILLCO MARCA
    (  936, 'IEP ANDRÉS FERNÁNDEZ GARRIDO', 'AV.UNIVERSITRIA KM 3.5 CARRETERA CENTRAL HUÁNUCO LIMA' ),
    (  937, 'IE INTEGRADO SAN PEDRO DE CANI', 'CC PP SAN PEDRO DE CANI' ),							-- QUISQUI
    (  937, 'IE JUAN JOSE CRESPO Y CASTILLO', 'KM 22 CARRETERA CENTRAL LA UNION' ),
    (  938, 'IE GABRIEL AGUILAR NARVARTE', 'JR. SAN PEDRO' ),										-- SAN FRANCISCO DE CAYRAN
    (  939, 'IE 32108', 'JR. SAN SEBASTIAN' ),														-- SAN PEDRO DE CHAULAN
    (  939, 'IE 32115', 'ENTRADA AL CC PP LIBERACION DE YAURAN - LADO DERECHO' ),
    (  939, 'IE 32117', 'JR. ANDAHUAYLAS S/N' ),
    (  939, 'IE 32118', 'CCPP SAN JUAN DE LA LIBERTAD' ),
    (  939, 'IE 32121', 'JR. 28 DE JULIO' ),
    (  939, 'IE TUPAC AMARU II', 'JR. CHAULAN' ),
    (  940, 'IE 32039 SAN SEBASTIAN DE QUERA', 'CALLE SAN SEBASTIAN' ),								-- SANTA MARIA DEL VALLE
    (  940, 'IE 32124 COLEGIO INTEGRADO PACHABAMBA NRO', 'PLAZA PRINCIPAL' ),
    (  940, 'IE 32127 INTEGRADO SANTIAGO DE LLACON', 'JR. SAN MARTIN' ),
    (  940, 'IE 32743 SANTA ROSA DE LIMA', 'JR. SAN ANTONIO' ),
    (  940, 'IE COLEGIO NACIONAL INTEGRADO POMACUCHO', 'PLAZA PRINICPAL' ),
    (  940, 'IE JORGE BASADRE PRIMARIA', 'JR. LIBERTAD' ),
    (  940, 'IE JORGE BASADRE SECUNDARIA', 'AV. LA REPUBLICA CDRA 5' ),
    (  940, 'IE NIÑO JESUS DE PRAGA', 'JR. HUANUCO 100' ),
    (  941, 'IE DANIEL ALOMIA ROBLES', 'R. PIURA SN - YACUS' ),										-- YACUS
    (  942, 'IE ANDRES AVELINO CACERES', 'JR. LIBERTAD' ),											-- YARUMAYO
 
-- ---- HUANUCO --- LAURICOCHA
	(  943, 'IE 32256', 'JR. MARAÑON' ),															-- BAÑOS
    (  944, 'IE JOSE VARALLANOS', 'JR. LOS INCAS SN' ),												-- JESUS                                                                        
    (  945, 'IE COLEGIO NACIONAL INTEGRADO PEDRO ARBUES BERNARDO PEÑA', 'JR. MARAÑON' ),			-- JIVIA
    (  946, 'IE COLEGIO NACIONAL INTEGRADO DE QUEROPALCA', 'JR. DOS DE MAYO' ),						-- QUEROPALCA
    (  947, 'IE 32272', 'JR. HUALLAYCO' ),															-- RONDOS
    (  948, 'IE 32279 HUARIN', 'JR. SAN FRANCISCO DE ASIS 222' ),									-- SAN FRANCISCO DE ASIS
    (  949, 'IE COLEGIO NACIONAL INTEGRADO ANTACOLPA', 'CALLE' ),									-- SAN MIGUEL DE CAURI
    (  949, 'IE FILOTHER MENDOZA CAMPOS', 'JR. LEONCIO PRADO' ),

-- ---- HUANUCO --- LEONCIO PRADO
	(  950, 'IE PUMAHUASI', 'AV. FEDERICO BASADRE KM 15' ),											-- DANIEL ALOMIA ROBLES
    (  951, 'IE SAN ISIDRO', 'AV. FEDERICO BASADRE KM 32' ),										-- HERMILIO VALDIZAN
    (  952, 'IE HANS VICTOR LANGEMAK MICHELSEN', 'PSJ. LOS PROCERES 150' ),							-- JOSE CRESPO Y CASTILLO
    (  952, 'IE INCA HUIRACOCHA', 'AV. LAS AMERICAS MANZANA Q' ),
    (  953, 'IE 32508 VICTOR REYES ROCA', 'AV. LOS JARDINES' ),										-- LUYANDO
    (  953, 'IST INSTITUTO SUPERIOR TECNOLOGICO NARANJILLO', 'PSJ. CARMEN SN MZ 18 LT 01' ),
    (  954, 'IE AGROPECUARIO LAS PALMAS', 'AV. CARRETERA FERNANDO BELAUNDE TERRY KM 17' ),			-- MARIANO DAMASO BERAUN
    (  954, 'IE MARIANO DAMASO BERAUN', 'AV. CARRETERA FERNANDO BELAUNDE TERRY KM 12' ),
    (  955, 'IE 32262 LEONCIO PRADO GUTIERREZ', 'AV. ALAMEDA PERU 720' ),							-- RUPA-RUPA
    (  955, 'IE 32483 RICARDO PALMA', 'AV. LA BANDERA 292' ),
    (  955, 'IE CESAR VALLEJO', 'AV. IQUITOS S/N' ),
    (  955, 'IE INTEGRADO RAMON CASTILLA', 'JR. TARAPACA 133' ),
    (  955, 'IE MARIANO BONIN', 'JR. JULIO BURGA CUADRA 3' ),
    (  955, 'IE PADRE ABAD', 'JR. UCAYALI CUADRA 4' ),
    (  955, 'UNIVERSIDAD AGRARIA DE LA SELVA', 'AV. UNIVERSITARIA KM 15' ),

-- ---- HUANUCO --- MARAÑON
	(  956, 'IE 33432 ANTONIO KETIN VIDAL HERRERA', 'CCPP SANTA ROSA DE ALTO YANAJANCA' ),			-- CHOLON
    (  956, 'IE 84056 ESCUELA PRIMARIA DE MENORES', 'AV. CHONTAYACU S/N' ),
    (  956, 'IE 84284 COLEGIO INTEGRADO SAGRADO CORAZON DE JESUS', 'CCPP SAN ANTONIO DE PADUA' ),
    (  956, 'IE ANTONIO RAYMONDI', 'JR. LOS CONQUISTADORES' ),
    (  956, 'IE JOSE ANTONIO ENCINAS FRANCO - PRIMARIA', 'AV. LAS PALMAS' ),
    (  957, 'COLEGIO INTEGRADO', 'CCPP HUAYCHAO' ),													-- HUACRACHUCO
    (  957, 'IE INICIAL 176', 'CCPP HUACHUMAY' ),
    (  957, 'IE HUAYNA CAPAC', 'AV. 28 DE JULIO 830' ),
    (  957, 'IE INICIAL 128', 'CARRETERA CCPP CHINCHIL' ),
    (  957, 'IE INICIAL 235', 'CCPP HUANCHAY' ),
    (  958, 'IE HORACIO ZEVALLOS GOMEZ', 'BARRIO ALTO' ),											-- SAN BUENAVENTURA
    (  958, 'IE 84068 ESCUELA PRIMARIA', 'BARRIO BUENOS AIRES' ),
    (  958, 'IE PRIMARIA - JOSE JAIME HEREDIA NEYRA', 'CCPP VILLAMAR' ),

-- ---- HUANUCO --- PACHITEA
	(  959, 'IE 32581 CHAGLLA', 'BARRIO SAN LUIS' ),												-- CHAGLLA
    (  959, 'IE 32612', 'CCPP PUERTO GUADALUPE' ),
    (  959, 'IE 32616 PAMPAMARCA', 'JR. LEONCIO PRADO' ),
    (  959, 'IE 32716 CHINCHAVITO', 'CCPP MENOR DE CHINCHAVITO' ),
    (  960, 'IE 32587 MOLINO PRIMARIA', 'JR. TOMAS CANTARO 409' ),									-- MOLINO
    (  960, 'IE CARLOS IVAN DEGREGORI CASO', 'JR. BARRIO AUCHI' ),
    (  961, 'IE 32594', 'CALLE YURAGMARKA' ),														-- PANAO
    (  961, 'IE 32737 SANTA VIRGINIA', 'CALLE SANTA VIRGINIA' ),
    (  961, 'IE 32575', 'JR. MAYRO 1002' ),
    (  961, 'IE TUPAC AMARU II DE PANAO', 'JR. LIMA CUADRA 9' ),
    (  962, 'IE LA PUNTA', 'KM 255 CARRETERA RANCHO - PANAO (ALTURA DEL CENTRO CIVICO)' ),			-- UMARI
    (  962, 'IE LEONCIO PRADO GUTIERREZ', 'LA CALLE 2 TAMBILLO' ),

-- ---- HUANUCO --- PUERTO INCA
	(  963, 'IE 33412', 'PRLG POZUZO' ),															-- CODO DEL POZUZO
    (  964, 'IE 64315 INTEGRADO NUEVA HONORIA', 'JR. JUAN VELASCO ALVARADO S/N' ),					-- HONORIA
    (  965, 'IE 32969 INTEGRADO PUERTO SUNGARO', 'JR. FERNANDO BELAUNDE TERRY KM 64' ),				-- PUERTO INCA
    (  965, 'IE 64329 PRIMARIA', 'AV. SANCHEZ CERRO' ),
    (  965, 'IE LUIS BENJAMIN CISNEROS', 'JR. VULCANO' ),
    (  966, 'IE 64349 INTEGRADO TOURNAVISTA', 'PSJ. FELIPE TINOCO CALDERON' ),						-- TOURNAVISTA
    (  966, 'IE JAIME TSENG', 'AV. CARRETERA FERNANDO BELAUNDE KM 12' ),
    (  967, 'IE 64330 AUGUSTO DURAND', 'AV. PASEO DE LA REPUBLICA SN' ),							-- YUYAPICHIS

-- ---- HUANUCO --- YAROWILCA
	(  968, 'IE 32219 DANIEL ALOMIA ROBLES', 'JR. SANTA ANA' ),										-- APARICIO POMARES
    (  969, 'IE 32211 JOSE CARLOS MARIATEGUI', 'JR. LIMA' ),										-- CAHUAC
    (  970, 'IE CHACABAMBA', 'JR. 3 DE OCTUBRE' ),													-- CHACABAMBA
    (  971, 'IE 32213 ANDRES AVELINO CACERES', 'JR. SAN JUAN' ),									-- CHAVINILLO
    (  971, 'IE ESTEBAN PAVLETICH TRUJILLO', 'JR. 14 DE SETIEMBRE' ),
    (  972, 'IE INTEGRADA GARU', 'JR. HUAMAN POMA DE AYALA' ),										-- CHORAS
    (  973, 'IE VICTOR RAUL HAYA DE LA TORRE', 'CARRETERA HUANUCO - LA UNION' ),					-- JACAS CHICO
    (  974, 'IE PUBLICA INTEGRADA HIPOLITO UNANUE', 'JR. AYACUCHO' ),								-- OBAS
    (  975, 'IE PUBLICA SAN LUCAS', 'SALIDA A LA CARRETERA A LA CIUDAD DE LA UNION' )				-- PAMPAMARCA