use Onpe;
insert LocalVotacion(idDistrito, RazonSocial, Direccion) values

-- ---- ICA --- CHINCHA														
	(  976, 'IE CIRO ALEGRIA', 'CALLE SIMON BOLIVAR 121' ),	                                        -- ALTO LARAN
    (  977, 'IE 22273', 'JR. SAN MARTIN' ),														    -- CHAVIN
	(  978, 'IE 23001 SEBASTIAN BARRANCA', 'AV. AMERICA 115' ),                                     -- CHINCHA ALTA
    (  978, 'IE ANDRES AVELINO CACERES', 'JR. LUIS MASSARO 230' ),
    (  978, 'IE CHINCHAYSUYO', 'PROLONGACION SANTOS NAGARO N° 690' ),
    (  978, 'IE JOSE PARDO Y BARREDA PRIMARIA', 'AV. LUIS GALVEZ CHIPOCO 273' ),
    (  978, 'IE JOSE PARDO Y BARREDA SECUNDARIA', 'AV. LUIS GALVEZ CHIPOCO 271' ),
    (  978, 'IE PUBLICA JOHN F. KENNEDY', 'AV. MARISCAL CASTILLA 300' ),
    (  978, 'IE SANTA ANA', 'AV. ALFONSO UGARTE S/N' ),
    (  979, 'IE 22247 JUAN XXIII', 'AV. ARNALDO ALVARADO S/N' ),									-- CHINCHA BAJA
    (  979, 'IE JUAN C. DE MORA', 'CALLE MORA 114' ),
    (  980, 'IE 22250', 'PRLG CHINCHA 530' ),							                            -- EL CARMEN
    (  980, 'IE NUESTRA SEÑORA DEL CARMEN', 'PRLG CHINHCA S/N' ),
    (  981, 'IE 22252 ANSELMO ABAD DE LA CRUZ', 'AV. CENTENARIO MZ V LT 7' ),                       -- GROCIO PRADO
    (  981, 'IE 22253 JOSE ANTONIO ENCINAS', 'CALLE SAN JUAN 245' ),
    (  981, 'IE MELCHORITA SARAVIA', 'AV. MELCHORITA 400' ),
    (  982, 'IE 22256 SAN ANTONIO DE PADUA', 'AV. VICTOR ANDRES BELAUNDE 453' ),                    -- PUEBLO NUEVO
    (  982, 'IE 22480 JOSE CARLOS MARIATEGUI', 'JR. SEBASTIAN BARRANCA 800' ),
    (  982, 'IE DEPORTIVA JOSE YATACO PACHAS', 'AV. 13 DE OCTUBRE 215' ),
    (  982, 'IEP DOS DE MAYO', 'AV. DOS DE MAYO 194' ),
    (  982, 'IEP HORACIO ZEVALLOS GAMEZ', 'AV. SANTA ROSA' ),
    (  982, 'IST CHINCHA', 'AV. UNION 500' ),  
    (  983, 'IE 22257 PRIMARIA', 'AV. LOS MAESTROS' ),                                              -- SAN JUAN DE YANAC
    (  984, 'IE 22258 LISCAY', 'CALLE HUANCAYO SUR' ),                                              -- SAN PEDRO DE HUACARPANA
    (  984, 'IE 22259 APOSTOL SAN PEDRO', 'JR. PROGRESO 500' ),
    (  984, 'IE 22286 BELLAVISTA', 'CALLE CHINCHA' ),
    (  985, 'IE 22268', 'AV. EMANCIPACIÓN 400' ),													-- SUNAMPE
    (  985, 'IE 257', 'JR. ICA 171' ),
    (  985, 'IE SIMON BOLIVAR', 'AV. MONTERRICO' ),
    (  986, 'IE MIGUEL GRAU SEMINARIO', 'AV. JOSE OLAYA 1086' ),                                    -- TAMBO DE MORA

-- ---- ICA --- ICA
    (  987, 'IE 132', 'CALLE CALLAO 469' ),                                                         -- ICA
    (  987, 'IE 22295', 'AV. TUPAC AMARU 281' ),
    (  987, 'IE 22299 CARLOS CUETO FERNANDINI', 'CALLE BOLIVAR 1096' ),
    (  987, 'IE 22494 JUAN XXIII', 'CALLE LIMA 319' ),
    (  987, 'IE 22495 MICAELA GALINDO DE CACERES', 'CALLE LUIS MEDINA CUADRA 2' ),
    (  987, 'IE 22533 ANTONIA MORENO DE CACERES', 'AV. ORQUIDEAS' ),
    (  987, 'IE 23007 JUDITH AYBAR DE GRANADOS', 'CALLE CALLAO 479' ),
    (  987, 'IE 23008 EZEQUIEL SANCHEZ GUERRERO', 'CALLE CALLAO 424' ),
    (  987, 'IE ABRAHAM VALDELOMAR', 'PRLG ACOMAYO' ),
    (  987, 'IE ANTONIA MORENO DE CACERES', 'AV. CUTERVO' ),
    (  987, 'IE EMBLEMATICA SAN LUIS GONZAGA', 'AV. JOSE MATIAS MANZANILLA 187' ),
    (  987, 'IE JOSE TORIBIO POLO', 'AV. LOS MAESTROS' ),
    (  987, 'IE MARGARITA SANTA ANA DE BENAVIDES', 'CALLE PIURA 347' ),
    (  987, 'IE NUESTRA SEÑORA DE LAS MERCEDES', 'AV. JOSE MATIAS MANZANILLA 446' ),
    (  987, 'IE PNP TEODOSIO FRANCO GARCIA', 'CALLE LA MAR 270' ),
    (  987, 'IST CATALINA BUEN DIA DE PECHO', 'AV. TUPAC AMARU' ),
    (  988, 'IE 22309', 'AV. MICAELA BASTIDAS 345' ),                                               -- LA TINGUIÑA
    (  988, 'IE 22491 MICAELA BASTIDAS PUYUCAWA', 'AV. MADRID 420' ),
    (  988, 'IE DANIEL MERINO RUIZ', 'AV. PARIS  920' ),
    (  989, 'IE 22314 VICENTA AQUIJE', 'AV. ARENALES 121' ),                                        -- LOS AQUIJES
    (  989, 'IE GABRIEL RAMOS', 'AV. ARENALES 112' ),
    (  989, 'IE JOSE GREGORIO HUAMAN GIRAO', 'AV. SEBASTIAN BARRANCA Z-8' ),
    (  990, 'IE 22526 MEDARDO APARCANA HERNANDEZ', 'AV. 22 N°°22' ),                                -- OCUCAJE
    (  991, 'IE 22318', 'AV. JOSE DE LA TORRE UGARTE' ),                                            -- PACHACUTEC  
    (  992, 'IE 136 SANTISIMA VIRGEN MARIA AUXILIADORA', 'AV. VICTOR MANUEL MAURTUA' ),             -- PARCONA
    (  992, 'IE 18 MARIA INMACULADA', 'AV. HIPOLITO UNANUE SN' ),
    (  992, 'IE 22320 ', 'AV. LUIS WUFFARDEN 180' ),
    (  992, 'IE 22718 LUIS ABRAHAM ELIAS GHEZZI', 'CALLE LOS CLAVELES S/N - COOPERATIVA SANTA ROSA' ),
    (  992, 'IE JOSE MARIA ARGUEDAS', 'CALLE JOSE BALTA' ),
    (  992, 'IE VICTOR MANUEL MAURTA', 'AV. SIMON BOLIVAR' ),
    (  993, 'IE GABINO CHACALTANA HERNANDEZ', 'AV. LUIS CAMINO DIBOS' ),                            -- PUEBLO NUEVO
    (  994, 'IE 22661 JUAN DONAIRE VIZARRETA', 'CALLE 8 LT 5 MZ F' ),                               -- SALAS
    (  994, 'IE GENERAL JUAN PABLO FERNANDINI', 'JR. TACNA 111' ),
    (  995, 'IE CATALINA BUENDIA DE PECHO', 'AV.  9 DE OCTUBRE' ),									-- SAN JOSE DE LOS MOLINOS
    (  996, 'IE GENARO HUAMAN ACUACHE', 'AV. TUPAC AMARU' ),                                        -- SAN JUAN BAUTISTA
    (  997, 'IE 22355 MARIA DARQUEA DE CABRERA', 'PANAMERICANA SUR' ),                              -- SANTIAGO
    (  997, 'IE FRAY RAMON ROJAS', 'PANAMERICANA SUR' ),
    (  997, 'IE SEBASTIAN BARRANCA', 'PANAMERICANA SUR' ),
    (  998, 'IE 138 SANTA ROSA DE LIMA', 'CALLE CALLAO' ),                                          -- SUBTANJALLA
    (  998, 'IE 22358', 'ABRAHAM VALDELOMAR 279' ),
    (  998, 'IE 22382 JUAN PABLO II', 'CALLE VIRGEN DEL ROSARIO DEL YAUCA E 14' ),
    (  998, 'IE ANDRES AVELINO CACERES', 'CALLE AMAZONAS' ),
    (  999, 'IE 22360 FRANCISCO PEREZ ANAMPA', 'AV. PRINCIPAL' ),                                   -- TATE
    (  999, 'IE RICARDO PALMA', 'AV. TATE LA CAPILLA' ),
    ( 1000, 'IE 22361 MANUEL PABLO OLAECHEA', 'AV. PRINCIPAL' ),                                    -- YAUCA DEL ROSARIO

-- ---- ICA --- NAZCA
    ( 1001, 'IE 22393', 'CALLE ELOY VALENCIA' ),                                                    -- CHANGUILLO
    ( 1002, 'IE JOSE MANUEL MEZA', 'CALLE MAMALA' ),                                                -- EL INGENIO
    ( 1003, 'IE 23544 CORONEL FRANCISCO BOLOGNESI', 'AV. LAS PETUNIAS' ),                           -- MARCONA
    ( 1003, 'IE ALMIRANTE MIGUEL GRAU', 'AV. LOS NOGALES' ),
    ( 1004, 'IE 22401 MARIA REICHE NEWMAN', 'AV. MARIA REICHE NEWMAN 205' ),                        -- NAZCA
    ( 1004, 'IE 22402 MICAELA BASTIDAS', 'CALLE LIMA  990' ),
    ( 1004, 'IE JOSEFINA MEJIA DE BOCANEGRA', 'AV. AGUSTIN BOCANEGRA Y PRADA 1319' ),
    ( 1004, 'IE SIMON RODRIGUEZ', 'AV. LA CULTURA' ),
    ( 1005, 'IE 22411 JOSUE S LANCHO ROJAS', 'CALLE INCA ROCA' ),                                   -- VISTA ALEGRE
    ( 1005, 'IE FERMIN DEL CASTILLO ARIAS', 'PRLG YAHUAR HUACA' ),

-- ---- ICA --- PALPA
    ( 1006, 'IE 22421 NUESTRA SEÑORA DE LAS MERCEDES', 'AV. NUEVA ESPERANZA' ),                     -- LLIPATA
    ( 1007, 'IE FERMIN TANGUIS', 'CALLE SAN ISIDRO 120' ),                                          -- PALPA
    ( 1007, 'IE RAUL PORRAS BARRENECHEA', 'AV. GARCILAZO DE LA VEGA' ),
    ( 1008, 'IST PALPA', 'CALLE ICA 200' ),                                                         -- RIO GRANDE
    ( 1009, 'IE 22438 DE LAS MONJAS', 'ANTIGUA PANAMERICANA SUR - ALTURA KM 385' ),                 -- SANTA CRUZ
    ( 1010, 'IE 22441 SANTA ANA', 'CALLE PALPA' ),                                                  -- TIBILLO

-- ---- ICA --- PISCO
    ( 1011, 'IE 22448 PORSIA SENISSE DE ARRIOLA SECUNDARIA', 'ALTURA DE LA PLAZA DE ARMAS' ),       -- HUANCANO
    ( 1012, 'IE 22451 BEATITA DE HUMAY', 'CALLE DERECHA S/N - VIA LOS LIBERTADORES WARI' ),         -- HUMAY
    ( 1013, 'IE 22445 GERARDO RAUL MENDOZA ESCATE', 'AV. FEDERICO URANGA' ),                        -- INDEPENDENCIA
    ( 1013, 'IE INDEPENDENCIA', 'AV. FEDERICO URANGA' ),
    ( 1014, 'IE 22489', 'AV. LOS LIBERTADORES S/N' ),                                               -- PARACAS
    ( 1015, 'IE 182', 'CALLE AREQUIPA 387' ),                                                       -- PISCO
    ( 1015, 'IE 22455 JOSE DE LA TORRE UGARTE', 'AV. MARISCAL CASTILLA 310' ),
    ( 1015, 'IE 22459 JULIO C TELLO', 'CALLE JUAN JOSE PINILLOS 301' ),
    ( 1015, 'IE 22462 HILDA BRINGAS QUINTANILLA', 'CALLE ANGEL ASTENGO 118' ),
    ( 1015, 'IE 22464 REPUBLICA ARGENTINA', 'CALLE RAUL PORRAS BARRENECHEA 200' ),
    ( 1015, 'IE 22540 NUESTRA SEÑORA DE GUADALUPE', 'AV. SAN MARTIN  954' ),
    ( 1015, 'IE 22544 PEDRO PABLO CASTRO PELAEZ', 'AV. SAN MARTIN 604' ),
    ( 1015, 'IE BANDERA DEL PERU', 'CALLE RAUL PORRAS BARRENECHEA' ),
    ( 1015, 'IE EMBLEMATICA JOSE DE SAN MARTIN', 'CALLE JOSE BALTA 769' ),
    ( 1016, 'IE 22472 RENAN ELIAS OLIVERA', 'CALLE FRANCISCO BOLOGNESI' ),                          -- SAN ANDRES
    ( 1016, 'IE 22473 SANTISIMA VIRGEN INMACULADA CONCEPCION', 'CALLE GRECIA 511' ),
    ( 1017, 'IE 22468 MARIA PARADO DE BELLIDO', 'AV. COPACABANA S/N' ),                             -- SAN CLEMENTE
    ( 1017, 'IE JOSE CARLOS MARIATEGUI', 'AV. LOS LIBERTADORES 720' ),
    ( 1018, 'IE 22471 TUPAC AMARU INCA', 'AV. TUPAC AMARU INCA MZ B LT 2' ),                        -- TUPAC AMARU INCA
    ( 1018, 'IE CAPITAN FAP JOSE ABELARDO QUIÑONES GONZALES', 'AV. TUPAC AMARU MZ 12A LT 1' )