use Onpe;
insert LocalVotacion(idDistrito, RazonSocial, Direccion) values

-- ---- MADRE DE DIOS --- MANU                            
	( 1487, 'IE 50876 BASICA REGULAR- BOCA MANU', 'CALLE BOCA MANU S/N(INGRESO)' ),					-- FITZCARRALD
	( 1488, 'IE 52082 HORACIO ZEVALLOS GAMEZ', 'AV. INDEPENDENCIA S/N' )  ,							-- HUEPETUHE
	( 1489, 'IE 52079 BOCA COLORADO', 'AV. MADRE DE DIOS' ) ,										-- MADRE DE DIOS
	( 1490, 'IE JOSE CARLOS MARIATEGUI', 'AV. ESPERANZA S/N' ),										-- MANU

 -- ---- MADRE DE DIOS --- TAHUAMANU
	( 1491, 'IE EMBLEMATICA DOS DE MAYO', 'AV. JOSE ALDAMIZ S/N' ),									-- IBERIA
	( 1492, 'IE 53003 ELENA BERTHA', 'AV. EL SOL S/N' ),											-- IÑAPARI
	( 1493, 'IE OLLANTA HUMALA TASSO', 'AV. VICTOR CUEVA THAMAYO' ),								-- TAHUAMANU

 -- ---- MADRE DE DIOS --- TAMBOPATA
	(  1494, 'IE 52040 SIMON BOLIVAR', 'IE 52040 SIMON BOLIVAR' ),									-- INAMBARI
	(  1495, 'IE 52062 JAVIER HERAUD', 'JR. LAS PIEDRAS' ),											-- LABERINTO	
	(  1496, 'IE HEROES DE ILLAMPU', 'PSJ. AYACUCHO S/N' ),											-- LAS PIEDRAS
	(  1496, 'IE JORGE CHAVEZ RENGIFO', 'AV. MADRE DE DIOS S/N' ),
	(  1497, 'IE 52001 SANTA ROSA', 'AV. CIRNCUNVALACION S/N ESQ CON PSJE ZOILA ANCORA' ),			-- TAMBOPATA
	(  1497, 'IE 52010 LA PASTORA', 'CARRETERA PUERTO MALDONADO - CUSCO KM6(INGRESO POR PASAJE JUAN HIDALGO PAREDES' ),
	(  1497, 'IE 52181 SEÑOR DE LOS MILAGROS', 'AV. PROCERES CUADRA 4' ),
	(  1497, 'IE CARLOS FERMIN FITZCARRALD', 'AV. MADRE DE DIOS CUADRA 4' ),
	(  1497, 'IE DOS DE MAYO', 'AV. DOS DE MAYO CUADRA 17' ),
	(  1497, 'IE FAUSTINO MALDONADO', 'JR. AREQUIPA 539' ),
	(  1497, 'IE NUESTRA SEÑORA DE LAS MERCEDES', 'AV. ERNESTO RIVERO / JR. CUSCO' )