use Onpe;
insert LocalVotacion(idDistrito, RazonSocial, Direccion) values

-- ---- MOQUEGUA --- GENERAL SANCHEZ CERRO
	( 1498, 'IE TUPAC AMARU II', 'CALLE SAN MARTIN SN' ),	  										-- CHOJATA
	( 1499, 'IE SAN PEDRO', 'CALLE MOQUEGUA SN' ),				 									-- COALAQUE
	( 1500, 'IE MARISCAL RAMON CASTILLA', 'CALLE MOQUEGUA 104' ),									-- ICHUÑA				
	( 1501, 'IE LA CAPILLA', 'CALLE DEL OLVIDO SN'),				 								-- LA CAPILLA
	( 1502, 'IE ELIAS AGUIRRE ROMERO', 'CALLE LAS NUECES SN'),									 	-- LLOQUE
	( 1503, 'IE RICARDO PALMA', 'CALLE FRANCISCO B CAMPOS SN'),										-- MATALAQUE
	( 1504, 'IE MARISCAL DOMINGO NIETO', 'CALLE 3 DE ABRIL 404'),									-- OMATE
	( 1505, 'IE. 43081 HORACIO ZEVALLOS GAMEZ', 'CALLE 28 DE JULIO 101' ),							-- PUQUINA
	( 1506, 'IE VICTOR RAUL HAYA DE LA TORRE', 'CALLE LOS OLIVOS 107' ),							-- QUINISTAQUILLAS
	( 1507, 'IE 43096 JOSE ABELARDO QUIÑONES', 'AV. QUIÑONEZ SN' ),									-- UBINAS
	( 1507, 'IE 43157 SALINAS CHIVIRIA', 'CALLE SANTA LUCIA DE SALINAS SN' ),
	( 1507, 'IE ALMIRANTE MIGUEL GRAU SEMINARIO', 'CALLE MIGUEL GRAU SN' ),
	( 1507, 'IE DE TASSA', 'CARRETERA AREQUIPA YUNGA SN' ),
	( 1507, 'IE JOSE CARLOS MARIATEGUI', 'CALLE CONCEPCION SN' ),
	( 1507, 'IE JOSE MANUEL UBALDE ZEVALLOS', 'CALLE LOS ÁNGELES SN' ),
	( 1508, 'COLISEO MUNICIPAL DE YUNGA', 'CALLE ALTO CCATA SN' ),									-- YUNGA

-- ---- MOQUEGUA --- ILO
	( 1509, 'IE 43130 EL ALGARROBAL', 'AV. PRINCIPAL KM 15' ),	  									-- EL ALGARROBAL
	( 1510, 'IE 43031 JHON F KENNEDY', 'AV. ANDRES A CACERES SN' ),									-- ILO
	( 1510, 'IE 43033 VIRGEN DEL ROSARIO', 'AV. MARIANO LINO URQUIETA SN' ),
	( 1510, 'IE CARLOS ALBERTO CONDE VASQUEZ', 'AV. MARIANO LINO URQUIETA 480' ),
	( 1510, 'IE DANIEL BECERRA OCAMPO', 'AV. MARIANO LINO URQUIETA 588' ),
	( 1510, 'IE JORGE BASADRE GROHMANN', 'ALTO ILO ARENAL SN' ),
	( 1510, 'IE MERCEDES CABELLO DE CARBONERA', 'AV. MARIANO LINO URQUIETA SN' ),
	( 1510, 'IEP SAN LUIS', 'AV. LA CULTURA 107' ),
	( 1510, 'UNIVERSIDAD JOSE CARLOS MARIATEGUI', 'AV. UNIVERSITARIA SN' ),
	( 1511, 'IE AMERICO GARIBALDI GHERSI', 'AAV. AMERICO GARIBALDI SN' ),							-- PACOCHA

-- ---- MOQUEGUA --- MARISCAL NIETO
	( 1512, 'IE HORACIO ZEBALLOS GAMEZ', 'CALLE PROGRESO SN' ),										-- CARUMAS
	( 1513, 'IE 43051', 'PSJ. EL PEDREGAL SN' ),													-- CUCHUMBAYA
	( 1513, 'IEI 325', 'PSJ. EL PEDREGAL SN' ),
	( 1514, 'IE 43014 ANGELA BARRIOS DE ESPINOZA', 'CALLE ANCASH 201' ),							-- MOQUEGUA
	( 1514, 'IE 43022 AMPARO BALUARTE', 'CALLE PRIMERO DE MAYO SN' ),
	( 1514, 'IE CORONEL MANUEL C DE LA TORRE', 'CALLE DANIEL BECERRA OCAMPO SN' ),
	( 1514, 'IE DANIEL BECERRA OCAMPO', 'PRLG. AMAZONAS SN' ),
	( 1514, 'IE LUIS ERNESTO PINTO SOTOMAYOR', 'CALLE TACNA SN' ),
	( 1514, 'IE MARISCAL DOMINGO NIETO', 'CALLE CARUMAS SN' ),
	( 1514, 'IE MODELO SAN ANTONIO', 'AV. DANIEL BECERRA OCAMPO SN' ),
	( 1514, 'IE SIMON BOLIVAR', 'AV. 25 DE NOVIEMBRE SN' ),
	( 1515, 'IE 43016 VITALIANO BECERRA HERRERA', 'CALLE CAHUIDE SN' ),								-- SAMEGUA
	( 1516, 'IE AGROPECUARIA ARTESANAL - ARUNTAYA', 'CALLE ARUNTAYA SN' ),							-- SAN CRISTOBAL
	( 1516, 'IE CESAR VALLEJO', 'CALLE NUEVA SN' ),
	( 1516, 'IE MIGUEL CONSTANTINIDES ROSADO', 'CALLE EL MORO SN' ),
	( 1516, 'IE TITIRE', 'CARRETERA MOQUEGUA PUNO KM 104' ),
	( 1517, 'IE JOSE CARLOS MARIATEGUI -PRIMARIA', 'CALLE NICOLAS LA TORRE SN' ),					-- TORATA
	( 1517, 'IE JOSE CARLOS MARIATEGUI SECUNDARIA', 'CALLE ALFONSO UGARTE SN' )