use Onpe;
insert LocalVotacion(idDistrito, RazonSocial, Direccion) values

-- ---- PASCO --- DANIEL ALCIDES CARRION
	( 1518, 'IE N°86 AGROPECUARIO FELIX ELIAS RAYMUNDO HUANCA', 'PRLG LIBERTAD S/N' ),				-- CHACAYAN
	( 1519, 'IE 34132', 'BARRIO PAMPA VERDE BAJA' ),												-- GOYLLARISQUIZGA
	( 1520, 'IE 34135 DOS DE MAYO - PAUCAR', 'BARRIO PUEBLO JOVEN S/N'),							-- PAUCAR
	( 1520, 'IE INDEPENDENCIA', 'CCPP INDEPENDENCIA'),
	( 1520, 'IE 34137 GRAN MARISCAL RAMON CASTILLA', 'BARRIO HUANCALPAY'),
	( 1521, 'IE 34139 ALFONSO UGARTE', 'CALLE YANAHUANCA SN'),										-- SAN PEDRO DE PILLAO
	( 1522, 'IE GENERAL CORDOVA', 'BARRIO TUSICANCHA S/N'),											-- SANTA ANA DE TUSI
	( 1522, 'IE JUANA OSORIO ZAMBRANO - SECUNDARIO', 'CCPP ANTAPIRCA'),
	( 1523, 'IE 34143 HIPOLITO UNANUE', 'AV. CHINCHAYSUYO S/N'),									-- TAPUC
	( 1523, 'IE CCHH TUPAC AMARU', 'AV. JOSE FERREYRA S/N'),
	( 1524, 'IE 34152 MARCELIANO RIOS VIANCHI', 'CARRETERA MARGINAL KM 13'),						-- VILCABAMBA
	( 1525, 'IE 35004 SANTO DOMINGO SAVIO', 'JR. SOLEDAD N°160'),									-- YANAHUANCA
	( 1525, 'IE COL NAC ERNESTO DIEZ CANSECO', 'JR. SAN MARTIN 303'),

-- ---- PASCO --- OXAPAMPA
	( 1526, 'IE 34216 JOSEPH WALIJEWFKI FLYBO', 'CALLE CIRCUNVALCION S/N'),							-- CHONTABAMBA
	( 1527, 'IE N°34456 "VILLA CARIÑO"', 'AV. FERNANDO BELAUNDE TERRY S/N'),						-- CONSTITUCION
	( 1528, 'IE 34221 INTEGRADO-NUESTRA SEÑORA DEL CARMEN (NIVEL SECUNDARIA)', 'JR. LAS GARDENIAS S/N'),	-- HUANCABAMBA
	( 1528, 'IE 34221 INTEGRADO-NUESTRA SEÑORA DEL CARMEN (NIVEL INICIAL)', 'JR. LAS PALMERAS S/N'),
	( 1528, 'IE 34221 INTEGRADO-NUESTRA SEÑORA DEL CARMEN (NIVEL PRIMARIA)', 'AV. LAS PALMERAS S/N'),
	( 1529, 'IE 34622 LIBERTADOR MARISCAL CASTILLA', 'JR. MARISCAL CASTILLA SN CDRA 5'),			-- OXAPAMPA
	( 1529, 'IE INTEGRADO DE CIENCIAS Y HUMANIDADES DIVINA PASTORA', 'JR. MARISCAL CASTILLA S/N'),
	( 1530, 'IE 34309 PUERTO LAGUNA RAYA - LOMA LINDA', 'CARRETERA MARGINAL VILLARICA-ISCOZACION S/N'),		-- PALCAZU
	( 1530, 'IE 34338 PRIMARIA', 'AV. ANTONIO RUFNER MERSHULER S/N'),
	( 1530, 'IE 34380 AGROPECUARIA -7 DE JUNIO', 'AV. MARGINAL S/N'),
	( 1530, 'IE COLEGIO NACIONAL ISCOZACIN', 'JR. JULIO SHITAGORI S/N'),
	( 1531, 'IE 34226 RVDO PADRE JOSE EGG', 'AV. LOS COLONOS 251'),									-- POZUZO
	( 1531, 'IE DE CIENCIAS Y HUMANIDADES TUPAC AMARU', 'CALLE MAESTRO CAROLINA EGG 260'),
	( 1532, 'IE 34270 AGRO INDUSTRIAL MANCO CAPAC', 'CALLE MIRAFLORES S/N'),						-- PUERTO BERMUDEZ
	( 1532, 'E 34277 INTEGRADO BIL', 'CALLE ARAROSHI S/N'),
	( 1532, 'IE 34618 REMIGIO MORALES BERMUDEZ', 'AV. REMIGIO MORALES BERMUDEZ S/N'),
	( 1533, 'IE 34237 MERCEDES INDACOCHEA', 'PSJ. SAN JUAN S/N'),									-- VILLA RICA
	( 1533, 'IE 34418 SANTA APOLONIA', 'AV. LEOPOLDO KRAUSSE S/N'),
	( 1533, 'INSTITUTO SUPERIOR TECNOLOGICO ALEXANDER VON HUMBOLD.', 'JR. ANTONIO RITCHEL S/N'),

-- ---- PASCO --- PASCO
	( 1534, 'IE 3 ANTENOR RIZO PATRON LEQUERICA', 'PLAZA CARRION N 171'),							-- CHAUPIMARCA
	( 1534, 'IE 35002 ZOILA AMORETTI DE ODRIA', 'JR. BOLOGNESI 296'),
	( 1534, 'IE DANIEL ALCIDES CARRION', 'AV. CIRCUNVALACION TUPAC AMARU 264'),
	( 1535, 'IE PRIMARIA 34005 HUACHON', 'CALLE 28 DE JULIO S/N'),									-- HUACHON
	( 1536, 'IE SAN JUAN BAUTISTA', 'JR. EL PROGRESO 100'),											-- HUARIACA
	( 1537, 'IE ANTONIO ALVAREZ DE ARENALES', 'JR. DOS DE MAYO S/N'),								-- HUAYLLAY
	( 1538, 'IE 34018 FRANCISCO HUARICAPCHA MEZA', 'AV. UNION S/N'),								-- NINACACA
	( 1539, 'IE 34020 EPIFANIO REY CAMARENA LEIVA', 'JR. BOLIVAR S/N'),								-- PALLANCHACRA
	( 1540, 'I.E.I ALFONSO UGARTE', 'JR. FRATERNIDAD N°360'),										-- PAUCARTAMBO
	( 1541, 'IE 34057 DANIEL ALCIDES CARRION', 'CALLE HUARIACA S/N'),								-- SAN FCO DE ASIS DE YARUSYACAN
	( 1541, 'IE AGROPECUARIO SAN FRANCISCO DE ASIS', 'PLAZA DE ARMAS S/N'),
	( 1542, 'COLEGIO NACIONAL SIMON BOLIVAR', 'CALLE SUCRE SN'),									-- SIMON BOLIVAR
	( 1542, 'IE 31774 INTEGRADO - SAN ANDRES', 'PSJ. CAMPAMENTO SAN ANDRES S/N'),
	( 1542, 'IE 34032 EPM - LOS MARTIRES DE RANCAS', 'CALLE JUAN VELASCO ALVARADO S/N'),
	( 1543, 'IE DE CIENCIAS Y HUMANIDADES - APOSTOL SAN PABLO', 'AV. TICLAHUANCA 102'),				-- TICLACAYAN
	( 1544, 'IE JOSE CARLOS MARIATEGUI', 'AV. TUPAC AMARU S/N'),									-- TINYAHUARCO
	( 1545, 'IE 34046 VICCO', 'AV. CERRO DE PASCO S/N'),											-- VICCO
	( 1546, 'IE INTEGRADA 34047 CESAR VALLEJO', 'AV. LA CULTURA S/N'),								-- YANACANCHA
	( 1546, 'IE INTEGRADA MARIA PARADO DE BELLIDO', 'AV. LAS AMÉRICAS S/N')