use Onpe;
insert LocalVotacion(idDistrito, RazonSocial, Direccion) values

-- ---- TUMBES --- CONTRALMIRANTE VILLAR
	( 1825, 'IE 065 JOSE OLAYA BALANDRA', 'BARRIO SEÑOR DE LOS MILAGROS SN' ),						-- CANOAS DE PUNTA SAL
	( 1826, 'IE CIRO ALEGRIA BAZAN', 'AV. CAÑAVERAL SN' ),											-- CASITAS
	( 1827, 'IE CONTRALMIRANTE VILLAR', 'AV. REPUBLICA DEL PERU SN' ),								-- ZORRITOS

-- ---- TUMBES --- TUMBES
	( 1828, 'IE 020 HILARIO CARRASCO VINCES', 'CALLE INCA YUPANQUI SN' ),							-- CORRALES
	( 1828, 'IE 7 DE ENERO', 'PSJ. SIETENERINO SN' ),
	( 1829, 'IE 031 VIRGEN DEL CARMEN', 'CALLE PIURA 1536' ),										-- LA CRUZ
	( 1830, 'IE ALIPIO ROSALES CAMACHO', 'AV. ALIPIO ROSALES CAMACHO 452' ),						-- PAMPAS DE HOSPITAL
	( 1831, 'IE SAN JACINTO', 'CARRETERA PLATEROS SN' ),											-- SAN JACINTO
	( 1832, 'IE SAN JUAN DE LA VIRGEN', 'CALLE 24 DE FEBRERO SN' ),								    -- SAN JUAN DE LA VIRGEN
	( 1833, 'CENTRO DE EDUCACION TECNICO PRODUCTIVO 002', 'PSJ. CENECAPE 100' ),					-- TUMBES
	( 1833, 'CN EL TRIUNFO', 'PSJ. EL TRIUNFO SN' ),
	( 1833, 'IE 001 JOSE LISHNER TUDELA', 'AV. TUMBES 793' ),
	( 1833, 'IE 002 RAMON CASTILLA', 'AV. MARISCAL CASTILLA 652' ),
	( 1833, 'IE 011 CESAR VALLEJO', 'CALLE GENERAL MORZAN 321' ),
	( 1833, 'IE 013 LEONARDO RODRIGUEZ ARELLANO', 'AV. TUMBES NORTE 719' ),
	( 1833, 'IE 117 RIGOBERTO MEZA CHUNGA', 'CALLE MORALES BERMUDEZ 200' ),
	( 1833, 'IE EJERCITO ANDRES AVELINO CACERES', 'PRLG FRANCISCO NAVARRETE SN' ),
	( 1833, 'IE INMACULADA CONCEPCION', 'PRLG TARAPACA SN' ),
	( 1833, 'ISP JOSE ANTONIO ENCINAS', 'AV. TUMBES NORTE 1254' ),
	( 1833, 'IST CAPITAN FAP JOSE ABELARDO QUIÑONES', 'AV. TUMBES NORTE 1228' ),

-- ---- TUMBES --- ZARUMILLA
	( 1834, 'IE 0098 EL GRAN CHILIMASA', 'AV. JAPON SN' ),											-- AGUAS VERDES
	( 1834, 'IE 130 28 DE JULIO', 'JR. LOS PROCERES SN' ),
	( 1835, 'IE 100 MANUEL CATALINO FARIAS MORAN', 'AV. ZARUMILLA SN' ),							-- MATAPALO
	( 1836, 'IE 104 INMACULADA CONCEPCION', 'AV. RAMON CASTILLA SN' ),								-- PAPAYAL
	( 1837, 'IE ZARUMILLA', 'JR. ABAD PUELL SN' ),													-- ZARUMILLA
	( 1837, 'IST 24 DE JULIO DE ZARUMILLA', 'AV. SANTA ROSA SN' )